// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: drill/v1/billing.proto

package drillv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`        // "subscription" or "pack"
	Plan          string                 `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan,omitempty"`        // e.g. "pro" (for subscription)
	Minutes       int32                  `protobuf:"varint,3,opt,name=minutes,proto3" json:"minutes,omitempty"` // minute pack size (for pack)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutRequest) Reset() {
	*x = CheckoutRequest{}
	mi := &file_drill_v1_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutRequest) ProtoMessage() {}

func (x *CheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutRequest.ProtoReflect.Descriptor instead.
func (*CheckoutRequest) Descriptor() ([]byte, []int) {
	return file_drill_v1_billing_proto_rawDescGZIP(), []int{0}
}

func (x *CheckoutRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CheckoutRequest) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *CheckoutRequest) GetMinutes() int32 {
	if x != nil {
		return x.Minutes
	}
	return 0
}

type CheckoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // Stripe checkout URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutResponse) Reset() {
	*x = CheckoutResponse{}
	mi := &file_drill_v1_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutResponse) ProtoMessage() {}

func (x *CheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutResponse.ProtoReflect.Descriptor instead.
func (*CheckoutResponse) Descriptor() ([]byte, []int) {
	return file_drill_v1_billing_proto_rawDescGZIP(), []int{1}
}

func (x *CheckoutResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type PortalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortalRequest) Reset() {
	*x = PortalRequest{}
	mi := &file_drill_v1_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortalRequest) ProtoMessage() {}

func (x *PortalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortalRequest.ProtoReflect.Descriptor instead.
func (*PortalRequest) Descriptor() ([]byte, []int) {
	return file_drill_v1_billing_proto_rawDescGZIP(), []int{2}
}

type PortalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // Stripe billing portal URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortalResponse) Reset() {
	*x = PortalResponse{}
	mi := &file_drill_v1_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortalResponse) ProtoMessage() {}

func (x *PortalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortalResponse.ProtoReflect.Descriptor instead.
func (*PortalResponse) Descriptor() ([]byte, []int) {
	return file_drill_v1_billing_proto_rawDescGZIP(), []int{3}
}

func (x *PortalResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_drill_v1_billing_proto protoreflect.FileDescriptor

const file_drill_v1_billing_proto_rawDesc = "" +
	"\n" +
	"\x16drill/v1/billing.proto\x12\bdrill.v1\"S\n" +
	"\x0fCheckoutRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04plan\x18\x02 \x01(\tR\x04plan\x12\x18\n" +
	"\aminutes\x18\x03 \x01(\x05R\aminutes\"$\n" +
	"\x10CheckoutResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x0f\n" +
	"\rPortalRequest\"\"\n" +
	"\x0ePortalResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2\x90\x01\n" +
	"\x0eBillingService\x12A\n" +
	"\bCheckout\x12\x19.drill.v1.CheckoutRequest\x1a\x1a.drill.v1.CheckoutResponse\x12;\n" +
	"\x06Portal\x12\x17.drill.v1.PortalRequest\x1a\x18.drill.v1.PortalResponseB3Z1github.com/btc/drill/internal/pb/drill/v1;drillv1b\x06proto3"

var (
	file_drill_v1_billing_proto_rawDescOnce sync.Once
	file_drill_v1_billing_proto_rawDescData []byte
)

func file_drill_v1_billing_proto_rawDescGZIP() []byte {
	file_drill_v1_billing_proto_rawDescOnce.Do(func() {
		file_drill_v1_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_drill_v1_billing_proto_rawDesc), len(file_drill_v1_billing_proto_rawDesc)))
	})
	return file_drill_v1_billing_proto_rawDescData
}

var file_drill_v1_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_drill_v1_billing_proto_goTypes = []any{
	(*CheckoutRequest)(nil),  // 0: drill.v1.CheckoutRequest
	(*CheckoutResponse)(nil), // 1: drill.v1.CheckoutResponse
	(*PortalRequest)(nil),    // 2: drill.v1.PortalRequest
	(*PortalResponse)(nil),   // 3: drill.v1.PortalResponse
}
var file_drill_v1_billing_proto_depIdxs = []int32{
	0, // 0: drill.v1.BillingService.Checkout:input_type -> drill.v1.CheckoutRequest
	2, // 1: drill.v1.BillingService.Portal:input_type -> drill.v1.PortalRequest
	1, // 2: drill.v1.BillingService.Checkout:output_type -> drill.v1.CheckoutResponse
	3, // 3: drill.v1.BillingService.Portal:output_type -> drill.v1.PortalResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_drill_v1_billing_proto_init() }
func file_drill_v1_billing_proto_init() {
	if File_drill_v1_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_drill_v1_billing_proto_rawDesc), len(file_drill_v1_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_drill_v1_billing_proto_goTypes,
		DependencyIndexes: file_drill_v1_billing_proto_depIdxs,
		MessageInfos:      file_drill_v1_billing_proto_msgTypes,
	}.Build()
	File_drill_v1_billing_proto = out.File
	file_drill_v1_billing_proto_goTypes = nil
	file_drill_v1_billing_proto_depIdxs = nil
}
