// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: drill/v1/coach.proto

package drillv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CoachAnalysis struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId              string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Narrative           string                 `protobuf:"bytes,3,opt,name=narrative,proto3" json:"narrative,omitempty"`
	WeakestDimension    *string                `protobuf:"bytes,4,opt,name=weakest_dimension,json=weakestDimension,proto3,oneof" json:"weakest_dimension,omitempty"`
	ImprovingDimensions []string               `protobuf:"bytes,5,rep,name=improving_dimensions,json=improvingDimensions,proto3" json:"improving_dimensions,omitempty"`
	TopicGaps           []string               `protobuf:"bytes,6,rep,name=topic_gaps,json=topicGaps,proto3" json:"topic_gaps,omitempty"`
	SuggestedQuestionId *string                `protobuf:"bytes,7,opt,name=suggested_question_id,json=suggestedQuestionId,proto3,oneof" json:"suggested_question_id,omitempty"`
	SessionsAnalyzed    []string               `protobuf:"bytes,8,rep,name=sessions_analyzed,json=sessionsAnalyzed,proto3" json:"sessions_analyzed,omitempty"`
	CreateTime          *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Summary             *string                `protobuf:"bytes,10,opt,name=summary,proto3,oneof" json:"summary,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CoachAnalysis) Reset() {
	*x = CoachAnalysis{}
	mi := &file_drill_v1_coach_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoachAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoachAnalysis) ProtoMessage() {}

func (x *CoachAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_coach_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoachAnalysis.ProtoReflect.Descriptor instead.
func (*CoachAnalysis) Descriptor() ([]byte, []int) {
	return file_drill_v1_coach_proto_rawDescGZIP(), []int{0}
}

func (x *CoachAnalysis) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CoachAnalysis) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CoachAnalysis) GetNarrative() string {
	if x != nil {
		return x.Narrative
	}
	return ""
}

func (x *CoachAnalysis) GetWeakestDimension() string {
	if x != nil && x.WeakestDimension != nil {
		return *x.WeakestDimension
	}
	return ""
}

func (x *CoachAnalysis) GetImprovingDimensions() []string {
	if x != nil {
		return x.ImprovingDimensions
	}
	return nil
}

func (x *CoachAnalysis) GetTopicGaps() []string {
	if x != nil {
		return x.TopicGaps
	}
	return nil
}

func (x *CoachAnalysis) GetSuggestedQuestionId() string {
	if x != nil && x.SuggestedQuestionId != nil {
		return *x.SuggestedQuestionId
	}
	return ""
}

func (x *CoachAnalysis) GetSessionsAnalyzed() []string {
	if x != nil {
		return x.SessionsAnalyzed
	}
	return nil
}

func (x *CoachAnalysis) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *CoachAnalysis) GetSummary() string {
	if x != nil && x.Summary != nil {
		return *x.Summary
	}
	return ""
}

type GetCoachAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoachAnalysisRequest) Reset() {
	*x = GetCoachAnalysisRequest{}
	mi := &file_drill_v1_coach_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoachAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoachAnalysisRequest) ProtoMessage() {}

func (x *GetCoachAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_coach_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoachAnalysisRequest.ProtoReflect.Descriptor instead.
func (*GetCoachAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_drill_v1_coach_proto_rawDescGZIP(), []int{1}
}

type GetCoachAnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analysis      *CoachAnalysis         `protobuf:"bytes,1,opt,name=analysis,proto3,oneof" json:"analysis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoachAnalysisResponse) Reset() {
	*x = GetCoachAnalysisResponse{}
	mi := &file_drill_v1_coach_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoachAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoachAnalysisResponse) ProtoMessage() {}

func (x *GetCoachAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_coach_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoachAnalysisResponse.ProtoReflect.Descriptor instead.
func (*GetCoachAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_drill_v1_coach_proto_rawDescGZIP(), []int{2}
}

func (x *GetCoachAnalysisResponse) GetAnalysis() *CoachAnalysis {
	if x != nil {
		return x.Analysis
	}
	return nil
}

type RequestCoachAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCoachAnalysisRequest) Reset() {
	*x = RequestCoachAnalysisRequest{}
	mi := &file_drill_v1_coach_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCoachAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCoachAnalysisRequest) ProtoMessage() {}

func (x *RequestCoachAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_coach_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCoachAnalysisRequest.ProtoReflect.Descriptor instead.
func (*RequestCoachAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_drill_v1_coach_proto_rawDescGZIP(), []int{3}
}

func (x *RequestCoachAnalysisRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type RequestCoachAnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCoachAnalysisResponse) Reset() {
	*x = RequestCoachAnalysisResponse{}
	mi := &file_drill_v1_coach_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCoachAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCoachAnalysisResponse) ProtoMessage() {}

func (x *RequestCoachAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_coach_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCoachAnalysisResponse.ProtoReflect.Descriptor instead.
func (*RequestCoachAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_drill_v1_coach_proto_rawDescGZIP(), []int{4}
}

var File_drill_v1_coach_proto protoreflect.FileDescriptor

const file_drill_v1_coach_proto_rawDesc = "" +
	"\n" +
	"\x14drill/v1/coach.proto\x12\bdrill.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd8\x03\n" +
	"\rCoachAnalysis\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1c\n" +
	"\tnarrative\x18\x03 \x01(\tR\tnarrative\x120\n" +
	"\x11weakest_dimension\x18\x04 \x01(\tH\x00R\x10weakestDimension\x88\x01\x01\x121\n" +
	"\x14improving_dimensions\x18\x05 \x03(\tR\x13improvingDimensions\x12\x1d\n" +
	"\n" +
	"topic_gaps\x18\x06 \x03(\tR\ttopicGaps\x127\n" +
	"\x15suggested_question_id\x18\a \x01(\tH\x01R\x13suggestedQuestionId\x88\x01\x01\x12+\n" +
	"\x11sessions_analyzed\x18\b \x03(\tR\x10sessionsAnalyzed\x12;\n" +
	"\vcreate_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12\x1d\n" +
	"\asummary\x18\n" +
	" \x01(\tH\x02R\asummary\x88\x01\x01B\x14\n" +
	"\x12_weakest_dimensionB\x18\n" +
	"\x16_suggested_question_idB\n" +
	"\n" +
	"\b_summary\"\x19\n" +
	"\x17GetCoachAnalysisRequest\"a\n" +
	"\x18GetCoachAnalysisResponse\x128\n" +
	"\banalysis\x18\x01 \x01(\v2\x17.drill.v1.CoachAnalysisH\x00R\banalysis\x88\x01\x01B\v\n" +
	"\t_analysis\"3\n" +
	"\x1bRequestCoachAnalysisRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\"\x1e\n" +
	"\x1cRequestCoachAnalysisResponse2\xd0\x01\n" +
	"\fCoachService\x12Y\n" +
	"\x10GetCoachAnalysis\x12!.drill.v1.GetCoachAnalysisRequest\x1a\".drill.v1.GetCoachAnalysisResponse\x12e\n" +
	"\x14RequestCoachAnalysis\x12%.drill.v1.RequestCoachAnalysisRequest\x1a&.drill.v1.RequestCoachAnalysisResponseB3Z1github.com/btc/drill/internal/pb/drill/v1;drillv1b\x06proto3"

var (
	file_drill_v1_coach_proto_rawDescOnce sync.Once
	file_drill_v1_coach_proto_rawDescData []byte
)

func file_drill_v1_coach_proto_rawDescGZIP() []byte {
	file_drill_v1_coach_proto_rawDescOnce.Do(func() {
		file_drill_v1_coach_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_drill_v1_coach_proto_rawDesc), len(file_drill_v1_coach_proto_rawDesc)))
	})
	return file_drill_v1_coach_proto_rawDescData
}

var file_drill_v1_coach_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_drill_v1_coach_proto_goTypes = []any{
	(*CoachAnalysis)(nil),                // 0: drill.v1.CoachAnalysis
	(*GetCoachAnalysisRequest)(nil),      // 1: drill.v1.GetCoachAnalysisRequest
	(*GetCoachAnalysisResponse)(nil),     // 2: drill.v1.GetCoachAnalysisResponse
	(*RequestCoachAnalysisRequest)(nil),  // 3: drill.v1.RequestCoachAnalysisRequest
	(*RequestCoachAnalysisResponse)(nil), // 4: drill.v1.RequestCoachAnalysisResponse
	(*timestamppb.Timestamp)(nil),        // 5: google.protobuf.Timestamp
}
var file_drill_v1_coach_proto_depIdxs = []int32{
	5, // 0: drill.v1.CoachAnalysis.create_time:type_name -> google.protobuf.Timestamp
	0, // 1: drill.v1.GetCoachAnalysisResponse.analysis:type_name -> drill.v1.CoachAnalysis
	1, // 2: drill.v1.CoachService.GetCoachAnalysis:input_type -> drill.v1.GetCoachAnalysisRequest
	3, // 3: drill.v1.CoachService.RequestCoachAnalysis:input_type -> drill.v1.RequestCoachAnalysisRequest
	2, // 4: drill.v1.CoachService.GetCoachAnalysis:output_type -> drill.v1.GetCoachAnalysisResponse
	4, // 5: drill.v1.CoachService.RequestCoachAnalysis:output_type -> drill.v1.RequestCoachAnalysisResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_drill_v1_coach_proto_init() }
func file_drill_v1_coach_proto_init() {
	if File_drill_v1_coach_proto != nil {
		return
	}
	file_drill_v1_coach_proto_msgTypes[0].OneofWrappers = []any{}
	file_drill_v1_coach_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_drill_v1_coach_proto_rawDesc), len(file_drill_v1_coach_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_drill_v1_coach_proto_goTypes,
		DependencyIndexes: file_drill_v1_coach_proto_depIdxs,
		MessageInfos:      file_drill_v1_coach_proto_msgTypes,
	}.Build()
	File_drill_v1_coach_proto = out.File
	file_drill_v1_coach_proto_goTypes = nil
	file_drill_v1_coach_proto_depIdxs = nil
}
