// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: drill/v1/landing.proto

package drillv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListFeaturedQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeaturedQuestionsRequest) Reset() {
	*x = ListFeaturedQuestionsRequest{}
	mi := &file_drill_v1_landing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeaturedQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeaturedQuestionsRequest) ProtoMessage() {}

func (x *ListFeaturedQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_landing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeaturedQuestionsRequest.ProtoReflect.Descriptor instead.
func (*ListFeaturedQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_drill_v1_landing_proto_rawDescGZIP(), []int{0}
}

type ListFeaturedQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*Question            `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeaturedQuestionsResponse) Reset() {
	*x = ListFeaturedQuestionsResponse{}
	mi := &file_drill_v1_landing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeaturedQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeaturedQuestionsResponse) ProtoMessage() {}

func (x *ListFeaturedQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_landing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeaturedQuestionsResponse.ProtoReflect.Descriptor instead.
func (*ListFeaturedQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_drill_v1_landing_proto_rawDescGZIP(), []int{1}
}

func (x *ListFeaturedQuestionsResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *ListFeaturedQuestionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_drill_v1_landing_proto protoreflect.FileDescriptor

const file_drill_v1_landing_proto_rawDesc = "" +
	"\n" +
	"\x16drill/v1/landing.proto\x12\bdrill.v1\x1a\x17drill/v1/question.proto\"\x1e\n" +
	"\x1cListFeaturedQuestionsRequest\"r\n" +
	"\x1dListFeaturedQuestionsResponse\x120\n" +
	"\tquestions\x18\x01 \x03(\v2\x12.drill.v1.QuestionR\tquestions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount2z\n" +
	"\x0eLandingService\x12h\n" +
	"\x15ListFeaturedQuestions\x12&.drill.v1.ListFeaturedQuestionsRequest\x1a'.drill.v1.ListFeaturedQuestionsResponseB3Z1github.com/btc/drill/internal/pb/drill/v1;drillv1b\x06proto3"

var (
	file_drill_v1_landing_proto_rawDescOnce sync.Once
	file_drill_v1_landing_proto_rawDescData []byte
)

func file_drill_v1_landing_proto_rawDescGZIP() []byte {
	file_drill_v1_landing_proto_rawDescOnce.Do(func() {
		file_drill_v1_landing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_drill_v1_landing_proto_rawDesc), len(file_drill_v1_landing_proto_rawDesc)))
	})
	return file_drill_v1_landing_proto_rawDescData
}

var file_drill_v1_landing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_drill_v1_landing_proto_goTypes = []any{
	(*ListFeaturedQuestionsRequest)(nil),  // 0: drill.v1.ListFeaturedQuestionsRequest
	(*ListFeaturedQuestionsResponse)(nil), // 1: drill.v1.ListFeaturedQuestionsResponse
	(*Question)(nil),                      // 2: drill.v1.Question
}
var file_drill_v1_landing_proto_depIdxs = []int32{
	2, // 0: drill.v1.ListFeaturedQuestionsResponse.questions:type_name -> drill.v1.Question
	0, // 1: drill.v1.LandingService.ListFeaturedQuestions:input_type -> drill.v1.ListFeaturedQuestionsRequest
	1, // 2: drill.v1.LandingService.ListFeaturedQuestions:output_type -> drill.v1.ListFeaturedQuestionsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_drill_v1_landing_proto_init() }
func file_drill_v1_landing_proto_init() {
	if File_drill_v1_landing_proto != nil {
		return
	}
	file_drill_v1_question_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_drill_v1_landing_proto_rawDesc), len(file_drill_v1_landing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_drill_v1_landing_proto_goTypes,
		DependencyIndexes: file_drill_v1_landing_proto_depIdxs,
		MessageInfos:      file_drill_v1_landing_proto_msgTypes,
	}.Build()
	File_drill_v1_landing_proto = out.File
	file_drill_v1_landing_proto_goTypes = nil
	file_drill_v1_landing_proto_depIdxs = nil
}
