// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: drill/v1/question.proto

package drillv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Difficulty int32

const (
	Difficulty_DIFFICULTY_UNSPECIFIED Difficulty = 0
	Difficulty_DIFFICULTY_MEDIUM      Difficulty = 1
	Difficulty_DIFFICULTY_HARD        Difficulty = 2
)

// Enum value maps for Difficulty.
var (
	Difficulty_name = map[int32]string{
		0: "DIFFICULTY_UNSPECIFIED",
		1: "DIFFICULTY_MEDIUM",
		2: "DIFFICULTY_HARD",
	}
	Difficulty_value = map[string]int32{
		"DIFFICULTY_UNSPECIFIED": 0,
		"DIFFICULTY_MEDIUM":      1,
		"DIFFICULTY_HARD":        2,
	}
)

func (x Difficulty) Enum() *Difficulty {
	p := new(Difficulty)
	*p = x
	return p
}

func (x Difficulty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Difficulty) Descriptor() protoreflect.EnumDescriptor {
	return file_drill_v1_question_proto_enumTypes[0].Descriptor()
}

func (Difficulty) Type() protoreflect.EnumType {
	return &file_drill_v1_question_proto_enumTypes[0]
}

func (x Difficulty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Difficulty.Descriptor instead.
func (Difficulty) EnumDescriptor() ([]byte, []int) {
	return file_drill_v1_question_proto_rawDescGZIP(), []int{0}
}

type QuestionSource int32

const (
	QuestionSource_QUESTION_SOURCE_UNSPECIFIED     QuestionSource = 0
	QuestionSource_QUESTION_SOURCE_SEED            QuestionSource = 1
	QuestionSource_QUESTION_SOURCE_CUSTOM          QuestionSource = 2
	QuestionSource_QUESTION_SOURCE_COACH_GENERATED QuestionSource = 3
)

// Enum value maps for QuestionSource.
var (
	QuestionSource_name = map[int32]string{
		0: "QUESTION_SOURCE_UNSPECIFIED",
		1: "QUESTION_SOURCE_SEED",
		2: "QUESTION_SOURCE_CUSTOM",
		3: "QUESTION_SOURCE_COACH_GENERATED",
	}
	QuestionSource_value = map[string]int32{
		"QUESTION_SOURCE_UNSPECIFIED":     0,
		"QUESTION_SOURCE_SEED":            1,
		"QUESTION_SOURCE_CUSTOM":          2,
		"QUESTION_SOURCE_COACH_GENERATED": 3,
	}
)

func (x QuestionSource) Enum() *QuestionSource {
	p := new(QuestionSource)
	*p = x
	return p
}

func (x QuestionSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuestionSource) Descriptor() protoreflect.EnumDescriptor {
	return file_drill_v1_question_proto_enumTypes[1].Descriptor()
}

func (QuestionSource) Type() protoreflect.EnumType {
	return &file_drill_v1_question_proto_enumTypes[1]
}

func (x QuestionSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuestionSource.Descriptor instead.
func (QuestionSource) EnumDescriptor() ([]byte, []int) {
	return file_drill_v1_question_proto_rawDescGZIP(), []int{1}
}

type ListQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuestionsRequest) Reset() {
	*x = ListQuestionsRequest{}
	mi := &file_drill_v1_question_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuestionsRequest) ProtoMessage() {}

func (x *ListQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_question_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuestionsRequest.ProtoReflect.Descriptor instead.
func (*ListQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_drill_v1_question_proto_rawDescGZIP(), []int{0}
}

func (x *ListQuestionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListQuestionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*Question            `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuestionsResponse) Reset() {
	*x = ListQuestionsResponse{}
	mi := &file_drill_v1_question_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuestionsResponse) ProtoMessage() {}

func (x *ListQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_question_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuestionsResponse.ProtoReflect.Descriptor instead.
func (*ListQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_drill_v1_question_proto_rawDescGZIP(), []int{1}
}

func (x *ListQuestionsResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *ListQuestionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        *string                `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Prompt        string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Difficulty    Difficulty             `protobuf:"varint,5,opt,name=difficulty,proto3,enum=drill.v1.Difficulty" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Hints         *string                `protobuf:"bytes,7,opt,name=hints,proto3,oneof" json:"hints,omitempty"`
	Source        QuestionSource         `protobuf:"varint,8,opt,name=source,proto3,enum=drill.v1.QuestionSource" json:"source,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	ImageUrl      *string                `protobuf:"bytes,10,opt,name=image_url,json=imageUrl,proto3,oneof" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_drill_v1_question_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_question_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_drill_v1_question_proto_rawDescGZIP(), []int{2}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *Question) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Question) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Question) GetDifficulty() Difficulty {
	if x != nil {
		return x.Difficulty
	}
	return Difficulty_DIFFICULTY_UNSPECIFIED
}

func (x *Question) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Question) GetHints() string {
	if x != nil && x.Hints != nil {
		return *x.Hints
	}
	return ""
}

func (x *Question) GetSource() QuestionSource {
	if x != nil {
		return x.Source
	}
	return QuestionSource_QUESTION_SOURCE_UNSPECIFIED
}

func (x *Question) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Question) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

var File_drill_v1_question_proto protoreflect.FileDescriptor

const file_drill_v1_question_proto_rawDesc = "" +
	"\n" +
	"\x17drill/v1/question.proto\x12\bdrill.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"R\n" +
	"\x14ListQuestionsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"q\n" +
	"\x15ListQuestionsResponse\x120\n" +
	"\tquestions\x18\x01 \x03(\v2\x12.drill.v1.QuestionR\tquestions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x80\x03\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\tH\x00R\x06userId\x88\x01\x01\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x124\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\x0e2\x14.drill.v1.DifficultyR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x19\n" +
	"\x05hints\x18\a \x01(\tH\x01R\x05hints\x88\x01\x01\x120\n" +
	"\x06source\x18\b \x01(\x0e2\x18.drill.v1.QuestionSourceR\x06source\x12;\n" +
	"\vcreate_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12 \n" +
	"\timage_url\x18\n" +
	" \x01(\tH\x02R\bimageUrl\x88\x01\x01B\n" +
	"\n" +
	"\b_user_idB\b\n" +
	"\x06_hintsB\f\n" +
	"\n" +
	"_image_url*T\n" +
	"\n" +
	"Difficulty\x12\x1a\n" +
	"\x16DIFFICULTY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DIFFICULTY_MEDIUM\x10\x01\x12\x13\n" +
	"\x0fDIFFICULTY_HARD\x10\x02*\x8c\x01\n" +
	"\x0eQuestionSource\x12\x1f\n" +
	"\x1bQUESTION_SOURCE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14QUESTION_SOURCE_SEED\x10\x01\x12\x1a\n" +
	"\x16QUESTION_SOURCE_CUSTOM\x10\x02\x12#\n" +
	"\x1fQUESTION_SOURCE_COACH_GENERATED\x10\x032c\n" +
	"\x0fQuestionService\x12P\n" +
	"\rListQuestions\x12\x1e.drill.v1.ListQuestionsRequest\x1a\x1f.drill.v1.ListQuestionsResponseB3Z1github.com/btc/drill/internal/pb/drill/v1;drillv1b\x06proto3"

var (
	file_drill_v1_question_proto_rawDescOnce sync.Once
	file_drill_v1_question_proto_rawDescData []byte
)

func file_drill_v1_question_proto_rawDescGZIP() []byte {
	file_drill_v1_question_proto_rawDescOnce.Do(func() {
		file_drill_v1_question_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_drill_v1_question_proto_rawDesc), len(file_drill_v1_question_proto_rawDesc)))
	})
	return file_drill_v1_question_proto_rawDescData
}

var file_drill_v1_question_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_drill_v1_question_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_drill_v1_question_proto_goTypes = []any{
	(Difficulty)(0),               // 0: drill.v1.Difficulty
	(QuestionSource)(0),           // 1: drill.v1.QuestionSource
	(*ListQuestionsRequest)(nil),  // 2: drill.v1.ListQuestionsRequest
	(*ListQuestionsResponse)(nil), // 3: drill.v1.ListQuestionsResponse
	(*Question)(nil),              // 4: drill.v1.Question
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_drill_v1_question_proto_depIdxs = []int32{
	4, // 0: drill.v1.ListQuestionsResponse.questions:type_name -> drill.v1.Question
	0, // 1: drill.v1.Question.difficulty:type_name -> drill.v1.Difficulty
	1, // 2: drill.v1.Question.source:type_name -> drill.v1.QuestionSource
	5, // 3: drill.v1.Question.create_time:type_name -> google.protobuf.Timestamp
	2, // 4: drill.v1.QuestionService.ListQuestions:input_type -> drill.v1.ListQuestionsRequest
	3, // 5: drill.v1.QuestionService.ListQuestions:output_type -> drill.v1.ListQuestionsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_drill_v1_question_proto_init() }
func file_drill_v1_question_proto_init() {
	if File_drill_v1_question_proto != nil {
		return
	}
	file_drill_v1_question_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_drill_v1_question_proto_rawDesc), len(file_drill_v1_question_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_drill_v1_question_proto_goTypes,
		DependencyIndexes: file_drill_v1_question_proto_depIdxs,
		EnumInfos:         file_drill_v1_question_proto_enumTypes,
		MessageInfos:      file_drill_v1_question_proto_msgTypes,
	}.Build()
	File_drill_v1_question_proto = out.File
	file_drill_v1_question_proto_goTypes = nil
	file_drill_v1_question_proto_depIdxs = nil
}
