// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: drill/v1/sample.proto

package drillv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSampleSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSampleSessionRequest) Reset() {
	*x = GetSampleSessionRequest{}
	mi := &file_drill_v1_sample_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSampleSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSampleSessionRequest) ProtoMessage() {}

func (x *GetSampleSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_sample_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSampleSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSampleSessionRequest) Descriptor() ([]byte, []int) {
	return file_drill_v1_sample_proto_rawDescGZIP(), []int{0}
}

type GetSampleSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSampleSessionResponse) Reset() {
	*x = GetSampleSessionResponse{}
	mi := &file_drill_v1_sample_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSampleSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSampleSessionResponse) ProtoMessage() {}

func (x *GetSampleSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_sample_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSampleSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSampleSessionResponse) Descriptor() ([]byte, []int) {
	return file_drill_v1_sample_proto_rawDescGZIP(), []int{1}
}

func (x *GetSampleSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *GetSampleSessionResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type GetSampleEvaluationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSampleEvaluationRequest) Reset() {
	*x = GetSampleEvaluationRequest{}
	mi := &file_drill_v1_sample_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSampleEvaluationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSampleEvaluationRequest) ProtoMessage() {}

func (x *GetSampleEvaluationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_sample_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSampleEvaluationRequest.ProtoReflect.Descriptor instead.
func (*GetSampleEvaluationRequest) Descriptor() ([]byte, []int) {
	return file_drill_v1_sample_proto_rawDescGZIP(), []int{2}
}

type GetSampleEvaluationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Evaluation    *EvaluationResult      `protobuf:"bytes,1,opt,name=evaluation,proto3" json:"evaluation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSampleEvaluationResponse) Reset() {
	*x = GetSampleEvaluationResponse{}
	mi := &file_drill_v1_sample_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSampleEvaluationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSampleEvaluationResponse) ProtoMessage() {}

func (x *GetSampleEvaluationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_sample_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSampleEvaluationResponse.ProtoReflect.Descriptor instead.
func (*GetSampleEvaluationResponse) Descriptor() ([]byte, []int) {
	return file_drill_v1_sample_proto_rawDescGZIP(), []int{3}
}

func (x *GetSampleEvaluationResponse) GetEvaluation() *EvaluationResult {
	if x != nil {
		return x.Evaluation
	}
	return nil
}

type GetSampleEducatorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSampleEducatorRequest) Reset() {
	*x = GetSampleEducatorRequest{}
	mi := &file_drill_v1_sample_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSampleEducatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSampleEducatorRequest) ProtoMessage() {}

func (x *GetSampleEducatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_sample_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSampleEducatorRequest.ProtoReflect.Descriptor instead.
func (*GetSampleEducatorRequest) Descriptor() ([]byte, []int) {
	return file_drill_v1_sample_proto_rawDescGZIP(), []int{4}
}

type GetSampleEducatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analysis      *EducatorAnalysis      `protobuf:"bytes,1,opt,name=analysis,proto3" json:"analysis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSampleEducatorResponse) Reset() {
	*x = GetSampleEducatorResponse{}
	mi := &file_drill_v1_sample_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSampleEducatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSampleEducatorResponse) ProtoMessage() {}

func (x *GetSampleEducatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_sample_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSampleEducatorResponse.ProtoReflect.Descriptor instead.
func (*GetSampleEducatorResponse) Descriptor() ([]byte, []int) {
	return file_drill_v1_sample_proto_rawDescGZIP(), []int{5}
}

func (x *GetSampleEducatorResponse) GetAnalysis() *EducatorAnalysis {
	if x != nil {
		return x.Analysis
	}
	return nil
}

type GetSampleCoachRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSampleCoachRequest) Reset() {
	*x = GetSampleCoachRequest{}
	mi := &file_drill_v1_sample_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSampleCoachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSampleCoachRequest) ProtoMessage() {}

func (x *GetSampleCoachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_sample_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSampleCoachRequest.ProtoReflect.Descriptor instead.
func (*GetSampleCoachRequest) Descriptor() ([]byte, []int) {
	return file_drill_v1_sample_proto_rawDescGZIP(), []int{6}
}

type GetSampleCoachResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analysis      *CoachAnalysis         `protobuf:"bytes,1,opt,name=analysis,proto3" json:"analysis,omitempty"`
	ScoreTrend    []*ScoreTrendPoint     `protobuf:"bytes,2,rep,name=score_trend,json=scoreTrend,proto3" json:"score_trend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSampleCoachResponse) Reset() {
	*x = GetSampleCoachResponse{}
	mi := &file_drill_v1_sample_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSampleCoachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSampleCoachResponse) ProtoMessage() {}

func (x *GetSampleCoachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_sample_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSampleCoachResponse.ProtoReflect.Descriptor instead.
func (*GetSampleCoachResponse) Descriptor() ([]byte, []int) {
	return file_drill_v1_sample_proto_rawDescGZIP(), []int{7}
}

func (x *GetSampleCoachResponse) GetAnalysis() *CoachAnalysis {
	if x != nil {
		return x.Analysis
	}
	return nil
}

func (x *GetSampleCoachResponse) GetScoreTrend() []*ScoreTrendPoint {
	if x != nil {
		return x.ScoreTrend
	}
	return nil
}

type ScoreTrendPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	OverallScore  int32                  `protobuf:"varint,2,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreTrendPoint) Reset() {
	*x = ScoreTrendPoint{}
	mi := &file_drill_v1_sample_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreTrendPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreTrendPoint) ProtoMessage() {}

func (x *ScoreTrendPoint) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_sample_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreTrendPoint.ProtoReflect.Descriptor instead.
func (*ScoreTrendPoint) Descriptor() ([]byte, []int) {
	return file_drill_v1_sample_proto_rawDescGZIP(), []int{8}
}

func (x *ScoreTrendPoint) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ScoreTrendPoint) GetOverallScore() int32 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

var File_drill_v1_sample_proto protoreflect.FileDescriptor

const file_drill_v1_sample_proto_rawDesc = "" +
	"\n" +
	"\x15drill/v1/sample.proto\x12\bdrill.v1\x1a\x16drill/v1/session.proto\x1a\x19drill/v1/evaluation.proto\x1a\x17drill/v1/educator.proto\x1a\x14drill/v1/coach.proto\"\x19\n" +
	"\x17GetSampleSessionRequest\"v\n" +
	"\x18GetSampleSessionResponse\x12+\n" +
	"\asession\x18\x01 \x01(\v2\x11.drill.v1.SessionR\asession\x12-\n" +
	"\bmessages\x18\x02 \x03(\v2\x11.drill.v1.MessageR\bmessages\"\x1c\n" +
	"\x1aGetSampleEvaluationRequest\"Y\n" +
	"\x1bGetSampleEvaluationResponse\x12:\n" +
	"\n" +
	"evaluation\x18\x01 \x01(\v2\x1a.drill.v1.EvaluationResultR\n" +
	"evaluation\"\x1a\n" +
	"\x18GetSampleEducatorRequest\"S\n" +
	"\x19GetSampleEducatorResponse\x126\n" +
	"\banalysis\x18\x01 \x01(\v2\x1a.drill.v1.EducatorAnalysisR\banalysis\"\x17\n" +
	"\x15GetSampleCoachRequest\"\x89\x01\n" +
	"\x16GetSampleCoachResponse\x123\n" +
	"\banalysis\x18\x01 \x01(\v2\x17.drill.v1.CoachAnalysisR\banalysis\x12:\n" +
	"\vscore_trend\x18\x02 \x03(\v2\x19.drill.v1.ScoreTrendPointR\n" +
	"scoreTrend\"J\n" +
	"\x0fScoreTrendPoint\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12#\n" +
	"\roverall_score\x18\x02 \x01(\x05R\foverallScore2\x81\x03\n" +
	"\rSampleService\x12Y\n" +
	"\x10GetSampleSession\x12!.drill.v1.GetSampleSessionRequest\x1a\".drill.v1.GetSampleSessionResponse\x12b\n" +
	"\x13GetSampleEvaluation\x12$.drill.v1.GetSampleEvaluationRequest\x1a%.drill.v1.GetSampleEvaluationResponse\x12\\\n" +
	"\x11GetSampleEducator\x12\".drill.v1.GetSampleEducatorRequest\x1a#.drill.v1.GetSampleEducatorResponse\x12S\n" +
	"\x0eGetSampleCoach\x12\x1f.drill.v1.GetSampleCoachRequest\x1a .drill.v1.GetSampleCoachResponseB3Z1github.com/btc/drill/internal/pb/drill/v1;drillv1b\x06proto3"

var (
	file_drill_v1_sample_proto_rawDescOnce sync.Once
	file_drill_v1_sample_proto_rawDescData []byte
)

func file_drill_v1_sample_proto_rawDescGZIP() []byte {
	file_drill_v1_sample_proto_rawDescOnce.Do(func() {
		file_drill_v1_sample_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_drill_v1_sample_proto_rawDesc), len(file_drill_v1_sample_proto_rawDesc)))
	})
	return file_drill_v1_sample_proto_rawDescData
}

var file_drill_v1_sample_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_drill_v1_sample_proto_goTypes = []any{
	(*GetSampleSessionRequest)(nil),     // 0: drill.v1.GetSampleSessionRequest
	(*GetSampleSessionResponse)(nil),    // 1: drill.v1.GetSampleSessionResponse
	(*GetSampleEvaluationRequest)(nil),  // 2: drill.v1.GetSampleEvaluationRequest
	(*GetSampleEvaluationResponse)(nil), // 3: drill.v1.GetSampleEvaluationResponse
	(*GetSampleEducatorRequest)(nil),    // 4: drill.v1.GetSampleEducatorRequest
	(*GetSampleEducatorResponse)(nil),   // 5: drill.v1.GetSampleEducatorResponse
	(*GetSampleCoachRequest)(nil),       // 6: drill.v1.GetSampleCoachRequest
	(*GetSampleCoachResponse)(nil),      // 7: drill.v1.GetSampleCoachResponse
	(*ScoreTrendPoint)(nil),             // 8: drill.v1.ScoreTrendPoint
	(*Session)(nil),                     // 9: drill.v1.Session
	(*Message)(nil),                     // 10: drill.v1.Message
	(*EvaluationResult)(nil),            // 11: drill.v1.EvaluationResult
	(*EducatorAnalysis)(nil),            // 12: drill.v1.EducatorAnalysis
	(*CoachAnalysis)(nil),               // 13: drill.v1.CoachAnalysis
}
var file_drill_v1_sample_proto_depIdxs = []int32{
	9,  // 0: drill.v1.GetSampleSessionResponse.session:type_name -> drill.v1.Session
	10, // 1: drill.v1.GetSampleSessionResponse.messages:type_name -> drill.v1.Message
	11, // 2: drill.v1.GetSampleEvaluationResponse.evaluation:type_name -> drill.v1.EvaluationResult
	12, // 3: drill.v1.GetSampleEducatorResponse.analysis:type_name -> drill.v1.EducatorAnalysis
	13, // 4: drill.v1.GetSampleCoachResponse.analysis:type_name -> drill.v1.CoachAnalysis
	8,  // 5: drill.v1.GetSampleCoachResponse.score_trend:type_name -> drill.v1.ScoreTrendPoint
	0,  // 6: drill.v1.SampleService.GetSampleSession:input_type -> drill.v1.GetSampleSessionRequest
	2,  // 7: drill.v1.SampleService.GetSampleEvaluation:input_type -> drill.v1.GetSampleEvaluationRequest
	4,  // 8: drill.v1.SampleService.GetSampleEducator:input_type -> drill.v1.GetSampleEducatorRequest
	6,  // 9: drill.v1.SampleService.GetSampleCoach:input_type -> drill.v1.GetSampleCoachRequest
	1,  // 10: drill.v1.SampleService.GetSampleSession:output_type -> drill.v1.GetSampleSessionResponse
	3,  // 11: drill.v1.SampleService.GetSampleEvaluation:output_type -> drill.v1.GetSampleEvaluationResponse
	5,  // 12: drill.v1.SampleService.GetSampleEducator:output_type -> drill.v1.GetSampleEducatorResponse
	7,  // 13: drill.v1.SampleService.GetSampleCoach:output_type -> drill.v1.GetSampleCoachResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_drill_v1_sample_proto_init() }
func file_drill_v1_sample_proto_init() {
	if File_drill_v1_sample_proto != nil {
		return
	}
	file_drill_v1_session_proto_init()
	file_drill_v1_evaluation_proto_init()
	file_drill_v1_educator_proto_init()
	file_drill_v1_coach_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_drill_v1_sample_proto_rawDesc), len(file_drill_v1_sample_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_drill_v1_sample_proto_goTypes,
		DependencyIndexes: file_drill_v1_sample_proto_depIdxs,
		MessageInfos:      file_drill_v1_sample_proto_msgTypes,
	}.Build()
	File_drill_v1_sample_proto = out.File
	file_drill_v1_sample_proto_goTypes = nil
	file_drill_v1_sample_proto_depIdxs = nil
}
