// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: drill/v1/session.proto

package drillv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_UNSPECIFIED       SessionStatus = 0
	SessionStatus_SESSION_STATUS_ACTIVE            SessionStatus = 1
	SessionStatus_SESSION_STATUS_COMPLETED         SessionStatus = 2
	SessionStatus_SESSION_STATUS_EVALUATING        SessionStatus = 3
	SessionStatus_SESSION_STATUS_REVIEWED          SessionStatus = 4
	SessionStatus_SESSION_STATUS_EVALUATION_FAILED SessionStatus = 5
	SessionStatus_SESSION_STATUS_FAILED            SessionStatus = 6
	SessionStatus_SESSION_STATUS_CANCELLED         SessionStatus = 7
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_UNSPECIFIED",
		1: "SESSION_STATUS_ACTIVE",
		2: "SESSION_STATUS_COMPLETED",
		3: "SESSION_STATUS_EVALUATING",
		4: "SESSION_STATUS_REVIEWED",
		5: "SESSION_STATUS_EVALUATION_FAILED",
		6: "SESSION_STATUS_FAILED",
		7: "SESSION_STATUS_CANCELLED",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_UNSPECIFIED":       0,
		"SESSION_STATUS_ACTIVE":            1,
		"SESSION_STATUS_COMPLETED":         2,
		"SESSION_STATUS_EVALUATING":        3,
		"SESSION_STATUS_REVIEWED":          4,
		"SESSION_STATUS_EVALUATION_FAILED": 5,
		"SESSION_STATUS_FAILED":            6,
		"SESSION_STATUS_CANCELLED":         7,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_drill_v1_session_proto_enumTypes[0].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_drill_v1_session_proto_enumTypes[0]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_drill_v1_session_proto_rawDescGZIP(), []int{0}
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_drill_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_drill_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *GetSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_drill_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_drill_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *GetSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_drill_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_drill_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *ListSessionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSessionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionSummary      `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_drill_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_drill_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *ListSessionsResponse) GetSessions() []*SessionSummary {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateSessionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	QuestionId      string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,2,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	TtsEnabled      bool                   `protobuf:"varint,3,opt,name=tts_enabled,json=ttsEnabled,proto3" json:"tts_enabled,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_drill_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_drill_v1_session_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSessionRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *CreateSessionRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *CreateSessionRequest) GetTtsEnabled() bool {
	if x != nil {
		return x.TtsEnabled
	}
	return false
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_drill_v1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_drill_v1_session_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type ArchiveSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionIds    []string               `protobuf:"bytes,1,rep,name=session_ids,json=sessionIds,proto3" json:"session_ids,omitempty"`
	Archive       bool                   `protobuf:"varint,2,opt,name=archive,proto3" json:"archive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveSessionsRequest) Reset() {
	*x = ArchiveSessionsRequest{}
	mi := &file_drill_v1_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveSessionsRequest) ProtoMessage() {}

func (x *ArchiveSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveSessionsRequest.ProtoReflect.Descriptor instead.
func (*ArchiveSessionsRequest) Descriptor() ([]byte, []int) {
	return file_drill_v1_session_proto_rawDescGZIP(), []int{6}
}

func (x *ArchiveSessionsRequest) GetSessionIds() []string {
	if x != nil {
		return x.SessionIds
	}
	return nil
}

func (x *ArchiveSessionsRequest) GetArchive() bool {
	if x != nil {
		return x.Archive
	}
	return false
}

type ArchiveSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedCount  int32                  `protobuf:"varint,1,opt,name=updated_count,json=updatedCount,proto3" json:"updated_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveSessionsResponse) Reset() {
	*x = ArchiveSessionsResponse{}
	mi := &file_drill_v1_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveSessionsResponse) ProtoMessage() {}

func (x *ArchiveSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveSessionsResponse.ProtoReflect.Descriptor instead.
func (*ArchiveSessionsResponse) Descriptor() ([]byte, []int) {
	return file_drill_v1_session_proto_rawDescGZIP(), []int{7}
}

func (x *ArchiveSessionsResponse) GetUpdatedCount() int32 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

type GetTranscriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTranscriptRequest) Reset() {
	*x = GetTranscriptRequest{}
	mi := &file_drill_v1_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranscriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranscriptRequest) ProtoMessage() {}

func (x *GetTranscriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranscriptRequest.ProtoReflect.Descriptor instead.
func (*GetTranscriptRequest) Descriptor() ([]byte, []int) {
	return file_drill_v1_session_proto_rawDescGZIP(), []int{8}
}

func (x *GetTranscriptRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetTranscriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTranscriptResponse) Reset() {
	*x = GetTranscriptResponse{}
	mi := &file_drill_v1_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranscriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranscriptResponse) ProtoMessage() {}

func (x *GetTranscriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranscriptResponse.ProtoReflect.Descriptor instead.
func (*GetTranscriptResponse) Descriptor() ([]byte, []int) {
	return file_drill_v1_session_proto_rawDescGZIP(), []int{9}
}

func (x *GetTranscriptResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

// Full session detail (returned by Get/Create).
type Session struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId                string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuestionId            string                 `protobuf:"bytes,3,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Status                SessionStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=drill.v1.SessionStatus" json:"status,omitempty"`
	ConfigDurationMinutes int32                  `protobuf:"varint,5,opt,name=config_duration_minutes,json=configDurationMinutes,proto3" json:"config_duration_minutes,omitempty"`
	ConfigTtsEnabled      bool                   `protobuf:"varint,6,opt,name=config_tts_enabled,json=configTtsEnabled,proto3" json:"config_tts_enabled,omitempty"`
	ConfigCoachBriefing   bool                   `protobuf:"varint,7,opt,name=config_coach_briefing,json=configCoachBriefing,proto3" json:"config_coach_briefing,omitempty"`
	StartTime             *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime               *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`
	TurnCount             int32                  `protobuf:"varint,10,opt,name=turn_count,json=turnCount,proto3" json:"turn_count,omitempty"`
	ArchiveTime           *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=archive_time,json=archiveTime,proto3,oneof" json:"archive_time,omitempty"`
	CreateTime            *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime            *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	QuestionTitle         string                 `protobuf:"bytes,14,opt,name=question_title,json=questionTitle,proto3" json:"question_title,omitempty"`
	QuestionPrompt        string                 `protobuf:"bytes,15,opt,name=question_prompt,json=questionPrompt,proto3" json:"question_prompt,omitempty"`
	QuestionDifficulty    string                 `protobuf:"bytes,16,opt,name=question_difficulty,json=questionDifficulty,proto3" json:"question_difficulty,omitempty"`
	QuestionHints         *string                `protobuf:"bytes,17,opt,name=question_hints,json=questionHints,proto3,oneof" json:"question_hints,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_drill_v1_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_drill_v1_session_proto_rawDescGZIP(), []int{10}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Session) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *Session) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *Session) GetConfigDurationMinutes() int32 {
	if x != nil {
		return x.ConfigDurationMinutes
	}
	return 0
}

func (x *Session) GetConfigTtsEnabled() bool {
	if x != nil {
		return x.ConfigTtsEnabled
	}
	return false
}

func (x *Session) GetConfigCoachBriefing() bool {
	if x != nil {
		return x.ConfigCoachBriefing
	}
	return false
}

func (x *Session) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Session) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Session) GetTurnCount() int32 {
	if x != nil {
		return x.TurnCount
	}
	return 0
}

func (x *Session) GetArchiveTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ArchiveTime
	}
	return nil
}

func (x *Session) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Session) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Session) GetQuestionTitle() string {
	if x != nil {
		return x.QuestionTitle
	}
	return ""
}

func (x *Session) GetQuestionPrompt() string {
	if x != nil {
		return x.QuestionPrompt
	}
	return ""
}

func (x *Session) GetQuestionDifficulty() string {
	if x != nil {
		return x.QuestionDifficulty
	}
	return ""
}

func (x *Session) GetQuestionHints() string {
	if x != nil && x.QuestionHints != nil {
		return *x.QuestionHints
	}
	return ""
}

// Summary for list view (lighter than full Session).
type SessionSummary struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId                string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuestionId            string                 `protobuf:"bytes,3,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Status                SessionStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=drill.v1.SessionStatus" json:"status,omitempty"`
	ConfigDurationMinutes int32                  `protobuf:"varint,5,opt,name=config_duration_minutes,json=configDurationMinutes,proto3" json:"config_duration_minutes,omitempty"`
	ConfigTtsEnabled      bool                   `protobuf:"varint,6,opt,name=config_tts_enabled,json=configTtsEnabled,proto3" json:"config_tts_enabled,omitempty"`
	StartTime             *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime               *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`
	TurnCount             int32                  `protobuf:"varint,9,opt,name=turn_count,json=turnCount,proto3" json:"turn_count,omitempty"`
	ArchiveTime           *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=archive_time,json=archiveTime,proto3,oneof" json:"archive_time,omitempty"`
	CreateTime            *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	QuestionTitle         string                 `protobuf:"bytes,12,opt,name=question_title,json=questionTitle,proto3" json:"question_title,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SessionSummary) Reset() {
	*x = SessionSummary{}
	mi := &file_drill_v1_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSummary) ProtoMessage() {}

func (x *SessionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSummary.ProtoReflect.Descriptor instead.
func (*SessionSummary) Descriptor() ([]byte, []int) {
	return file_drill_v1_session_proto_rawDescGZIP(), []int{11}
}

func (x *SessionSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionSummary) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionSummary) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *SessionSummary) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *SessionSummary) GetConfigDurationMinutes() int32 {
	if x != nil {
		return x.ConfigDurationMinutes
	}
	return 0
}

func (x *SessionSummary) GetConfigTtsEnabled() bool {
	if x != nil {
		return x.ConfigTtsEnabled
	}
	return false
}

func (x *SessionSummary) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *SessionSummary) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *SessionSummary) GetTurnCount() int32 {
	if x != nil {
		return x.TurnCount
	}
	return 0
}

func (x *SessionSummary) GetArchiveTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ArchiveTime
	}
	return nil
}

func (x *SessionSummary) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *SessionSummary) GetQuestionTitle() string {
	if x != nil {
		return x.QuestionTitle
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Seq           int32                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	InputMethod   *string                `protobuf:"bytes,6,opt,name=input_method,json=inputMethod,proto3,oneof" json:"input_method,omitempty"`
	AudioUrl      *string                `protobuf:"bytes,7,opt,name=audio_url,json=audioUrl,proto3,oneof" json:"audio_url,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_drill_v1_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_drill_v1_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_drill_v1_session_proto_rawDescGZIP(), []int{12}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Message) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetInputMethod() string {
	if x != nil && x.InputMethod != nil {
		return *x.InputMethod
	}
	return ""
}

func (x *Message) GetAudioUrl() string {
	if x != nil && x.AudioUrl != nil {
		return *x.AudioUrl
	}
	return ""
}

func (x *Message) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

var File_drill_v1_session_proto protoreflect.FileDescriptor

const file_drill_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x16drill/v1/session.proto\x12\bdrill.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"#\n" +
	"\x11GetSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"A\n" +
	"\x12GetSessionResponse\x12+\n" +
	"\asession\x18\x01 \x01(\v2\x11.drill.v1.SessionR\asession\"Q\n" +
	"\x13ListSessionsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"t\n" +
	"\x14ListSessionsResponse\x124\n" +
	"\bsessions\x18\x01 \x03(\v2\x18.drill.v1.SessionSummaryR\bsessions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x83\x01\n" +
	"\x14CreateSessionRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12)\n" +
	"\x10duration_minutes\x18\x02 \x01(\x05R\x0fdurationMinutes\x12\x1f\n" +
	"\vtts_enabled\x18\x03 \x01(\bR\n" +
	"ttsEnabled\"D\n" +
	"\x15CreateSessionResponse\x12+\n" +
	"\asession\x18\x01 \x01(\v2\x11.drill.v1.SessionR\asession\"S\n" +
	"\x16ArchiveSessionsRequest\x12\x1f\n" +
	"\vsession_ids\x18\x01 \x03(\tR\n" +
	"sessionIds\x12\x18\n" +
	"\aarchive\x18\x02 \x01(\bR\aarchive\">\n" +
	"\x17ArchiveSessionsResponse\x12#\n" +
	"\rupdated_count\x18\x01 \x01(\x05R\fupdatedCount\"5\n" +
	"\x14GetTranscriptRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"F\n" +
	"\x15GetTranscriptResponse\x12-\n" +
	"\bmessages\x18\x01 \x03(\v2\x11.drill.v1.MessageR\bmessages\"\xd0\x06\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vquestion_id\x18\x03 \x01(\tR\n" +
	"questionId\x12/\n" +
	"\x06status\x18\x04 \x01(\x0e2\x17.drill.v1.SessionStatusR\x06status\x126\n" +
	"\x17config_duration_minutes\x18\x05 \x01(\x05R\x15configDurationMinutes\x12,\n" +
	"\x12config_tts_enabled\x18\x06 \x01(\bR\x10configTtsEnabled\x122\n" +
	"\x15config_coach_briefing\x18\a \x01(\bR\x13configCoachBriefing\x129\n" +
	"\n" +
	"start_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12:\n" +
	"\bend_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x00R\aendTime\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"turn_count\x18\n" +
	" \x01(\x05R\tturnCount\x12B\n" +
	"\farchive_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampH\x01R\varchiveTime\x88\x01\x01\x12;\n" +
	"\vcreate_time\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12%\n" +
	"\x0equestion_title\x18\x0e \x01(\tR\rquestionTitle\x12'\n" +
	"\x0fquestion_prompt\x18\x0f \x01(\tR\x0equestionPrompt\x12/\n" +
	"\x13question_difficulty\x18\x10 \x01(\tR\x12questionDifficulty\x12*\n" +
	"\x0equestion_hints\x18\x11 \x01(\tH\x02R\rquestionHints\x88\x01\x01B\v\n" +
	"\t_end_timeB\x0f\n" +
	"\r_archive_timeB\x11\n" +
	"\x0f_question_hints\"\xcd\x04\n" +
	"\x0eSessionSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vquestion_id\x18\x03 \x01(\tR\n" +
	"questionId\x12/\n" +
	"\x06status\x18\x04 \x01(\x0e2\x17.drill.v1.SessionStatusR\x06status\x126\n" +
	"\x17config_duration_minutes\x18\x05 \x01(\x05R\x15configDurationMinutes\x12,\n" +
	"\x12config_tts_enabled\x18\x06 \x01(\bR\x10configTtsEnabled\x129\n" +
	"\n" +
	"start_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12:\n" +
	"\bend_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x00R\aendTime\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"turn_count\x18\t \x01(\x05R\tturnCount\x12B\n" +
	"\farchive_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\x01R\varchiveTime\x88\x01\x01\x12;\n" +
	"\vcreate_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12%\n" +
	"\x0equestion_title\x18\f \x01(\tR\rquestionTitleB\v\n" +
	"\t_end_timeB\x0f\n" +
	"\r_archive_time\"\x9e\x02\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x05R\x03seq\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12&\n" +
	"\finput_method\x18\x06 \x01(\tH\x00R\vinputMethod\x88\x01\x01\x12 \n" +
	"\taudio_url\x18\a \x01(\tH\x01R\baudioUrl\x88\x01\x01\x12;\n" +
	"\vcreate_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTimeB\x0f\n" +
	"\r_input_methodB\f\n" +
	"\n" +
	"_audio_url*\x83\x02\n" +
	"\rSessionStatus\x12\x1e\n" +
	"\x1aSESSION_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SESSION_STATUS_ACTIVE\x10\x01\x12\x1c\n" +
	"\x18SESSION_STATUS_COMPLETED\x10\x02\x12\x1d\n" +
	"\x19SESSION_STATUS_EVALUATING\x10\x03\x12\x1b\n" +
	"\x17SESSION_STATUS_REVIEWED\x10\x04\x12$\n" +
	" SESSION_STATUS_EVALUATION_FAILED\x10\x05\x12\x19\n" +
	"\x15SESSION_STATUS_FAILED\x10\x06\x12\x1c\n" +
	"\x18SESSION_STATUS_CANCELLED\x10\a2\xa4\x03\n" +
	"\x0eSessionService\x12G\n" +
	"\n" +
	"GetSession\x12\x1b.drill.v1.GetSessionRequest\x1a\x1c.drill.v1.GetSessionResponse\x12M\n" +
	"\fListSessions\x12\x1d.drill.v1.ListSessionsRequest\x1a\x1e.drill.v1.ListSessionsResponse\x12P\n" +
	"\rCreateSession\x12\x1e.drill.v1.CreateSessionRequest\x1a\x1f.drill.v1.CreateSessionResponse\x12V\n" +
	"\x0fArchiveSessions\x12 .drill.v1.ArchiveSessionsRequest\x1a!.drill.v1.ArchiveSessionsResponse\x12P\n" +
	"\rGetTranscript\x12\x1e.drill.v1.GetTranscriptRequest\x1a\x1f.drill.v1.GetTranscriptResponseB3Z1github.com/btc/drill/internal/pb/drill/v1;drillv1b\x06proto3"

var (
	file_drill_v1_session_proto_rawDescOnce sync.Once
	file_drill_v1_session_proto_rawDescData []byte
)

func file_drill_v1_session_proto_rawDescGZIP() []byte {
	file_drill_v1_session_proto_rawDescOnce.Do(func() {
		file_drill_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_drill_v1_session_proto_rawDesc), len(file_drill_v1_session_proto_rawDesc)))
	})
	return file_drill_v1_session_proto_rawDescData
}

var file_drill_v1_session_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_drill_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_drill_v1_session_proto_goTypes = []any{
	(SessionStatus)(0),              // 0: drill.v1.SessionStatus
	(*GetSessionRequest)(nil),       // 1: drill.v1.GetSessionRequest
	(*GetSessionResponse)(nil),      // 2: drill.v1.GetSessionResponse
	(*ListSessionsRequest)(nil),     // 3: drill.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),    // 4: drill.v1.ListSessionsResponse
	(*CreateSessionRequest)(nil),    // 5: drill.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil),   // 6: drill.v1.CreateSessionResponse
	(*ArchiveSessionsRequest)(nil),  // 7: drill.v1.ArchiveSessionsRequest
	(*ArchiveSessionsResponse)(nil), // 8: drill.v1.ArchiveSessionsResponse
	(*GetTranscriptRequest)(nil),    // 9: drill.v1.GetTranscriptRequest
	(*GetTranscriptResponse)(nil),   // 10: drill.v1.GetTranscriptResponse
	(*Session)(nil),                 // 11: drill.v1.Session
	(*SessionSummary)(nil),          // 12: drill.v1.SessionSummary
	(*Message)(nil),                 // 13: drill.v1.Message
	(*timestamppb.Timestamp)(nil),   // 14: google.protobuf.Timestamp
}
var file_drill_v1_session_proto_depIdxs = []int32{
	11, // 0: drill.v1.GetSessionResponse.session:type_name -> drill.v1.Session
	12, // 1: drill.v1.ListSessionsResponse.sessions:type_name -> drill.v1.SessionSummary
	11, // 2: drill.v1.CreateSessionResponse.session:type_name -> drill.v1.Session
	13, // 3: drill.v1.GetTranscriptResponse.messages:type_name -> drill.v1.Message
	0,  // 4: drill.v1.Session.status:type_name -> drill.v1.SessionStatus
	14, // 5: drill.v1.Session.start_time:type_name -> google.protobuf.Timestamp
	14, // 6: drill.v1.Session.end_time:type_name -> google.protobuf.Timestamp
	14, // 7: drill.v1.Session.archive_time:type_name -> google.protobuf.Timestamp
	14, // 8: drill.v1.Session.create_time:type_name -> google.protobuf.Timestamp
	14, // 9: drill.v1.Session.update_time:type_name -> google.protobuf.Timestamp
	0,  // 10: drill.v1.SessionSummary.status:type_name -> drill.v1.SessionStatus
	14, // 11: drill.v1.SessionSummary.start_time:type_name -> google.protobuf.Timestamp
	14, // 12: drill.v1.SessionSummary.end_time:type_name -> google.protobuf.Timestamp
	14, // 13: drill.v1.SessionSummary.archive_time:type_name -> google.protobuf.Timestamp
	14, // 14: drill.v1.SessionSummary.create_time:type_name -> google.protobuf.Timestamp
	14, // 15: drill.v1.Message.create_time:type_name -> google.protobuf.Timestamp
	1,  // 16: drill.v1.SessionService.GetSession:input_type -> drill.v1.GetSessionRequest
	3,  // 17: drill.v1.SessionService.ListSessions:input_type -> drill.v1.ListSessionsRequest
	5,  // 18: drill.v1.SessionService.CreateSession:input_type -> drill.v1.CreateSessionRequest
	7,  // 19: drill.v1.SessionService.ArchiveSessions:input_type -> drill.v1.ArchiveSessionsRequest
	9,  // 20: drill.v1.SessionService.GetTranscript:input_type -> drill.v1.GetTranscriptRequest
	2,  // 21: drill.v1.SessionService.GetSession:output_type -> drill.v1.GetSessionResponse
	4,  // 22: drill.v1.SessionService.ListSessions:output_type -> drill.v1.ListSessionsResponse
	6,  // 23: drill.v1.SessionService.CreateSession:output_type -> drill.v1.CreateSessionResponse
	8,  // 24: drill.v1.SessionService.ArchiveSessions:output_type -> drill.v1.ArchiveSessionsResponse
	10, // 25: drill.v1.SessionService.GetTranscript:output_type -> drill.v1.GetTranscriptResponse
	21, // [21:26] is the sub-list for method output_type
	16, // [16:21] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_drill_v1_session_proto_init() }
func file_drill_v1_session_proto_init() {
	if File_drill_v1_session_proto != nil {
		return
	}
	file_drill_v1_session_proto_msgTypes[10].OneofWrappers = []any{}
	file_drill_v1_session_proto_msgTypes[11].OneofWrappers = []any{}
	file_drill_v1_session_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_drill_v1_session_proto_rawDesc), len(file_drill_v1_session_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_drill_v1_session_proto_goTypes,
		DependencyIndexes: file_drill_v1_session_proto_depIdxs,
		EnumInfos:         file_drill_v1_session_proto_enumTypes,
		MessageInfos:      file_drill_v1_session_proto_msgTypes,
	}.Build()
	File_drill_v1_session_proto = out.File
	file_drill_v1_session_proto_goTypes = nil
	file_drill_v1_session_proto_depIdxs = nil
}
