pre-commit:
  parallel: true
  commands:
    frontend-lint:
      root: "web/"
      glob: "web/src/**/*.{ts,tsx}"
      exclude: "web/src/pb/**"
      run: npx eslint --fix {staged_files} && git add {staged_files}
    frontend-typecheck:
      root: "web/"
      glob: "web/src/**/*.{ts,tsx}"
      run: npx tsc --noEmit -p tsconfig.app.json
    backend-vet:
      glob: "**/*.go"
      run: go vet ./...
