// @generated by protoc-gen-es v2.11.0
// @generated from file drill/v1/auth.proto (package drill.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file drill/v1/auth.proto.
 */
export declare const file_drill_v1_auth: GenFile;

/**
 * @generated from message drill.v1.SignupRequest
 */
export declare type SignupRequest = Message<"drill.v1.SignupRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;

  /**
   * @generated from field: string display_name = 3;
   */
  displayName: string;
};

/**
 * Describes the message drill.v1.SignupRequest.
 * Use `create(SignupRequestSchema)` to create a new message.
 */
export declare const SignupRequestSchema: GenMessage<SignupRequest>;

/**
 * @generated from message drill.v1.SignupResponse
 */
export declare type SignupResponse = Message<"drill.v1.SignupResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;
};

/**
 * Describes the message drill.v1.SignupResponse.
 * Use `create(SignupResponseSchema)` to create a new message.
 */
export declare const SignupResponseSchema: GenMessage<SignupResponse>;

/**
 * @generated from message drill.v1.LoginRequest
 */
export declare type LoginRequest = Message<"drill.v1.LoginRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message drill.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export declare const LoginRequestSchema: GenMessage<LoginRequest>;

/**
 * @generated from message drill.v1.LoginResponse
 */
export declare type LoginResponse = Message<"drill.v1.LoginResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;
};

/**
 * Describes the message drill.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export declare const LoginResponseSchema: GenMessage<LoginResponse>;

/**
 * @generated from message drill.v1.LogoutRequest
 */
export declare type LogoutRequest = Message<"drill.v1.LogoutRequest"> & {
};

/**
 * Describes the message drill.v1.LogoutRequest.
 * Use `create(LogoutRequestSchema)` to create a new message.
 */
export declare const LogoutRequestSchema: GenMessage<LogoutRequest>;

/**
 * @generated from message drill.v1.LogoutResponse
 */
export declare type LogoutResponse = Message<"drill.v1.LogoutResponse"> & {
};

/**
 * Describes the message drill.v1.LogoutResponse.
 * Use `create(LogoutResponseSchema)` to create a new message.
 */
export declare const LogoutResponseSchema: GenMessage<LogoutResponse>;

/**
 * @generated from message drill.v1.VerifyEmailRequest
 */
export declare type VerifyEmailRequest = Message<"drill.v1.VerifyEmailRequest"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message drill.v1.VerifyEmailRequest.
 * Use `create(VerifyEmailRequestSchema)` to create a new message.
 */
export declare const VerifyEmailRequestSchema: GenMessage<VerifyEmailRequest>;

/**
 * @generated from message drill.v1.VerifyEmailResponse
 */
export declare type VerifyEmailResponse = Message<"drill.v1.VerifyEmailResponse"> & {
};

/**
 * Describes the message drill.v1.VerifyEmailResponse.
 * Use `create(VerifyEmailResponseSchema)` to create a new message.
 */
export declare const VerifyEmailResponseSchema: GenMessage<VerifyEmailResponse>;

/**
 * @generated from message drill.v1.ForgotPasswordRequest
 */
export declare type ForgotPasswordRequest = Message<"drill.v1.ForgotPasswordRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;
};

/**
 * Describes the message drill.v1.ForgotPasswordRequest.
 * Use `create(ForgotPasswordRequestSchema)` to create a new message.
 */
export declare const ForgotPasswordRequestSchema: GenMessage<ForgotPasswordRequest>;

/**
 * @generated from message drill.v1.ForgotPasswordResponse
 */
export declare type ForgotPasswordResponse = Message<"drill.v1.ForgotPasswordResponse"> & {
};

/**
 * Describes the message drill.v1.ForgotPasswordResponse.
 * Use `create(ForgotPasswordResponseSchema)` to create a new message.
 */
export declare const ForgotPasswordResponseSchema: GenMessage<ForgotPasswordResponse>;

/**
 * @generated from message drill.v1.ResetPasswordRequest
 */
export declare type ResetPasswordRequest = Message<"drill.v1.ResetPasswordRequest"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message drill.v1.ResetPasswordRequest.
 * Use `create(ResetPasswordRequestSchema)` to create a new message.
 */
export declare const ResetPasswordRequestSchema: GenMessage<ResetPasswordRequest>;

/**
 * @generated from message drill.v1.ResetPasswordResponse
 */
export declare type ResetPasswordResponse = Message<"drill.v1.ResetPasswordResponse"> & {
};

/**
 * Describes the message drill.v1.ResetPasswordResponse.
 * Use `create(ResetPasswordResponseSchema)` to create a new message.
 */
export declare const ResetPasswordResponseSchema: GenMessage<ResetPasswordResponse>;

/**
 * @generated from message drill.v1.DeleteAccountRequest
 */
export declare type DeleteAccountRequest = Message<"drill.v1.DeleteAccountRequest"> & {
};

/**
 * Describes the message drill.v1.DeleteAccountRequest.
 * Use `create(DeleteAccountRequestSchema)` to create a new message.
 */
export declare const DeleteAccountRequestSchema: GenMessage<DeleteAccountRequest>;

/**
 * @generated from message drill.v1.DeleteAccountResponse
 */
export declare type DeleteAccountResponse = Message<"drill.v1.DeleteAccountResponse"> & {
};

/**
 * Describes the message drill.v1.DeleteAccountResponse.
 * Use `create(DeleteAccountResponseSchema)` to create a new message.
 */
export declare const DeleteAccountResponseSchema: GenMessage<DeleteAccountResponse>;

/**
 * AuthService provides public authentication endpoints.
 * All methods except DeleteAccount are unauthenticated.
 *
 * @generated from service drill.v1.AuthService
 */
export declare const AuthService: GenService<{
  /**
   * @generated from rpc drill.v1.AuthService.Signup
   */
  signup: {
    methodKind: "unary";
    input: typeof SignupRequestSchema;
    output: typeof SignupResponseSchema;
  },
  /**
   * @generated from rpc drill.v1.AuthService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
  /**
   * @generated from rpc drill.v1.AuthService.Logout
   */
  logout: {
    methodKind: "unary";
    input: typeof LogoutRequestSchema;
    output: typeof LogoutResponseSchema;
  },
  /**
   * @generated from rpc drill.v1.AuthService.VerifyEmail
   */
  verifyEmail: {
    methodKind: "unary";
    input: typeof VerifyEmailRequestSchema;
    output: typeof VerifyEmailResponseSchema;
  },
  /**
   * @generated from rpc drill.v1.AuthService.ForgotPassword
   */
  forgotPassword: {
    methodKind: "unary";
    input: typeof ForgotPasswordRequestSchema;
    output: typeof ForgotPasswordResponseSchema;
  },
  /**
   * @generated from rpc drill.v1.AuthService.ResetPassword
   */
  resetPassword: {
    methodKind: "unary";
    input: typeof ResetPasswordRequestSchema;
    output: typeof ResetPasswordResponseSchema;
  },
  /**
   * @generated from rpc drill.v1.AuthService.DeleteAccount
   */
  deleteAccount: {
    methodKind: "unary";
    input: typeof DeleteAccountRequestSchema;
    output: typeof DeleteAccountResponseSchema;
  },
}>;

