// @generated by protoc-gen-connect-query v2.2.0
// @generated from file drill/v1/auth.proto (package drill.v1, syntax proto3)
/* eslint-disable */

import { AuthService } from "./auth_pb";

/**
 * @generated from rpc drill.v1.AuthService.Signup
 */
export const signup: typeof AuthService["method"]["signup"];
/**
 * @generated from rpc drill.v1.AuthService.Login
 */
export const login: typeof AuthService["method"]["login"];
/**
 * @generated from rpc drill.v1.AuthService.Logout
 */
export const logout: typeof AuthService["method"]["logout"];
/**
 * @generated from rpc drill.v1.AuthService.VerifyEmail
 */
export const verifyEmail: typeof AuthService["method"]["verifyEmail"];
/**
 * @generated from rpc drill.v1.AuthService.ForgotPassword
 */
export const forgotPassword: typeof AuthService["method"]["forgotPassword"];
/**
 * @generated from rpc drill.v1.AuthService.ResetPassword
 */
export const resetPassword: typeof AuthService["method"]["resetPassword"];
/**
 * @generated from rpc drill.v1.AuthService.DeleteAccount
 */
export const deleteAccount: typeof AuthService["method"]["deleteAccount"];
