// @generated by protoc-gen-es v2.11.0
// @generated from file drill/v1/auth.proto (package drill.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file drill/v1/auth.proto.
 */
export const file_drill_v1_auth = /*@__PURE__*/
  fileDesc("ChNkcmlsbC92MS9hdXRoLnByb3RvEghkcmlsbC52MSJGCg1TaWdudXBSZXF1ZXN0Eg0KBWVtYWlsGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJEhQKDGRpc3BsYXlfbmFtZRgDIAEoCSIrCg5TaWdudXBSZXNwb25zZRIKCgJpZBgBIAEoCRINCgVlbWFpbBgCIAEoCSIvCgxMb2dpblJlcXVlc3QSDQoFZW1haWwYASABKAkSEAoIcGFzc3dvcmQYAiABKAkiKgoNTG9naW5SZXNwb25zZRIKCgJpZBgBIAEoCRINCgVlbWFpbBgCIAEoCSIPCg1Mb2dvdXRSZXF1ZXN0IhAKDkxvZ291dFJlc3BvbnNlIiMKElZlcmlmeUVtYWlsUmVxdWVzdBINCgV0b2tlbhgBIAEoCSIVChNWZXJpZnlFbWFpbFJlc3BvbnNlIiYKFUZvcmdvdFBhc3N3b3JkUmVxdWVzdBINCgVlbWFpbBgBIAEoCSIYChZGb3Jnb3RQYXNzd29yZFJlc3BvbnNlIjcKFFJlc2V0UGFzc3dvcmRSZXF1ZXN0Eg0KBXRva2VuGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJIhcKFVJlc2V0UGFzc3dvcmRSZXNwb25zZSIWChREZWxldGVBY2NvdW50UmVxdWVzdCIXChVEZWxldGVBY2NvdW50UmVzcG9uc2UyhgQKC0F1dGhTZXJ2aWNlEjsKBlNpZ251cBIXLmRyaWxsLnYxLlNpZ251cFJlcXVlc3QaGC5kcmlsbC52MS5TaWdudXBSZXNwb25zZRI4CgVMb2dpbhIWLmRyaWxsLnYxLkxvZ2luUmVxdWVzdBoXLmRyaWxsLnYxLkxvZ2luUmVzcG9uc2USOwoGTG9nb3V0EhcuZHJpbGwudjEuTG9nb3V0UmVxdWVzdBoYLmRyaWxsLnYxLkxvZ291dFJlc3BvbnNlEkoKC1ZlcmlmeUVtYWlsEhwuZHJpbGwudjEuVmVyaWZ5RW1haWxSZXF1ZXN0Gh0uZHJpbGwudjEuVmVyaWZ5RW1haWxSZXNwb25zZRJTCg5Gb3Jnb3RQYXNzd29yZBIfLmRyaWxsLnYxLkZvcmdvdFBhc3N3b3JkUmVxdWVzdBogLmRyaWxsLnYxLkZvcmdvdFBhc3N3b3JkUmVzcG9uc2USUAoNUmVzZXRQYXNzd29yZBIeLmRyaWxsLnYxLlJlc2V0UGFzc3dvcmRSZXF1ZXN0Gh8uZHJpbGwudjEuUmVzZXRQYXNzd29yZFJlc3BvbnNlElAKDURlbGV0ZUFjY291bnQSHi5kcmlsbC52MS5EZWxldGVBY2NvdW50UmVxdWVzdBofLmRyaWxsLnYxLkRlbGV0ZUFjY291bnRSZXNwb25zZUIzWjFnaXRodWIuY29tL2J0Yy9kcmlsbC9pbnRlcm5hbC9wYi9kcmlsbC92MTtkcmlsbHYxYgZwcm90bzM");

/**
 * Describes the message drill.v1.SignupRequest.
 * Use `create(SignupRequestSchema)` to create a new message.
 */
export const SignupRequestSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_auth, 0);

/**
 * Describes the message drill.v1.SignupResponse.
 * Use `create(SignupResponseSchema)` to create a new message.
 */
export const SignupResponseSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_auth, 1);

/**
 * Describes the message drill.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_auth, 2);

/**
 * Describes the message drill.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_auth, 3);

/**
 * Describes the message drill.v1.LogoutRequest.
 * Use `create(LogoutRequestSchema)` to create a new message.
 */
export const LogoutRequestSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_auth, 4);

/**
 * Describes the message drill.v1.LogoutResponse.
 * Use `create(LogoutResponseSchema)` to create a new message.
 */
export const LogoutResponseSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_auth, 5);

/**
 * Describes the message drill.v1.VerifyEmailRequest.
 * Use `create(VerifyEmailRequestSchema)` to create a new message.
 */
export const VerifyEmailRequestSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_auth, 6);

/**
 * Describes the message drill.v1.VerifyEmailResponse.
 * Use `create(VerifyEmailResponseSchema)` to create a new message.
 */
export const VerifyEmailResponseSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_auth, 7);

/**
 * Describes the message drill.v1.ForgotPasswordRequest.
 * Use `create(ForgotPasswordRequestSchema)` to create a new message.
 */
export const ForgotPasswordRequestSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_auth, 8);

/**
 * Describes the message drill.v1.ForgotPasswordResponse.
 * Use `create(ForgotPasswordResponseSchema)` to create a new message.
 */
export const ForgotPasswordResponseSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_auth, 9);

/**
 * Describes the message drill.v1.ResetPasswordRequest.
 * Use `create(ResetPasswordRequestSchema)` to create a new message.
 */
export const ResetPasswordRequestSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_auth, 10);

/**
 * Describes the message drill.v1.ResetPasswordResponse.
 * Use `create(ResetPasswordResponseSchema)` to create a new message.
 */
export const ResetPasswordResponseSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_auth, 11);

/**
 * Describes the message drill.v1.DeleteAccountRequest.
 * Use `create(DeleteAccountRequestSchema)` to create a new message.
 */
export const DeleteAccountRequestSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_auth, 12);

/**
 * Describes the message drill.v1.DeleteAccountResponse.
 * Use `create(DeleteAccountResponseSchema)` to create a new message.
 */
export const DeleteAccountResponseSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_auth, 13);

/**
 * AuthService provides public authentication endpoints.
 * All methods except DeleteAccount are unauthenticated.
 *
 * @generated from service drill.v1.AuthService
 */
export const AuthService = /*@__PURE__*/
  serviceDesc(file_drill_v1_auth, 0);

