// @generated by protoc-gen-connect-query v2.2.0
// @generated from file drill/v1/billing.proto (package drill.v1, syntax proto3)
/* eslint-disable */

import { BillingService } from "./billing_pb";

/**
 * @generated from rpc drill.v1.BillingService.Checkout
 */
export const checkout: typeof BillingService["method"]["checkout"];
/**
 * @generated from rpc drill.v1.BillingService.Portal
 */
export const portal: typeof BillingService["method"]["portal"];
