// @generated by protoc-gen-es v2.11.0
// @generated from file drill/v1/billing.proto (package drill.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file drill/v1/billing.proto.
 */
export const file_drill_v1_billing = /*@__PURE__*/
  fileDesc("ChZkcmlsbC92MS9iaWxsaW5nLnByb3RvEghkcmlsbC52MSI+Cg9DaGVja291dFJlcXVlc3QSDAoEdHlwZRgBIAEoCRIMCgRwbGFuGAIgASgJEg8KB21pbnV0ZXMYAyABKAUiHwoQQ2hlY2tvdXRSZXNwb25zZRILCgN1cmwYASABKAkiDwoNUG9ydGFsUmVxdWVzdCIdCg5Qb3J0YWxSZXNwb25zZRILCgN1cmwYASABKAkykAEKDkJpbGxpbmdTZXJ2aWNlEkEKCENoZWNrb3V0EhkuZHJpbGwudjEuQ2hlY2tvdXRSZXF1ZXN0GhouZHJpbGwudjEuQ2hlY2tvdXRSZXNwb25zZRI7CgZQb3J0YWwSFy5kcmlsbC52MS5Qb3J0YWxSZXF1ZXN0GhguZHJpbGwudjEuUG9ydGFsUmVzcG9uc2VCM1oxZ2l0aHViLmNvbS9idGMvZHJpbGwvaW50ZXJuYWwvcGIvZHJpbGwvdjE7ZHJpbGx2MWIGcHJvdG8z");

/**
 * Describes the message drill.v1.CheckoutRequest.
 * Use `create(CheckoutRequestSchema)` to create a new message.
 */
export const CheckoutRequestSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_billing, 0);

/**
 * Describes the message drill.v1.CheckoutResponse.
 * Use `create(CheckoutResponseSchema)` to create a new message.
 */
export const CheckoutResponseSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_billing, 1);

/**
 * Describes the message drill.v1.PortalRequest.
 * Use `create(PortalRequestSchema)` to create a new message.
 */
export const PortalRequestSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_billing, 2);

/**
 * Describes the message drill.v1.PortalResponse.
 * Use `create(PortalResponseSchema)` to create a new message.
 */
export const PortalResponseSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_billing, 3);

/**
 * BillingService provides Stripe checkout and billing portal RPCs.
 *
 * @generated from service drill.v1.BillingService
 */
export const BillingService = /*@__PURE__*/
  serviceDesc(file_drill_v1_billing, 0);

