// @generated by protoc-gen-es v2.11.0
// @generated from file drill/v1/coach.proto (package drill.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file drill/v1/coach.proto.
 */
export const file_drill_v1_coach = /*@__PURE__*/
  fileDesc("ChRkcmlsbC92MS9jb2FjaC5wcm90bxIIZHJpbGwudjEisQIKDUNvYWNoQW5hbHlzaXMSCgoCaWQYASABKAkSDwoHdXNlcl9pZBgCIAEoCRIRCgluYXJyYXRpdmUYAyABKAkSHgoRd2Vha2VzdF9kaW1lbnNpb24YBCABKAlIAIgBARIcChRpbXByb3ZpbmdfZGltZW5zaW9ucxgFIAMoCRISCgp0b3BpY19nYXBzGAYgAygJEiIKFXN1Z2dlc3RlZF9xdWVzdGlvbl9pZBgHIAEoCUgBiAEBEhkKEXNlc3Npb25zX2FuYWx5emVkGAggAygJEi8KC2NyZWF0ZV90aW1lGAkgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEIUChJfd2Vha2VzdF9kaW1lbnNpb25CGAoWX3N1Z2dlc3RlZF9xdWVzdGlvbl9pZCIZChdHZXRDb2FjaEFuYWx5c2lzUmVxdWVzdCJXChhHZXRDb2FjaEFuYWx5c2lzUmVzcG9uc2USLgoIYW5hbHlzaXMYASABKAsyFy5kcmlsbC52MS5Db2FjaEFuYWx5c2lzSACIAQFCCwoJX2FuYWx5c2lzIiwKG1JlcXVlc3RDb2FjaEFuYWx5c2lzUmVxdWVzdBINCgVmb3JjZRgBIAEoCCIeChxSZXF1ZXN0Q29hY2hBbmFseXNpc1Jlc3BvbnNlMtABCgxDb2FjaFNlcnZpY2USWQoQR2V0Q29hY2hBbmFseXNpcxIhLmRyaWxsLnYxLkdldENvYWNoQW5hbHlzaXNSZXF1ZXN0GiIuZHJpbGwudjEuR2V0Q29hY2hBbmFseXNpc1Jlc3BvbnNlEmUKFFJlcXVlc3RDb2FjaEFuYWx5c2lzEiUuZHJpbGwudjEuUmVxdWVzdENvYWNoQW5hbHlzaXNSZXF1ZXN0GiYuZHJpbGwudjEuUmVxdWVzdENvYWNoQW5hbHlzaXNSZXNwb25zZUIzWjFnaXRodWIuY29tL2J0Yy9kcmlsbC9pbnRlcm5hbC9wYi9kcmlsbC92MTtkcmlsbHYxYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * Describes the message drill.v1.CoachAnalysis.
 * Use `create(CoachAnalysisSchema)` to create a new message.
 */
export const CoachAnalysisSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_coach, 0);

/**
 * Describes the message drill.v1.GetCoachAnalysisRequest.
 * Use `create(GetCoachAnalysisRequestSchema)` to create a new message.
 */
export const GetCoachAnalysisRequestSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_coach, 1);

/**
 * Describes the message drill.v1.GetCoachAnalysisResponse.
 * Use `create(GetCoachAnalysisResponseSchema)` to create a new message.
 */
export const GetCoachAnalysisResponseSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_coach, 2);

/**
 * Describes the message drill.v1.RequestCoachAnalysisRequest.
 * Use `create(RequestCoachAnalysisRequestSchema)` to create a new message.
 */
export const RequestCoachAnalysisRequestSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_coach, 3);

/**
 * Describes the message drill.v1.RequestCoachAnalysisResponse.
 * Use `create(RequestCoachAnalysisResponseSchema)` to create a new message.
 */
export const RequestCoachAnalysisResponseSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_coach, 4);

/**
 * @generated from service drill.v1.CoachService
 */
export const CoachService = /*@__PURE__*/
  serviceDesc(file_drill_v1_coach, 0);

