// @generated by protoc-gen-es v2.11.0
// @generated from file drill/v1/coach.proto (package drill.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file drill/v1/coach.proto.
 */
export const file_drill_v1_coach = /*@__PURE__*/
  fileDesc("ChRkcmlsbC92MS9jb2FjaC5wcm90bxIIZHJpbGwudjEi0wIKDUNvYWNoQW5hbHlzaXMSCgoCaWQYASABKAkSDwoHdXNlcl9pZBgCIAEoCRIRCgluYXJyYXRpdmUYAyABKAkSHgoRd2Vha2VzdF9kaW1lbnNpb24YBCABKAlIAIgBARIcChRpbXByb3ZpbmdfZGltZW5zaW9ucxgFIAMoCRISCgp0b3BpY19nYXBzGAYgAygJEiIKFXN1Z2dlc3RlZF9xdWVzdGlvbl9pZBgHIAEoCUgBiAEBEhkKEXNlc3Npb25zX2FuYWx5emVkGAggAygJEi8KC2NyZWF0ZV90aW1lGAkgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIUCgdzdW1tYXJ5GAogASgJSAKIAQFCFAoSX3dlYWtlc3RfZGltZW5zaW9uQhgKFl9zdWdnZXN0ZWRfcXVlc3Rpb25faWRCCgoIX3N1bW1hcnkiGQoXR2V0Q29hY2hBbmFseXNpc1JlcXVlc3QiVwoYR2V0Q29hY2hBbmFseXNpc1Jlc3BvbnNlEi4KCGFuYWx5c2lzGAEgASgLMhcuZHJpbGwudjEuQ29hY2hBbmFseXNpc0gAiAEBQgsKCV9hbmFseXNpcyIsChtSZXF1ZXN0Q29hY2hBbmFseXNpc1JlcXVlc3QSDQoFZm9yY2UYASABKAgiHgocUmVxdWVzdENvYWNoQW5hbHlzaXNSZXNwb25zZTLQAQoMQ29hY2hTZXJ2aWNlElkKEEdldENvYWNoQW5hbHlzaXMSIS5kcmlsbC52MS5HZXRDb2FjaEFuYWx5c2lzUmVxdWVzdBoiLmRyaWxsLnYxLkdldENvYWNoQW5hbHlzaXNSZXNwb25zZRJlChRSZXF1ZXN0Q29hY2hBbmFseXNpcxIlLmRyaWxsLnYxLlJlcXVlc3RDb2FjaEFuYWx5c2lzUmVxdWVzdBomLmRyaWxsLnYxLlJlcXVlc3RDb2FjaEFuYWx5c2lzUmVzcG9uc2VCM1oxZ2l0aHViLmNvbS9idGMvZHJpbGwvaW50ZXJuYWwvcGIvZHJpbGwvdjE7ZHJpbGx2MWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * Describes the message drill.v1.CoachAnalysis.
 * Use `create(CoachAnalysisSchema)` to create a new message.
 */
export const CoachAnalysisSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_coach, 0);

/**
 * Describes the message drill.v1.GetCoachAnalysisRequest.
 * Use `create(GetCoachAnalysisRequestSchema)` to create a new message.
 */
export const GetCoachAnalysisRequestSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_coach, 1);

/**
 * Describes the message drill.v1.GetCoachAnalysisResponse.
 * Use `create(GetCoachAnalysisResponseSchema)` to create a new message.
 */
export const GetCoachAnalysisResponseSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_coach, 2);

/**
 * Describes the message drill.v1.RequestCoachAnalysisRequest.
 * Use `create(RequestCoachAnalysisRequestSchema)` to create a new message.
 */
export const RequestCoachAnalysisRequestSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_coach, 3);

/**
 * Describes the message drill.v1.RequestCoachAnalysisResponse.
 * Use `create(RequestCoachAnalysisResponseSchema)` to create a new message.
 */
export const RequestCoachAnalysisResponseSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_coach, 4);

/**
 * @generated from service drill.v1.CoachService
 */
export const CoachService = /*@__PURE__*/
  serviceDesc(file_drill_v1_coach, 0);

