// @generated by protoc-gen-connect-query v2.2.0
// @generated from file drill/v1/educator.proto (package drill.v1, syntax proto3)
/* eslint-disable */

import { EducatorService } from "./educator_pb";

/**
 * @generated from rpc drill.v1.EducatorService.GetEducatorAnalysis
 */
export const getEducatorAnalysis: typeof EducatorService["method"]["getEducatorAnalysis"];
/**
 * @generated from rpc drill.v1.EducatorService.RequestEducatorAnalysis
 */
export const requestEducatorAnalysis: typeof EducatorService["method"]["requestEducatorAnalysis"];
