// @generated by protoc-gen-es v2.11.0
// @generated from file drill/v1/educator.proto (package drill.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file drill/v1/educator.proto.
 */
export const file_drill_v1_educator = /*@__PURE__*/
  fileDesc("ChdkcmlsbC92MS9lZHVjYXRvci5wcm90bxIIZHJpbGwudjEiMAoaR2V0RWR1Y2F0b3JBbmFseXNpc1JlcXVlc3QSEgoKc2Vzc2lvbl9pZBgBIAEoCSJLChtHZXRFZHVjYXRvckFuYWx5c2lzUmVzcG9uc2USLAoIYW5hbHlzaXMYASABKAsyGi5kcmlsbC52MS5FZHVjYXRvckFuYWx5c2lzIjQKHlJlcXVlc3RFZHVjYXRvckFuYWx5c2lzUmVxdWVzdBISCgpzZXNzaW9uX2lkGAEgASgJIiEKH1JlcXVlc3RFZHVjYXRvckFuYWx5c2lzUmVzcG9uc2Ui6QEKEEVkdWNhdG9yQW5hbHlzaXMSCgoCaWQYASABKAkSEgoKc2Vzc2lvbl9pZBgCIAEoCRIoCgZzdGF0dXMYAyABKA4yGC5kcmlsbC52MS5FZHVjYXRvclN0YXR1cxIZCgxtb2RlbF9hbnN3ZXIYBCABKAlIAIgBARIbCg5nYXBfZGVlcF9kaXZlcxgFIAEoCUgBiAEBEi8KC2NyZWF0ZV90aW1lGAYgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEIPCg1fbW9kZWxfYW5zd2VyQhEKD19nYXBfZGVlcF9kaXZlcyqvAQoORWR1Y2F0b3JTdGF0dXMSHwobRURVQ0FUT1JfU1RBVFVTX1VOU1BFQ0lGSUVEEAASIQodRURVQ0FUT1JfU1RBVFVTX05PVF9SRVFVRVNURUQQARIeChpFRFVDQVRPUl9TVEFUVVNfR0VORVJBVElORxACEh0KGUVEVUNBVE9SX1NUQVRVU19DT01QTEVURUQQAxIaChZFRFVDQVRPUl9TVEFUVVNfRkFJTEVEEAQy5QEKD0VkdWNhdG9yU2VydmljZRJiChNHZXRFZHVjYXRvckFuYWx5c2lzEiQuZHJpbGwudjEuR2V0RWR1Y2F0b3JBbmFseXNpc1JlcXVlc3QaJS5kcmlsbC52MS5HZXRFZHVjYXRvckFuYWx5c2lzUmVzcG9uc2USbgoXUmVxdWVzdEVkdWNhdG9yQW5hbHlzaXMSKC5kcmlsbC52MS5SZXF1ZXN0RWR1Y2F0b3JBbmFseXNpc1JlcXVlc3QaKS5kcmlsbC52MS5SZXF1ZXN0RWR1Y2F0b3JBbmFseXNpc1Jlc3BvbnNlQjNaMWdpdGh1Yi5jb20vYnRjL2RyaWxsL2ludGVybmFsL3BiL2RyaWxsL3YxO2RyaWxsdjFiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * Describes the message drill.v1.GetEducatorAnalysisRequest.
 * Use `create(GetEducatorAnalysisRequestSchema)` to create a new message.
 */
export const GetEducatorAnalysisRequestSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_educator, 0);

/**
 * Describes the message drill.v1.GetEducatorAnalysisResponse.
 * Use `create(GetEducatorAnalysisResponseSchema)` to create a new message.
 */
export const GetEducatorAnalysisResponseSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_educator, 1);

/**
 * Describes the message drill.v1.RequestEducatorAnalysisRequest.
 * Use `create(RequestEducatorAnalysisRequestSchema)` to create a new message.
 */
export const RequestEducatorAnalysisRequestSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_educator, 2);

/**
 * Describes the message drill.v1.RequestEducatorAnalysisResponse.
 * Use `create(RequestEducatorAnalysisResponseSchema)` to create a new message.
 */
export const RequestEducatorAnalysisResponseSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_educator, 3);

/**
 * Describes the message drill.v1.EducatorAnalysis.
 * Use `create(EducatorAnalysisSchema)` to create a new message.
 */
export const EducatorAnalysisSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_educator, 4);

/**
 * Describes the enum drill.v1.EducatorStatus.
 */
export const EducatorStatusSchema = /*@__PURE__*/
  enumDesc(file_drill_v1_educator, 0);

/**
 * @generated from enum drill.v1.EducatorStatus
 */
export const EducatorStatus = /*@__PURE__*/
  tsEnum(EducatorStatusSchema);

/**
 * @generated from service drill.v1.EducatorService
 */
export const EducatorService = /*@__PURE__*/
  serviceDesc(file_drill_v1_educator, 0);

