// @generated by protoc-gen-es v2.11.0
// @generated from file drill/v1/educator.proto (package drill.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file drill/v1/educator.proto.
 */
export declare const file_drill_v1_educator: GenFile;

/**
 * @generated from message drill.v1.GetEducatorAnalysisRequest
 */
export declare type GetEducatorAnalysisRequest = Message<"drill.v1.GetEducatorAnalysisRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;
};

/**
 * Describes the message drill.v1.GetEducatorAnalysisRequest.
 * Use `create(GetEducatorAnalysisRequestSchema)` to create a new message.
 */
export declare const GetEducatorAnalysisRequestSchema: GenMessage<GetEducatorAnalysisRequest>;

/**
 * @generated from message drill.v1.GetEducatorAnalysisResponse
 */
export declare type GetEducatorAnalysisResponse = Message<"drill.v1.GetEducatorAnalysisResponse"> & {
  /**
   * @generated from field: drill.v1.EducatorAnalysis analysis = 1;
   */
  analysis?: EducatorAnalysis;
};

/**
 * Describes the message drill.v1.GetEducatorAnalysisResponse.
 * Use `create(GetEducatorAnalysisResponseSchema)` to create a new message.
 */
export declare const GetEducatorAnalysisResponseSchema: GenMessage<GetEducatorAnalysisResponse>;

/**
 * @generated from message drill.v1.RequestEducatorAnalysisRequest
 */
export declare type RequestEducatorAnalysisRequest = Message<"drill.v1.RequestEducatorAnalysisRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;
};

/**
 * Describes the message drill.v1.RequestEducatorAnalysisRequest.
 * Use `create(RequestEducatorAnalysisRequestSchema)` to create a new message.
 */
export declare const RequestEducatorAnalysisRequestSchema: GenMessage<RequestEducatorAnalysisRequest>;

/**
 * @generated from message drill.v1.RequestEducatorAnalysisResponse
 */
export declare type RequestEducatorAnalysisResponse = Message<"drill.v1.RequestEducatorAnalysisResponse"> & {
};

/**
 * Describes the message drill.v1.RequestEducatorAnalysisResponse.
 * Use `create(RequestEducatorAnalysisResponseSchema)` to create a new message.
 */
export declare const RequestEducatorAnalysisResponseSchema: GenMessage<RequestEducatorAnalysisResponse>;

/**
 * @generated from message drill.v1.EducatorAnalysis
 */
export declare type EducatorAnalysis = Message<"drill.v1.EducatorAnalysis"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string session_id = 2;
   */
  sessionId: string;

  /**
   * @generated from field: drill.v1.EducatorStatus status = 3;
   */
  status: EducatorStatus;

  /**
   * @generated from field: optional string model_answer = 4;
   */
  modelAnswer?: string;

  /**
   * @generated from field: optional string gap_deep_dives = 5;
   */
  gapDeepDives?: string;

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 6;
   */
  createTime?: Timestamp;
};

/**
 * Describes the message drill.v1.EducatorAnalysis.
 * Use `create(EducatorAnalysisSchema)` to create a new message.
 */
export declare const EducatorAnalysisSchema: GenMessage<EducatorAnalysis>;

/**
 * @generated from enum drill.v1.EducatorStatus
 */
export enum EducatorStatus {
  /**
   * @generated from enum value: EDUCATOR_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: EDUCATOR_STATUS_NOT_REQUESTED = 1;
   */
  NOT_REQUESTED = 1,

  /**
   * @generated from enum value: EDUCATOR_STATUS_GENERATING = 2;
   */
  GENERATING = 2,

  /**
   * @generated from enum value: EDUCATOR_STATUS_COMPLETED = 3;
   */
  COMPLETED = 3,

  /**
   * @generated from enum value: EDUCATOR_STATUS_FAILED = 4;
   */
  FAILED = 4,
}

/**
 * Describes the enum drill.v1.EducatorStatus.
 */
export declare const EducatorStatusSchema: GenEnum<EducatorStatus>;

/**
 * @generated from service drill.v1.EducatorService
 */
export declare const EducatorService: GenService<{
  /**
   * @generated from rpc drill.v1.EducatorService.GetEducatorAnalysis
   */
  getEducatorAnalysis: {
    methodKind: "unary";
    input: typeof GetEducatorAnalysisRequestSchema;
    output: typeof GetEducatorAnalysisResponseSchema;
  },
  /**
   * @generated from rpc drill.v1.EducatorService.RequestEducatorAnalysis
   */
  requestEducatorAnalysis: {
    methodKind: "unary";
    input: typeof RequestEducatorAnalysisRequestSchema;
    output: typeof RequestEducatorAnalysisResponseSchema;
  },
}>;

