// pb/drill/v1/interview.proto

// @generated by protoc-gen-es v2.11.0
// @generated from file drill/v1/interview.proto (package drill.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Message as Message$1, SessionStatus } from "./session_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file drill/v1/interview.proto.
 */
export declare const file_drill_v1_interview: GenFile;

/**
 * @generated from message drill.v1.SubmitTurnRequest
 */
export declare type SubmitTurnRequest = Message<"drill.v1.SubmitTurnRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string traceparent = 2;
   */
  traceparent: string;

  /**
   * @generated from oneof drill.v1.SubmitTurnRequest.input
   */
  input: {
    /**
     * @generated from field: drill.v1.TextInput text_input = 3;
     */
    value: TextInput;
    case: "textInput";
  } | {
    /**
     * @generated from field: drill.v1.VoiceInput voice_input = 4;
     */
    value: VoiceInput;
    case: "voiceInput";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message drill.v1.SubmitTurnRequest.
 * Use `create(SubmitTurnRequestSchema)` to create a new message.
 */
export declare const SubmitTurnRequestSchema: GenMessage<SubmitTurnRequest>;

/**
 * @generated from message drill.v1.TextInput
 */
export declare type TextInput = Message<"drill.v1.TextInput"> & {
  /**
   * @generated from field: string content = 1;
   */
  content: string;
};

/**
 * Describes the message drill.v1.TextInput.
 * Use `create(TextInputSchema)` to create a new message.
 */
export declare const TextInputSchema: GenMessage<TextInput>;

/**
 * @generated from message drill.v1.VoiceInput
 */
export declare type VoiceInput = Message<"drill.v1.VoiceInput"> & {
  /**
   * @generated from field: bytes audio = 1;
   */
  audio: Uint8Array;

  /**
   * @generated from field: string audio_mime_type = 2;
   */
  audioMimeType: string;
};

/**
 * Describes the message drill.v1.VoiceInput.
 * Use `create(VoiceInputSchema)` to create a new message.
 */
export declare const VoiceInputSchema: GenMessage<VoiceInput>;

/**
 * @generated from message drill.v1.TurnEvent
 */
export declare type TurnEvent = Message<"drill.v1.TurnEvent"> & {
  /**
   * @generated from oneof drill.v1.TurnEvent.event
   */
  event: {
    /**
     * @generated from field: drill.v1.TranscriptionResult transcription_result = 1;
     */
    value: TranscriptionResult;
    case: "transcriptionResult";
  } | {
    /**
     * @generated from field: drill.v1.InterviewerToken interviewer_token = 2;
     */
    value: InterviewerToken;
    case: "interviewerToken";
  } | {
    /**
     * @generated from field: drill.v1.InterviewerDone interviewer_done = 3;
     */
    value: InterviewerDone;
    case: "interviewerDone";
  } | {
    /**
     * @generated from field: drill.v1.TtsChunk tts_chunk = 4;
     */
    value: TtsChunk;
    case: "ttsChunk";
  } | {
    /**
     * @generated from field: drill.v1.TtsDone tts_done = 5;
     */
    value: TtsDone;
    case: "ttsDone";
  } | {
    /**
     * @generated from field: drill.v1.TurnError error = 6;
     */
    value: TurnError;
    case: "error";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message drill.v1.TurnEvent.
 * Use `create(TurnEventSchema)` to create a new message.
 */
export declare const TurnEventSchema: GenMessage<TurnEvent>;

/**
 * @generated from message drill.v1.TranscriptionResult
 */
export declare type TranscriptionResult = Message<"drill.v1.TranscriptionResult"> & {
  /**
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message drill.v1.TranscriptionResult.
 * Use `create(TranscriptionResultSchema)` to create a new message.
 */
export declare const TranscriptionResultSchema: GenMessage<TranscriptionResult>;

/**
 * @generated from message drill.v1.InterviewerToken
 */
export declare type InterviewerToken = Message<"drill.v1.InterviewerToken"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message drill.v1.InterviewerToken.
 * Use `create(InterviewerTokenSchema)` to create a new message.
 */
export declare const InterviewerTokenSchema: GenMessage<InterviewerToken>;

/**
 * @generated from message drill.v1.InterviewerDone
 */
export declare type InterviewerDone = Message<"drill.v1.InterviewerDone"> & {
  /**
   * @generated from field: string message_id = 1;
   */
  messageId: string;
};

/**
 * Describes the message drill.v1.InterviewerDone.
 * Use `create(InterviewerDoneSchema)` to create a new message.
 */
export declare const InterviewerDoneSchema: GenMessage<InterviewerDone>;

/**
 * @generated from message drill.v1.TtsChunk
 */
export declare type TtsChunk = Message<"drill.v1.TtsChunk"> & {
  /**
   * @generated from field: bytes data = 1;
   */
  data: Uint8Array;

  /**
   * @generated from field: string message_id = 2;
   */
  messageId: string;

  /**
   * @generated from field: int32 seq = 3;
   */
  seq: number;
};

/**
 * Describes the message drill.v1.TtsChunk.
 * Use `create(TtsChunkSchema)` to create a new message.
 */
export declare const TtsChunkSchema: GenMessage<TtsChunk>;

/**
 * @generated from message drill.v1.TtsDone
 */
export declare type TtsDone = Message<"drill.v1.TtsDone"> & {
  /**
   * @generated from field: string message_id = 1;
   */
  messageId: string;
};

/**
 * Describes the message drill.v1.TtsDone.
 * Use `create(TtsDoneSchema)` to create a new message.
 */
export declare const TtsDoneSchema: GenMessage<TtsDone>;

/**
 * @generated from message drill.v1.TurnError
 */
export declare type TurnError = Message<"drill.v1.TurnError"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message drill.v1.TurnError.
 * Use `create(TurnErrorSchema)` to create a new message.
 */
export declare const TurnErrorSchema: GenMessage<TurnError>;

/**
 * @generated from message drill.v1.GetSessionStateRequest
 */
export declare type GetSessionStateRequest = Message<"drill.v1.GetSessionStateRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: int32 known_message_count = 2;
   */
  knownMessageCount: number;
};

/**
 * Describes the message drill.v1.GetSessionStateRequest.
 * Use `create(GetSessionStateRequestSchema)` to create a new message.
 */
export declare const GetSessionStateRequestSchema: GenMessage<GetSessionStateRequest>;

/**
 * @generated from message drill.v1.GetSessionStateResponse
 */
export declare type GetSessionStateResponse = Message<"drill.v1.GetSessionStateResponse"> & {
  /**
   * @generated from field: drill.v1.InterviewSessionInfo session_info = 1;
   */
  sessionInfo?: InterviewSessionInfo;

  /**
   * @generated from field: repeated drill.v1.Message messages = 2;
   */
  messages: Message$1[];

  /**
   * @generated from field: drill.v1.SessionStatus status = 3;
   */
  status: SessionStatus;
};

/**
 * Describes the message drill.v1.GetSessionStateResponse.
 * Use `create(GetSessionStateResponseSchema)` to create a new message.
 */
export declare const GetSessionStateResponseSchema: GenMessage<GetSessionStateResponse>;

/**
 * @generated from message drill.v1.InterviewSessionInfo
 */
export declare type InterviewSessionInfo = Message<"drill.v1.InterviewSessionInfo"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string question_title = 2;
   */
  questionTitle: string;

  /**
   * @generated from field: string question_prompt = 3;
   */
  questionPrompt: string;

  /**
   * @generated from field: int32 duration_minutes = 4;
   */
  durationMinutes: number;

  /**
   * @generated from field: bool tts_enabled = 5;
   */
  ttsEnabled: boolean;

  /**
   * @generated from field: google.protobuf.Timestamp start_time = 6;
   */
  startTime?: Timestamp;
};

/**
 * Describes the message drill.v1.InterviewSessionInfo.
 * Use `create(InterviewSessionInfoSchema)` to create a new message.
 */
export declare const InterviewSessionInfoSchema: GenMessage<InterviewSessionInfo>;

/**
 * @generated from message drill.v1.EndSessionRequest
 */
export declare type EndSessionRequest = Message<"drill.v1.EndSessionRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;
};

/**
 * Describes the message drill.v1.EndSessionRequest.
 * Use `create(EndSessionRequestSchema)` to create a new message.
 */
export declare const EndSessionRequestSchema: GenMessage<EndSessionRequest>;

/**
 * @generated from message drill.v1.EndSessionResponse
 */
export declare type EndSessionResponse = Message<"drill.v1.EndSessionResponse"> & {
};

/**
 * Describes the message drill.v1.EndSessionResponse.
 * Use `create(EndSessionResponseSchema)` to create a new message.
 */
export declare const EndSessionResponseSchema: GenMessage<EndSessionResponse>;

/**
 * @generated from message drill.v1.CancelSessionRequest
 */
export declare type CancelSessionRequest = Message<"drill.v1.CancelSessionRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;
};

/**
 * Describes the message drill.v1.CancelSessionRequest.
 * Use `create(CancelSessionRequestSchema)` to create a new message.
 */
export declare const CancelSessionRequestSchema: GenMessage<CancelSessionRequest>;

/**
 * @generated from message drill.v1.CancelSessionResponse
 */
export declare type CancelSessionResponse = Message<"drill.v1.CancelSessionResponse"> & {
};

/**
 * Describes the message drill.v1.CancelSessionResponse.
 * Use `create(CancelSessionResponseSchema)` to create a new message.
 */
export declare const CancelSessionResponseSchema: GenMessage<CancelSessionResponse>;

/**
 * @generated from service drill.v1.InterviewService
 */
export declare const InterviewService: GenService<{
  /**
   * AIP-136: Custom method — submit a turn and stream the interviewer response.
   *
   * @generated from rpc drill.v1.InterviewService.SubmitTurn
   */
  submitTurn: {
    methodKind: "server_streaming";
    input: typeof SubmitTurnRequestSchema;
    output: typeof TurnEventSchema;
  },
  /**
   * AIP-131: Get current session state (messages, status, session info).
   *
   * @generated from rpc drill.v1.InterviewService.GetSessionState
   */
  getSessionState: {
    methodKind: "unary";
    input: typeof GetSessionStateRequestSchema;
    output: typeof GetSessionStateResponseSchema;
  },
  /**
   * AIP-136: Custom method — end the session (complete + evaluate).
   *
   * @generated from rpc drill.v1.InterviewService.EndSession
   */
  endSession: {
    methodKind: "unary";
    input: typeof EndSessionRequestSchema;
    output: typeof EndSessionResponseSchema;
  },
  /**
   * AIP-136: Custom method — cancel the session (archive + refund).
   *
   * @generated from rpc drill.v1.InterviewService.CancelSession
   */
  cancelSession: {
    methodKind: "unary";
    input: typeof CancelSessionRequestSchema;
    output: typeof CancelSessionResponseSchema;
  },
}>;

