// @generated by protoc-gen-es v2.11.0
// @generated from file drill/v1/landing.proto (package drill.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_drill_v1_question } from "./question_pb";

/**
 * Describes the file drill/v1/landing.proto.
 */
export const file_drill_v1_landing = /*@__PURE__*/
  fileDesc("ChZkcmlsbC92MS9sYW5kaW5nLnByb3RvEghkcmlsbC52MSIeChxMaXN0RmVhdHVyZWRRdWVzdGlvbnNSZXF1ZXN0IlsKHUxpc3RGZWF0dXJlZFF1ZXN0aW9uc1Jlc3BvbnNlEiUKCXF1ZXN0aW9ucxgBIAMoCzISLmRyaWxsLnYxLlF1ZXN0aW9uEhMKC3RvdGFsX2NvdW50GAIgASgFMnoKDkxhbmRpbmdTZXJ2aWNlEmgKFUxpc3RGZWF0dXJlZFF1ZXN0aW9ucxImLmRyaWxsLnYxLkxpc3RGZWF0dXJlZFF1ZXN0aW9uc1JlcXVlc3QaJy5kcmlsbC52MS5MaXN0RmVhdHVyZWRRdWVzdGlvbnNSZXNwb25zZUIzWjFnaXRodWIuY29tL2J0Yy9kcmlsbC9pbnRlcm5hbC9wYi9kcmlsbC92MTtkcmlsbHYxYgZwcm90bzM", [file_drill_v1_question]);

/**
 * Describes the message drill.v1.ListFeaturedQuestionsRequest.
 * Use `create(ListFeaturedQuestionsRequestSchema)` to create a new message.
 */
export const ListFeaturedQuestionsRequestSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_landing, 0);

/**
 * Describes the message drill.v1.ListFeaturedQuestionsResponse.
 * Use `create(ListFeaturedQuestionsResponseSchema)` to create a new message.
 */
export const ListFeaturedQuestionsResponseSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_landing, 1);

/**
 * LandingService exposes public, auth-exempt data for the unauthenticated
 * marketing landing page. Registered with publicOpts in internal/rpc/register.go.
 *
 * @generated from service drill.v1.LandingService
 */
export const LandingService = /*@__PURE__*/
  serviceDesc(file_drill_v1_landing, 0);

