// @generated by protoc-gen-es v2.11.0
// @generated from file drill/v1/landing.proto (package drill.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Question } from "./question_pb";

/**
 * Describes the file drill/v1/landing.proto.
 */
export declare const file_drill_v1_landing: GenFile;

/**
 * @generated from message drill.v1.ListFeaturedQuestionsRequest
 */
export declare type ListFeaturedQuestionsRequest = Message<"drill.v1.ListFeaturedQuestionsRequest"> & {
};

/**
 * Describes the message drill.v1.ListFeaturedQuestionsRequest.
 * Use `create(ListFeaturedQuestionsRequestSchema)` to create a new message.
 */
export declare const ListFeaturedQuestionsRequestSchema: GenMessage<ListFeaturedQuestionsRequest>;

/**
 * @generated from message drill.v1.ListFeaturedQuestionsResponse
 */
export declare type ListFeaturedQuestionsResponse = Message<"drill.v1.ListFeaturedQuestionsResponse"> & {
  /**
   * ordered by featured_order
   *
   * @generated from field: repeated drill.v1.Question questions = 1;
   */
  questions: Question[];

  /**
   * full library size, for the "N questions" header
   *
   * @generated from field: int32 total_count = 2;
   */
  totalCount: number;
};

/**
 * Describes the message drill.v1.ListFeaturedQuestionsResponse.
 * Use `create(ListFeaturedQuestionsResponseSchema)` to create a new message.
 */
export declare const ListFeaturedQuestionsResponseSchema: GenMessage<ListFeaturedQuestionsResponse>;

/**
 * LandingService exposes public, auth-exempt data for the unauthenticated
 * marketing landing page. Registered with publicOpts in internal/rpc/register.go.
 *
 * @generated from service drill.v1.LandingService
 */
export declare const LandingService: GenService<{
  /**
   * @generated from rpc drill.v1.LandingService.ListFeaturedQuestions
   */
  listFeaturedQuestions: {
    methodKind: "unary";
    input: typeof ListFeaturedQuestionsRequestSchema;
    output: typeof ListFeaturedQuestionsResponseSchema;
  },
}>;

