// @generated by protoc-gen-connect-es v1.6.1
// @generated from file drill/v1/question.proto (package drill.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListQuestionsRequest, ListQuestionsResponse } from "./question_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service drill.v1.QuestionService
 */
export const QuestionService = {
  typeName: "drill.v1.QuestionService",
  methods: {
    /**
     * @generated from rpc drill.v1.QuestionService.ListQuestions
     */
    listQuestions: {
      name: "ListQuestions",
      I: ListQuestionsRequest,
      O: ListQuestionsResponse,
      kind: MethodKind.Unary,
    },
  }
};

