// @generated by protoc-gen-es v2.11.0
// @generated from file drill/v1/question.proto (package drill.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file drill/v1/question.proto.
 */
export const file_drill_v1_question = /*@__PURE__*/
  fileDesc("ChdkcmlsbC92MS9xdWVzdGlvbi5wcm90bxIIZHJpbGwudjEiPQoUTGlzdFF1ZXN0aW9uc1JlcXVlc3QSEQoJcGFnZV9zaXplGAEgASgFEhIKCnBhZ2VfdG9rZW4YAiABKAkiVwoVTGlzdFF1ZXN0aW9uc1Jlc3BvbnNlEiUKCXF1ZXN0aW9ucxgBIAMoCzISLmRyaWxsLnYxLlF1ZXN0aW9uEhcKD25leHRfcGFnZV90b2tlbhgCIAEoCSKIAgoIUXVlc3Rpb24SCgoCaWQYASABKAkSFAoHdXNlcl9pZBgCIAEoCUgAiAEBEg0KBXRpdGxlGAMgASgJEg4KBnByb21wdBgEIAEoCRIoCgpkaWZmaWN1bHR5GAUgASgOMhQuZHJpbGwudjEuRGlmZmljdWx0eRIMCgR0YWdzGAYgAygJEhIKBWhpbnRzGAcgASgJSAGIAQESKAoGc291cmNlGAggASgOMhguZHJpbGwudjEuUXVlc3Rpb25Tb3VyY2USLwoLY3JlYXRlX3RpbWUYCSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQgoKCF91c2VyX2lkQggKBl9oaW50cypUCgpEaWZmaWN1bHR5EhoKFkRJRkZJQ1VMVFlfVU5TUEVDSUZJRUQQABIVChFESUZGSUNVTFRZX01FRElVTRABEhMKD0RJRkZJQ1VMVFlfSEFSRBACKowBCg5RdWVzdGlvblNvdXJjZRIfChtRVUVTVElPTl9TT1VSQ0VfVU5TUEVDSUZJRUQQABIYChRRVUVTVElPTl9TT1VSQ0VfU0VFRBABEhoKFlFVRVNUSU9OX1NPVVJDRV9DVVNUT00QAhIjCh9RVUVTVElPTl9TT1VSQ0VfQ09BQ0hfR0VORVJBVEVEEAMyYwoPUXVlc3Rpb25TZXJ2aWNlElAKDUxpc3RRdWVzdGlvbnMSHi5kcmlsbC52MS5MaXN0UXVlc3Rpb25zUmVxdWVzdBofLmRyaWxsLnYxLkxpc3RRdWVzdGlvbnNSZXNwb25zZUIzWjFnaXRodWIuY29tL2J0Yy9kcmlsbC9pbnRlcm5hbC9wYi9kcmlsbC92MTtkcmlsbHYxYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * Describes the message drill.v1.ListQuestionsRequest.
 * Use `create(ListQuestionsRequestSchema)` to create a new message.
 */
export const ListQuestionsRequestSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_question, 0);

/**
 * Describes the message drill.v1.ListQuestionsResponse.
 * Use `create(ListQuestionsResponseSchema)` to create a new message.
 */
export const ListQuestionsResponseSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_question, 1);

/**
 * Describes the message drill.v1.Question.
 * Use `create(QuestionSchema)` to create a new message.
 */
export const QuestionSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_question, 2);

/**
 * Describes the enum drill.v1.Difficulty.
 */
export const DifficultySchema = /*@__PURE__*/
  enumDesc(file_drill_v1_question, 0);

/**
 * @generated from enum drill.v1.Difficulty
 */
export const Difficulty = /*@__PURE__*/
  tsEnum(DifficultySchema);

/**
 * Describes the enum drill.v1.QuestionSource.
 */
export const QuestionSourceSchema = /*@__PURE__*/
  enumDesc(file_drill_v1_question, 1);

/**
 * @generated from enum drill.v1.QuestionSource
 */
export const QuestionSource = /*@__PURE__*/
  tsEnum(QuestionSourceSchema);

/**
 * @generated from service drill.v1.QuestionService
 */
export const QuestionService = /*@__PURE__*/
  serviceDesc(file_drill_v1_question, 0);

