// @generated by protoc-gen-es v2.11.0
// @generated from file drill/v1/question.proto (package drill.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file drill/v1/question.proto.
 */
export const file_drill_v1_question = /*@__PURE__*/
  fileDesc("ChdkcmlsbC92MS9xdWVzdGlvbi5wcm90bxIIZHJpbGwudjEiQgoVQ3JlYXRlUXVlc3Rpb25SZXF1ZXN0EikKCHF1ZXN0aW9uGAEgASgLMhIuZHJpbGwudjEuUXVlc3Rpb25CA+BBAiI9ChRMaXN0UXVlc3Rpb25zUmVxdWVzdBIRCglwYWdlX3NpemUYASABKAUSEgoKcGFnZV90b2tlbhgCIAEoCSJXChVMaXN0UXVlc3Rpb25zUmVzcG9uc2USJQoJcXVlc3Rpb25zGAEgAygLMhIuZHJpbGwudjEuUXVlc3Rpb24SFwoPbmV4dF9wYWdlX3Rva2VuGAIgASgJItECCghRdWVzdGlvbhIPCgJpZBgBIAEoCUID4EEDEhkKB3VzZXJfaWQYAiABKAlCA+BBA0gAiAEBEhIKBXRpdGxlGAMgASgJQgPgQQISEwoGcHJvbXB0GAQgASgJQgPgQQISKAoKZGlmZmljdWx0eRgFIAEoDjIULmRyaWxsLnYxLkRpZmZpY3VsdHkSDAoEdGFncxgGIAMoCRISCgVoaW50cxgHIAEoCUgBiAEBEi0KBnNvdXJjZRgIIAEoDjIYLmRyaWxsLnYxLlF1ZXN0aW9uU291cmNlQgPgQQMSNAoLY3JlYXRlX3RpbWUYCSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQgPgQQMSGwoJaW1hZ2VfdXJsGAogASgJQgPgQQNIAogBAUIKCghfdXNlcl9pZEIICgZfaGludHNCDAoKX2ltYWdlX3VybCpUCgpEaWZmaWN1bHR5EhoKFkRJRkZJQ1VMVFlfVU5TUEVDSUZJRUQQABIVChFESUZGSUNVTFRZX01FRElVTRABEhMKD0RJRkZJQ1VMVFlfSEFSRBACKowBCg5RdWVzdGlvblNvdXJjZRIfChtRVUVTVElPTl9TT1VSQ0VfVU5TUEVDSUZJRUQQABIYChRRVUVTVElPTl9TT1VSQ0VfU0VFRBABEhoKFlFVRVNUSU9OX1NPVVJDRV9DVVNUT00QAhIjCh9RVUVTVElPTl9TT1VSQ0VfQ09BQ0hfR0VORVJBVEVEEAMyqgEKD1F1ZXN0aW9uU2VydmljZRJQCg1MaXN0UXVlc3Rpb25zEh4uZHJpbGwudjEuTGlzdFF1ZXN0aW9uc1JlcXVlc3QaHy5kcmlsbC52MS5MaXN0UXVlc3Rpb25zUmVzcG9uc2USRQoOQ3JlYXRlUXVlc3Rpb24SHy5kcmlsbC52MS5DcmVhdGVRdWVzdGlvblJlcXVlc3QaEi5kcmlsbC52MS5RdWVzdGlvbkIzWjFnaXRodWIuY29tL2J0Yy9kcmlsbC9pbnRlcm5hbC9wYi9kcmlsbC92MTtkcmlsbHYxYgZwcm90bzM", [file_google_api_field_behavior, file_google_protobuf_timestamp]);

/**
 * Describes the message drill.v1.CreateQuestionRequest.
 * Use `create(CreateQuestionRequestSchema)` to create a new message.
 */
export const CreateQuestionRequestSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_question, 0);

/**
 * Describes the message drill.v1.ListQuestionsRequest.
 * Use `create(ListQuestionsRequestSchema)` to create a new message.
 */
export const ListQuestionsRequestSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_question, 1);

/**
 * Describes the message drill.v1.ListQuestionsResponse.
 * Use `create(ListQuestionsResponseSchema)` to create a new message.
 */
export const ListQuestionsResponseSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_question, 2);

/**
 * Describes the message drill.v1.Question.
 * Use `create(QuestionSchema)` to create a new message.
 */
export const QuestionSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_question, 3);

/**
 * Describes the enum drill.v1.Difficulty.
 */
export const DifficultySchema = /*@__PURE__*/
  enumDesc(file_drill_v1_question, 0);

/**
 * @generated from enum drill.v1.Difficulty
 */
export const Difficulty = /*@__PURE__*/
  tsEnum(DifficultySchema);

/**
 * Describes the enum drill.v1.QuestionSource.
 */
export const QuestionSourceSchema = /*@__PURE__*/
  enumDesc(file_drill_v1_question, 1);

/**
 * @generated from enum drill.v1.QuestionSource
 */
export const QuestionSource = /*@__PURE__*/
  tsEnum(QuestionSourceSchema);

/**
 * @generated from service drill.v1.QuestionService
 */
export const QuestionService = /*@__PURE__*/
  serviceDesc(file_drill_v1_question, 0);

