// @generated by protoc-gen-es v2.11.0
// @generated from file drill/v1/question.proto (package drill.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file drill/v1/question.proto.
 */
export declare const file_drill_v1_question: GenFile;

/**
 * @generated from message drill.v1.CreateQuestionRequest
 */
export declare type CreateQuestionRequest = Message<"drill.v1.CreateQuestionRequest"> & {
  /**
   * @generated from field: drill.v1.Question question = 1;
   */
  question?: Question;
};

/**
 * Describes the message drill.v1.CreateQuestionRequest.
 * Use `create(CreateQuestionRequestSchema)` to create a new message.
 */
export declare const CreateQuestionRequestSchema: GenMessage<CreateQuestionRequest>;

/**
 * @generated from message drill.v1.ListQuestionsRequest
 */
export declare type ListQuestionsRequest = Message<"drill.v1.ListQuestionsRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message drill.v1.ListQuestionsRequest.
 * Use `create(ListQuestionsRequestSchema)` to create a new message.
 */
export declare const ListQuestionsRequestSchema: GenMessage<ListQuestionsRequest>;

/**
 * @generated from message drill.v1.ListQuestionsResponse
 */
export declare type ListQuestionsResponse = Message<"drill.v1.ListQuestionsResponse"> & {
  /**
   * @generated from field: repeated drill.v1.Question questions = 1;
   */
  questions: Question[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message drill.v1.ListQuestionsResponse.
 * Use `create(ListQuestionsResponseSchema)` to create a new message.
 */
export declare const ListQuestionsResponseSchema: GenMessage<ListQuestionsResponse>;

/**
 * @generated from message drill.v1.Question
 */
export declare type Question = Message<"drill.v1.Question"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: optional string user_id = 2;
   */
  userId?: string;

  /**
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * @generated from field: string prompt = 4;
   */
  prompt: string;

  /**
   * @generated from field: drill.v1.Difficulty difficulty = 5;
   */
  difficulty: Difficulty;

  /**
   * @generated from field: repeated string tags = 6;
   */
  tags: string[];

  /**
   * @generated from field: optional string hints = 7;
   */
  hints?: string;

  /**
   * @generated from field: drill.v1.QuestionSource source = 8;
   */
  source: QuestionSource;

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 9;
   */
  createTime?: Timestamp;

  /**
   * @generated from field: optional string image_url = 10;
   */
  imageUrl?: string;
};

/**
 * Describes the message drill.v1.Question.
 * Use `create(QuestionSchema)` to create a new message.
 */
export declare const QuestionSchema: GenMessage<Question>;

/**
 * @generated from enum drill.v1.Difficulty
 */
export enum Difficulty {
  /**
   * @generated from enum value: DIFFICULTY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: DIFFICULTY_MEDIUM = 1;
   */
  MEDIUM = 1,

  /**
   * @generated from enum value: DIFFICULTY_HARD = 2;
   */
  HARD = 2,
}

/**
 * Describes the enum drill.v1.Difficulty.
 */
export declare const DifficultySchema: GenEnum<Difficulty>;

/**
 * @generated from enum drill.v1.QuestionSource
 */
export enum QuestionSource {
  /**
   * @generated from enum value: QUESTION_SOURCE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: QUESTION_SOURCE_SEED = 1;
   */
  SEED = 1,

  /**
   * @generated from enum value: QUESTION_SOURCE_CUSTOM = 2;
   */
  CUSTOM = 2,

  /**
   * @generated from enum value: QUESTION_SOURCE_COACH_GENERATED = 3;
   */
  COACH_GENERATED = 3,
}

/**
 * Describes the enum drill.v1.QuestionSource.
 */
export declare const QuestionSourceSchema: GenEnum<QuestionSource>;

/**
 * @generated from service drill.v1.QuestionService
 */
export declare const QuestionService: GenService<{
  /**
   * @generated from rpc drill.v1.QuestionService.ListQuestions
   */
  listQuestions: {
    methodKind: "unary";
    input: typeof ListQuestionsRequestSchema;
    output: typeof ListQuestionsResponseSchema;
  },
  /**
   * @generated from rpc drill.v1.QuestionService.CreateQuestion
   */
  createQuestion: {
    methodKind: "unary";
    input: typeof CreateQuestionRequestSchema;
    output: typeof QuestionSchema;
  },
}>;

