// @generated by protoc-gen-connect-es v1.6.1
// @generated from file drill/v1/question.proto (package drill.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListQuestionsRequest, ListQuestionsResponse } from "./question_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service drill.v1.QuestionService
 */
export declare const QuestionService: {
  readonly typeName: "drill.v1.QuestionService",
  readonly methods: {
    /**
     * @generated from rpc drill.v1.QuestionService.ListQuestions
     */
    readonly listQuestions: {
      readonly name: "ListQuestions",
      readonly I: typeof ListQuestionsRequest,
      readonly O: typeof ListQuestionsResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

