// @generated by protoc-gen-connect-query v2.2.0
// @generated from file drill/v1/question.proto (package drill.v1, syntax proto3)
/* eslint-disable */

import { QuestionService } from "./question_pb";

/**
 * @generated from rpc drill.v1.QuestionService.ListQuestions
 */
export const listQuestions: typeof QuestionService["method"]["listQuestions"];
