// @generated by protoc-gen-es v2.11.0
// @generated from file drill/v1/sample.proto (package drill.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Message as Message$1, Session } from "./session_pb";
import type { CoachAnalysis } from "./coach_pb";
import type { GetEvaluationResponseSchema } from "./evaluation_pb";
import type { GetEducatorAnalysisResponseSchema } from "./educator_pb";

/**
 * Describes the file drill/v1/sample.proto.
 */
export declare const file_drill_v1_sample: GenFile;

/**
 * @generated from message drill.v1.GetSampleSessionRequest
 */
export declare type GetSampleSessionRequest = Message<"drill.v1.GetSampleSessionRequest"> & {
};

/**
 * Describes the message drill.v1.GetSampleSessionRequest.
 * Use `create(GetSampleSessionRequestSchema)` to create a new message.
 */
export declare const GetSampleSessionRequestSchema: GenMessage<GetSampleSessionRequest>;

/**
 * @generated from message drill.v1.GetSampleSessionResponse
 */
export declare type GetSampleSessionResponse = Message<"drill.v1.GetSampleSessionResponse"> & {
  /**
   * @generated from field: drill.v1.Session session = 1;
   */
  session?: Session;

  /**
   * @generated from field: repeated drill.v1.Message messages = 2;
   */
  messages: Message$1[];
};

/**
 * Describes the message drill.v1.GetSampleSessionResponse.
 * Use `create(GetSampleSessionResponseSchema)` to create a new message.
 */
export declare const GetSampleSessionResponseSchema: GenMessage<GetSampleSessionResponse>;

/**
 * @generated from message drill.v1.GetSampleEvaluationRequest
 */
export declare type GetSampleEvaluationRequest = Message<"drill.v1.GetSampleEvaluationRequest"> & {
};

/**
 * Describes the message drill.v1.GetSampleEvaluationRequest.
 * Use `create(GetSampleEvaluationRequestSchema)` to create a new message.
 */
export declare const GetSampleEvaluationRequestSchema: GenMessage<GetSampleEvaluationRequest>;

/**
 * @generated from message drill.v1.GetSampleEducatorRequest
 */
export declare type GetSampleEducatorRequest = Message<"drill.v1.GetSampleEducatorRequest"> & {
};

/**
 * Describes the message drill.v1.GetSampleEducatorRequest.
 * Use `create(GetSampleEducatorRequestSchema)` to create a new message.
 */
export declare const GetSampleEducatorRequestSchema: GenMessage<GetSampleEducatorRequest>;

/**
 * @generated from message drill.v1.GetSampleCoachRequest
 */
export declare type GetSampleCoachRequest = Message<"drill.v1.GetSampleCoachRequest"> & {
};

/**
 * Describes the message drill.v1.GetSampleCoachRequest.
 * Use `create(GetSampleCoachRequestSchema)` to create a new message.
 */
export declare const GetSampleCoachRequestSchema: GenMessage<GetSampleCoachRequest>;

/**
 * @generated from message drill.v1.GetSampleCoachResponse
 */
export declare type GetSampleCoachResponse = Message<"drill.v1.GetSampleCoachResponse"> & {
  /**
   * @generated from field: drill.v1.CoachAnalysis analysis = 1;
   */
  analysis?: CoachAnalysis;

  /**
   * @generated from field: repeated drill.v1.ScoreTrendPoint score_trend = 2;
   */
  scoreTrend: ScoreTrendPoint[];
};

/**
 * Describes the message drill.v1.GetSampleCoachResponse.
 * Use `create(GetSampleCoachResponseSchema)` to create a new message.
 */
export declare const GetSampleCoachResponseSchema: GenMessage<GetSampleCoachResponse>;

/**
 * @generated from message drill.v1.ScoreTrendPoint
 */
export declare type ScoreTrendPoint = Message<"drill.v1.ScoreTrendPoint"> & {
  /**
   * @generated from field: string date = 1;
   */
  date: string;

  /**
   * @generated from field: int32 overall_score = 2;
   */
  overallScore: number;
};

/**
 * Describes the message drill.v1.ScoreTrendPoint.
 * Use `create(ScoreTrendPointSchema)` to create a new message.
 */
export declare const ScoreTrendPointSchema: GenMessage<ScoreTrendPoint>;

/**
 * @generated from service drill.v1.SampleService
 */
export declare const SampleService: GenService<{
  /**
   * @generated from rpc drill.v1.SampleService.GetSampleSession
   */
  getSampleSession: {
    methodKind: "unary";
    input: typeof GetSampleSessionRequestSchema;
    output: typeof GetSampleSessionResponseSchema;
  },
  /**
   * @generated from rpc drill.v1.SampleService.GetSampleEvaluation
   */
  getSampleEvaluation: {
    methodKind: "unary";
    input: typeof GetSampleEvaluationRequestSchema;
    output: typeof GetEvaluationResponseSchema;
  },
  /**
   * @generated from rpc drill.v1.SampleService.GetSampleEducator
   */
  getSampleEducator: {
    methodKind: "unary";
    input: typeof GetSampleEducatorRequestSchema;
    output: typeof GetEducatorAnalysisResponseSchema;
  },
  /**
   * @generated from rpc drill.v1.SampleService.GetSampleCoach
   */
  getSampleCoach: {
    methodKind: "unary";
    input: typeof GetSampleCoachRequestSchema;
    output: typeof GetSampleCoachResponseSchema;
  },
}>;

