// @generated by protoc-gen-connect-query v2.2.0
// @generated from file drill/v1/sample.proto (package drill.v1, syntax proto3)
/* eslint-disable */

import { SampleService } from "./sample_pb";

/**
 * @generated from rpc drill.v1.SampleService.GetSampleSession
 */
export const getSampleSession: typeof SampleService["method"]["getSampleSession"];
/**
 * @generated from rpc drill.v1.SampleService.GetSampleEvaluation
 */
export const getSampleEvaluation: typeof SampleService["method"]["getSampleEvaluation"];
/**
 * @generated from rpc drill.v1.SampleService.GetSampleEducator
 */
export const getSampleEducator: typeof SampleService["method"]["getSampleEducator"];
/**
 * @generated from rpc drill.v1.SampleService.GetSampleCoach
 */
export const getSampleCoach: typeof SampleService["method"]["getSampleCoach"];
