// @generated by protoc-gen-es v2.11.0
// @generated from file drill/v1/sample.proto (package drill.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_drill_v1_session } from "./session_pb";
import { file_drill_v1_evaluation } from "./evaluation_pb";
import { file_drill_v1_educator } from "./educator_pb";
import { file_drill_v1_coach } from "./coach_pb";

/**
 * Describes the file drill/v1/sample.proto.
 */
export const file_drill_v1_sample = /*@__PURE__*/
  fileDesc("ChVkcmlsbC92MS9zYW1wbGUucHJvdG8SCGRyaWxsLnYxIhkKF0dldFNhbXBsZVNlc3Npb25SZXF1ZXN0ImMKGEdldFNhbXBsZVNlc3Npb25SZXNwb25zZRIiCgdzZXNzaW9uGAEgASgLMhEuZHJpbGwudjEuU2Vzc2lvbhIjCghtZXNzYWdlcxgCIAMoCzIRLmRyaWxsLnYxLk1lc3NhZ2UiHAoaR2V0U2FtcGxlRXZhbHVhdGlvblJlcXVlc3QiTQobR2V0U2FtcGxlRXZhbHVhdGlvblJlc3BvbnNlEi4KCmV2YWx1YXRpb24YASABKAsyGi5kcmlsbC52MS5FdmFsdWF0aW9uUmVzdWx0IhoKGEdldFNhbXBsZUVkdWNhdG9yUmVxdWVzdCJJChlHZXRTYW1wbGVFZHVjYXRvclJlc3BvbnNlEiwKCGFuYWx5c2lzGAEgASgLMhouZHJpbGwudjEuRWR1Y2F0b3JBbmFseXNpcyIXChVHZXRTYW1wbGVDb2FjaFJlcXVlc3QicwoWR2V0U2FtcGxlQ29hY2hSZXNwb25zZRIpCghhbmFseXNpcxgBIAEoCzIXLmRyaWxsLnYxLkNvYWNoQW5hbHlzaXMSLgoLc2NvcmVfdHJlbmQYAiADKAsyGS5kcmlsbC52MS5TY29yZVRyZW5kUG9pbnQiNgoPU2NvcmVUcmVuZFBvaW50EgwKBGRhdGUYASABKAkSFQoNb3ZlcmFsbF9zY29yZRgCIAEoBTKBAwoNU2FtcGxlU2VydmljZRJZChBHZXRTYW1wbGVTZXNzaW9uEiEuZHJpbGwudjEuR2V0U2FtcGxlU2Vzc2lvblJlcXVlc3QaIi5kcmlsbC52MS5HZXRTYW1wbGVTZXNzaW9uUmVzcG9uc2USYgoTR2V0U2FtcGxlRXZhbHVhdGlvbhIkLmRyaWxsLnYxLkdldFNhbXBsZUV2YWx1YXRpb25SZXF1ZXN0GiUuZHJpbGwudjEuR2V0U2FtcGxlRXZhbHVhdGlvblJlc3BvbnNlElwKEUdldFNhbXBsZUVkdWNhdG9yEiIuZHJpbGwudjEuR2V0U2FtcGxlRWR1Y2F0b3JSZXF1ZXN0GiMuZHJpbGwudjEuR2V0U2FtcGxlRWR1Y2F0b3JSZXNwb25zZRJTCg5HZXRTYW1wbGVDb2FjaBIfLmRyaWxsLnYxLkdldFNhbXBsZUNvYWNoUmVxdWVzdBogLmRyaWxsLnYxLkdldFNhbXBsZUNvYWNoUmVzcG9uc2VCM1oxZ2l0aHViLmNvbS9idGMvZHJpbGwvaW50ZXJuYWwvcGIvZHJpbGwvdjE7ZHJpbGx2MWIGcHJvdG8z", [file_drill_v1_session, file_drill_v1_evaluation, file_drill_v1_educator, file_drill_v1_coach]);

/**
 * Describes the message drill.v1.GetSampleSessionRequest.
 * Use `create(GetSampleSessionRequestSchema)` to create a new message.
 */
export const GetSampleSessionRequestSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_sample, 0);

/**
 * Describes the message drill.v1.GetSampleSessionResponse.
 * Use `create(GetSampleSessionResponseSchema)` to create a new message.
 */
export const GetSampleSessionResponseSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_sample, 1);

/**
 * Describes the message drill.v1.GetSampleEvaluationRequest.
 * Use `create(GetSampleEvaluationRequestSchema)` to create a new message.
 */
export const GetSampleEvaluationRequestSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_sample, 2);

/**
 * Describes the message drill.v1.GetSampleEvaluationResponse.
 * Use `create(GetSampleEvaluationResponseSchema)` to create a new message.
 */
export const GetSampleEvaluationResponseSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_sample, 3);

/**
 * Describes the message drill.v1.GetSampleEducatorRequest.
 * Use `create(GetSampleEducatorRequestSchema)` to create a new message.
 */
export const GetSampleEducatorRequestSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_sample, 4);

/**
 * Describes the message drill.v1.GetSampleEducatorResponse.
 * Use `create(GetSampleEducatorResponseSchema)` to create a new message.
 */
export const GetSampleEducatorResponseSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_sample, 5);

/**
 * Describes the message drill.v1.GetSampleCoachRequest.
 * Use `create(GetSampleCoachRequestSchema)` to create a new message.
 */
export const GetSampleCoachRequestSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_sample, 6);

/**
 * Describes the message drill.v1.GetSampleCoachResponse.
 * Use `create(GetSampleCoachResponseSchema)` to create a new message.
 */
export const GetSampleCoachResponseSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_sample, 7);

/**
 * Describes the message drill.v1.ScoreTrendPoint.
 * Use `create(ScoreTrendPointSchema)` to create a new message.
 */
export const ScoreTrendPointSchema = /*@__PURE__*/
  messageDesc(file_drill_v1_sample, 8);

/**
 * @generated from service drill.v1.SampleService
 */
export const SampleService = /*@__PURE__*/
  serviceDesc(file_drill_v1_sample, 0);

