// @generated by protoc-gen-es v2.11.0
// @generated from file drill/v1/session.proto (package drill.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message as Message$1 } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file drill/v1/session.proto.
 */
export declare const file_drill_v1_session: GenFile;

/**
 * @generated from message drill.v1.GetSessionRequest
 */
export declare type GetSessionRequest = Message$1<"drill.v1.GetSessionRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message drill.v1.GetSessionRequest.
 * Use `create(GetSessionRequestSchema)` to create a new message.
 */
export declare const GetSessionRequestSchema: GenMessage<GetSessionRequest>;

/**
 * @generated from message drill.v1.GetSessionResponse
 */
export declare type GetSessionResponse = Message$1<"drill.v1.GetSessionResponse"> & {
  /**
   * @generated from field: drill.v1.Session session = 1;
   */
  session?: Session;
};

/**
 * Describes the message drill.v1.GetSessionResponse.
 * Use `create(GetSessionResponseSchema)` to create a new message.
 */
export declare const GetSessionResponseSchema: GenMessage<GetSessionResponse>;

/**
 * @generated from message drill.v1.ListSessionsRequest
 */
export declare type ListSessionsRequest = Message$1<"drill.v1.ListSessionsRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message drill.v1.ListSessionsRequest.
 * Use `create(ListSessionsRequestSchema)` to create a new message.
 */
export declare const ListSessionsRequestSchema: GenMessage<ListSessionsRequest>;

/**
 * @generated from message drill.v1.ListSessionsResponse
 */
export declare type ListSessionsResponse = Message$1<"drill.v1.ListSessionsResponse"> & {
  /**
   * @generated from field: repeated drill.v1.SessionSummary sessions = 1;
   */
  sessions: SessionSummary[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message drill.v1.ListSessionsResponse.
 * Use `create(ListSessionsResponseSchema)` to create a new message.
 */
export declare const ListSessionsResponseSchema: GenMessage<ListSessionsResponse>;

/**
 * @generated from message drill.v1.CreateSessionRequest
 */
export declare type CreateSessionRequest = Message$1<"drill.v1.CreateSessionRequest"> & {
  /**
   * @generated from field: string question_id = 1;
   */
  questionId: string;

  /**
   * @generated from field: int32 duration_minutes = 2;
   */
  durationMinutes: number;

  /**
   * @generated from field: bool tts_enabled = 3;
   */
  ttsEnabled: boolean;
};

/**
 * Describes the message drill.v1.CreateSessionRequest.
 * Use `create(CreateSessionRequestSchema)` to create a new message.
 */
export declare const CreateSessionRequestSchema: GenMessage<CreateSessionRequest>;

/**
 * @generated from message drill.v1.CreateSessionResponse
 */
export declare type CreateSessionResponse = Message$1<"drill.v1.CreateSessionResponse"> & {
  /**
   * @generated from field: drill.v1.Session session = 1;
   */
  session?: Session;
};

/**
 * Describes the message drill.v1.CreateSessionResponse.
 * Use `create(CreateSessionResponseSchema)` to create a new message.
 */
export declare const CreateSessionResponseSchema: GenMessage<CreateSessionResponse>;

/**
 * @generated from message drill.v1.ArchiveSessionsRequest
 */
export declare type ArchiveSessionsRequest = Message$1<"drill.v1.ArchiveSessionsRequest"> & {
  /**
   * @generated from field: repeated string session_ids = 1;
   */
  sessionIds: string[];

  /**
   * @generated from field: bool archive = 2;
   */
  archive: boolean;
};

/**
 * Describes the message drill.v1.ArchiveSessionsRequest.
 * Use `create(ArchiveSessionsRequestSchema)` to create a new message.
 */
export declare const ArchiveSessionsRequestSchema: GenMessage<ArchiveSessionsRequest>;

/**
 * @generated from message drill.v1.ArchiveSessionsResponse
 */
export declare type ArchiveSessionsResponse = Message$1<"drill.v1.ArchiveSessionsResponse"> & {
};

/**
 * Describes the message drill.v1.ArchiveSessionsResponse.
 * Use `create(ArchiveSessionsResponseSchema)` to create a new message.
 */
export declare const ArchiveSessionsResponseSchema: GenMessage<ArchiveSessionsResponse>;

/**
 * @generated from message drill.v1.GetTranscriptRequest
 */
export declare type GetTranscriptRequest = Message$1<"drill.v1.GetTranscriptRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;
};

/**
 * Describes the message drill.v1.GetTranscriptRequest.
 * Use `create(GetTranscriptRequestSchema)` to create a new message.
 */
export declare const GetTranscriptRequestSchema: GenMessage<GetTranscriptRequest>;

/**
 * @generated from message drill.v1.GetTranscriptResponse
 */
export declare type GetTranscriptResponse = Message$1<"drill.v1.GetTranscriptResponse"> & {
  /**
   * @generated from field: repeated drill.v1.Message messages = 1;
   */
  messages: Message[];
};

/**
 * Describes the message drill.v1.GetTranscriptResponse.
 * Use `create(GetTranscriptResponseSchema)` to create a new message.
 */
export declare const GetTranscriptResponseSchema: GenMessage<GetTranscriptResponse>;

/**
 * Full session detail (returned by Get/Create).
 *
 * @generated from message drill.v1.Session
 */
export declare type Session = Message$1<"drill.v1.Session"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * @generated from field: string question_id = 3;
   */
  questionId: string;

  /**
   * @generated from field: drill.v1.SessionStatus status = 4;
   */
  status: SessionStatus;

  /**
   * @generated from field: int32 config_duration_minutes = 5;
   */
  configDurationMinutes: number;

  /**
   * @generated from field: bool config_tts_enabled = 6;
   */
  configTtsEnabled: boolean;

  /**
   * @generated from field: bool config_coach_briefing = 7;
   */
  configCoachBriefing: boolean;

  /**
   * @generated from field: google.protobuf.Timestamp start_time = 8;
   */
  startTime?: Timestamp;

  /**
   * @generated from field: optional google.protobuf.Timestamp end_time = 9;
   */
  endTime?: Timestamp;

  /**
   * @generated from field: int32 turn_count = 10;
   */
  turnCount: number;

  /**
   * @generated from field: optional google.protobuf.Timestamp archive_time = 11;
   */
  archiveTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 12;
   */
  createTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp update_time = 13;
   */
  updateTime?: Timestamp;

  /**
   * @generated from field: string question_title = 14;
   */
  questionTitle: string;

  /**
   * @generated from field: string question_prompt = 15;
   */
  questionPrompt: string;

  /**
   * @generated from field: string question_difficulty = 16;
   */
  questionDifficulty: string;

  /**
   * @generated from field: optional string question_hints = 17;
   */
  questionHints?: string;
};

/**
 * Describes the message drill.v1.Session.
 * Use `create(SessionSchema)` to create a new message.
 */
export declare const SessionSchema: GenMessage<Session>;

/**
 * Summary for list view (lighter than full Session).
 *
 * @generated from message drill.v1.SessionSummary
 */
export declare type SessionSummary = Message$1<"drill.v1.SessionSummary"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * @generated from field: string question_id = 3;
   */
  questionId: string;

  /**
   * @generated from field: drill.v1.SessionStatus status = 4;
   */
  status: SessionStatus;

  /**
   * @generated from field: int32 config_duration_minutes = 5;
   */
  configDurationMinutes: number;

  /**
   * @generated from field: bool config_tts_enabled = 6;
   */
  configTtsEnabled: boolean;

  /**
   * @generated from field: google.protobuf.Timestamp start_time = 7;
   */
  startTime?: Timestamp;

  /**
   * @generated from field: optional google.protobuf.Timestamp end_time = 8;
   */
  endTime?: Timestamp;

  /**
   * @generated from field: int32 turn_count = 9;
   */
  turnCount: number;

  /**
   * @generated from field: optional google.protobuf.Timestamp archive_time = 10;
   */
  archiveTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 11;
   */
  createTime?: Timestamp;

  /**
   * @generated from field: string question_title = 12;
   */
  questionTitle: string;
};

/**
 * Describes the message drill.v1.SessionSummary.
 * Use `create(SessionSummarySchema)` to create a new message.
 */
export declare const SessionSummarySchema: GenMessage<SessionSummary>;

/**
 * @generated from message drill.v1.Message
 */
export declare type Message = Message$1<"drill.v1.Message"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string session_id = 2;
   */
  sessionId: string;

  /**
   * @generated from field: int32 seq = 3;
   */
  seq: number;

  /**
   * @generated from field: string role = 4;
   */
  role: string;

  /**
   * @generated from field: string content = 5;
   */
  content: string;

  /**
   * @generated from field: optional string input_method = 6;
   */
  inputMethod?: string;

  /**
   * @generated from field: optional string audio_url = 7;
   */
  audioUrl?: string;

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 8;
   */
  createTime?: Timestamp;
};

/**
 * Describes the message drill.v1.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export declare const MessageSchema: GenMessage<Message>;

/**
 * @generated from enum drill.v1.SessionStatus
 */
export enum SessionStatus {
  /**
   * @generated from enum value: SESSION_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SESSION_STATUS_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * @generated from enum value: SESSION_STATUS_COMPLETED = 2;
   */
  COMPLETED = 2,

  /**
   * @generated from enum value: SESSION_STATUS_EVALUATING = 3;
   */
  EVALUATING = 3,

  /**
   * @generated from enum value: SESSION_STATUS_REVIEWED = 4;
   */
  REVIEWED = 4,

  /**
   * @generated from enum value: SESSION_STATUS_EVALUATION_FAILED = 5;
   */
  EVALUATION_FAILED = 5,

  /**
   * @generated from enum value: SESSION_STATUS_FAILED = 6;
   */
  FAILED = 6,

  /**
   * @generated from enum value: SESSION_STATUS_CANCELLED = 7;
   */
  CANCELLED = 7,
}

/**
 * Describes the enum drill.v1.SessionStatus.
 */
export declare const SessionStatusSchema: GenEnum<SessionStatus>;

/**
 * @generated from service drill.v1.SessionService
 */
export declare const SessionService: GenService<{
  /**
   * AIP-131: Get a single session by ID.
   *
   * @generated from rpc drill.v1.SessionService.GetSession
   */
  getSession: {
    methodKind: "unary";
    input: typeof GetSessionRequestSchema;
    output: typeof GetSessionResponseSchema;
  },
  /**
   * AIP-132: List sessions for the authenticated user.
   *
   * @generated from rpc drill.v1.SessionService.ListSessions
   */
  listSessions: {
    methodKind: "unary";
    input: typeof ListSessionsRequestSchema;
    output: typeof ListSessionsResponseSchema;
  },
  /**
   * AIP-133: Create a new interview session.
   *
   * @generated from rpc drill.v1.SessionService.CreateSession
   */
  createSession: {
    methodKind: "unary";
    input: typeof CreateSessionRequestSchema;
    output: typeof CreateSessionResponseSchema;
  },
  /**
   * AIP-136: Custom method — bulk archive/unarchive sessions.
   *
   * @generated from rpc drill.v1.SessionService.ArchiveSessions
   */
  archiveSessions: {
    methodKind: "unary";
    input: typeof ArchiveSessionsRequestSchema;
    output: typeof ArchiveSessionsResponseSchema;
  },
  /**
   * AIP-131: Get the transcript (messages) for a session.
   *
   * @generated from rpc drill.v1.SessionService.GetTranscript
   */
  getTranscript: {
    methodKind: "unary";
    input: typeof GetTranscriptRequestSchema;
    output: typeof GetTranscriptResponseSchema;
  },
}>;

