// @generated by protoc-gen-connect-query v2.2.0
// @generated from file drill/v1/user.proto (package drill.v1, syntax proto3)
/* eslint-disable */

import { UserService } from "./user_pb";

/**
 * @generated from rpc drill.v1.UserService.GetMe
 */
export const getMe: typeof UserService["method"]["getMe"];
/**
 * @generated from rpc drill.v1.UserService.GetUsage
 */
export const getUsage: typeof UserService["method"]["getUsage"];
/**
 * @generated from rpc drill.v1.UserService.UpdateProfile
 */
export const updateProfile: typeof UserService["method"]["updateProfile"];
/**
 * @generated from rpc drill.v1.UserService.ExportData
 */
export const exportData: typeof UserService["method"]["exportData"];
