// @generated by protoc-gen-es v2.11.0
// @generated from file drill/v1/user.proto (package drill.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { FieldMask, Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file drill/v1/user.proto.
 */
export declare const file_drill_v1_user: GenFile;

/**
 * @generated from message drill.v1.GetMeRequest
 */
export declare type GetMeRequest = Message<"drill.v1.GetMeRequest"> & {
};

/**
 * Describes the message drill.v1.GetMeRequest.
 * Use `create(GetMeRequestSchema)` to create a new message.
 */
export declare const GetMeRequestSchema: GenMessage<GetMeRequest>;

/**
 * @generated from message drill.v1.GetMeResponse
 */
export declare type GetMeResponse = Message<"drill.v1.GetMeResponse"> & {
  /**
   * @generated from field: drill.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message drill.v1.GetMeResponse.
 * Use `create(GetMeResponseSchema)` to create a new message.
 */
export declare const GetMeResponseSchema: GenMessage<GetMeResponse>;

/**
 * @generated from message drill.v1.User
 */
export declare type User = Message<"drill.v1.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string display_name = 3;
   */
  displayName: string;

  /**
   * @generated from field: drill.v1.UserRole role = 4;
   */
  role: UserRole;

  /**
   * @generated from field: drill.v1.UserPlan plan = 5;
   */
  plan: UserPlan;

  /**
   * @generated from field: bool email_verified = 6;
   */
  emailVerified: boolean;

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 7;
   */
  createTime?: Timestamp;
};

/**
 * Describes the message drill.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export declare const UserSchema: GenMessage<User>;

/**
 * @generated from message drill.v1.GetUsageRequest
 */
export declare type GetUsageRequest = Message<"drill.v1.GetUsageRequest"> & {
};

/**
 * Describes the message drill.v1.GetUsageRequest.
 * Use `create(GetUsageRequestSchema)` to create a new message.
 */
export declare const GetUsageRequestSchema: GenMessage<GetUsageRequest>;

/**
 * @generated from message drill.v1.GetUsageResponse
 */
export declare type GetUsageResponse = Message<"drill.v1.GetUsageResponse"> & {
  /**
   * @generated from field: int32 total_balance = 1;
   */
  totalBalance: number;

  /**
   * @generated from field: int32 free_balance = 2;
   */
  freeBalance: number;

  /**
   * @generated from field: int32 paid_balance = 3;
   */
  paidBalance: number;

  /**
   * @generated from field: repeated drill.v1.Grant grants = 4;
   */
  grants: Grant[];

  /**
   * @generated from field: repeated drill.v1.LedgerEntry recent_activity = 5;
   */
  recentActivity: LedgerEntry[];
};

/**
 * Describes the message drill.v1.GetUsageResponse.
 * Use `create(GetUsageResponseSchema)` to create a new message.
 */
export declare const GetUsageResponseSchema: GenMessage<GetUsageResponse>;

/**
 * @generated from message drill.v1.Grant
 */
export declare type Grant = Message<"drill.v1.Grant"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string source = 2;
   */
  source: string;

  /**
   * @generated from field: int32 initial_minutes = 3;
   */
  initialMinutes: number;

  /**
   * @generated from field: int32 remaining_minutes = 4;
   */
  remainingMinutes: number;

  /**
   * @generated from field: optional google.protobuf.Timestamp expire_time = 5;
   */
  expireTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 6;
   */
  createTime?: Timestamp;
};

/**
 * Describes the message drill.v1.Grant.
 * Use `create(GrantSchema)` to create a new message.
 */
export declare const GrantSchema: GenMessage<Grant>;

/**
 * @generated from message drill.v1.LedgerEntry
 */
export declare type LedgerEntry = Message<"drill.v1.LedgerEntry"> & {
  /**
   * @generated from field: int32 amount = 1;
   */
  amount: number;

  /**
   * @generated from field: string reason = 2;
   */
  reason: string;

  /**
   * @generated from field: optional string session_id = 3;
   */
  sessionId?: string;

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 4;
   */
  createTime?: Timestamp;
};

/**
 * Describes the message drill.v1.LedgerEntry.
 * Use `create(LedgerEntrySchema)` to create a new message.
 */
export declare const LedgerEntrySchema: GenMessage<LedgerEntry>;

/**
 * AIP-134: Update uses field mask for partial updates (PATCH semantics).
 *
 * @generated from message drill.v1.UpdateProfileRequest
 */
export declare type UpdateProfileRequest = Message<"drill.v1.UpdateProfileRequest"> & {
  /**
   * @generated from field: drill.v1.User user = 1;
   */
  user?: User;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask;
};

/**
 * Describes the message drill.v1.UpdateProfileRequest.
 * Use `create(UpdateProfileRequestSchema)` to create a new message.
 */
export declare const UpdateProfileRequestSchema: GenMessage<UpdateProfileRequest>;

/**
 * @generated from message drill.v1.UpdateProfileResponse
 */
export declare type UpdateProfileResponse = Message<"drill.v1.UpdateProfileResponse"> & {
  /**
   * @generated from field: drill.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message drill.v1.UpdateProfileResponse.
 * Use `create(UpdateProfileResponseSchema)` to create a new message.
 */
export declare const UpdateProfileResponseSchema: GenMessage<UpdateProfileResponse>;

/**
 * @generated from message drill.v1.ExportDataRequest
 */
export declare type ExportDataRequest = Message<"drill.v1.ExportDataRequest"> & {
};

/**
 * Describes the message drill.v1.ExportDataRequest.
 * Use `create(ExportDataRequestSchema)` to create a new message.
 */
export declare const ExportDataRequestSchema: GenMessage<ExportDataRequest>;

/**
 * @generated from message drill.v1.ExportDataResponse
 */
export declare type ExportDataResponse = Message<"drill.v1.ExportDataResponse"> & {
};

/**
 * Describes the message drill.v1.ExportDataResponse.
 * Use `create(ExportDataResponseSchema)` to create a new message.
 */
export declare const ExportDataResponseSchema: GenMessage<ExportDataResponse>;

/**
 * @generated from enum drill.v1.UserRole
 */
export enum UserRole {
  /**
   * @generated from enum value: USER_ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: USER_ROLE_CANDIDATE = 1;
   */
  CANDIDATE = 1,

  /**
   * @generated from enum value: USER_ROLE_ADMIN = 2;
   */
  ADMIN = 2,
}

/**
 * Describes the enum drill.v1.UserRole.
 */
export declare const UserRoleSchema: GenEnum<UserRole>;

/**
 * @generated from enum drill.v1.UserPlan
 */
export enum UserPlan {
  /**
   * @generated from enum value: USER_PLAN_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: USER_PLAN_FREE = 1;
   */
  FREE = 1,

  /**
   * @generated from enum value: USER_PLAN_PRO = 2;
   */
  PRO = 2,
}

/**
 * Describes the enum drill.v1.UserPlan.
 */
export declare const UserPlanSchema: GenEnum<UserPlan>;

/**
 * UserService provides authenticated user profile and usage endpoints.
 *
 * @generated from service drill.v1.UserService
 */
export declare const UserService: GenService<{
  /**
   * @generated from rpc drill.v1.UserService.GetMe
   */
  getMe: {
    methodKind: "unary";
    input: typeof GetMeRequestSchema;
    output: typeof GetMeResponseSchema;
  },
  /**
   * @generated from rpc drill.v1.UserService.GetUsage
   */
  getUsage: {
    methodKind: "unary";
    input: typeof GetUsageRequestSchema;
    output: typeof GetUsageResponseSchema;
  },
  /**
   * @generated from rpc drill.v1.UserService.UpdateProfile
   */
  updateProfile: {
    methodKind: "unary";
    input: typeof UpdateProfileRequestSchema;
    output: typeof UpdateProfileResponseSchema;
  },
  /**
   * @generated from rpc drill.v1.UserService.ExportData
   */
  exportData: {
    methodKind: "unary";
    input: typeof ExportDataRequestSchema;
    output: typeof ExportDataResponseSchema;
  },
}>;

