-- Seed questions for system design interview practice.
-- Idempotent: only inserts if no seed questions exist yet.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM questions WHERE source = 'seed') THEN
        INSERT INTO questions (title, prompt, difficulty, tags, hints, source) VALUES
        ('URL Shortener', 'Design a URL shortening service.', 'medium',
         ARRAY['read-heavy','hashing','storage','web'],
         'How do you generate short URLs? Hash collisions? Read vs write ratio and caching strategy. Analytics and click tracking. Custom short URLs and expiration.', 'seed'),
        ('News Feed', 'Design a social media news feed.', 'hard',
         ARRAY['read-heavy','fanout','caching','ranking','social'],
         'Push vs pull model for feed generation. Ranking and relevance algorithms. Celebrity/influencer problem (fanout). Real-time updates vs polling.', 'seed'),
        ('Chat System', 'Design a real-time chat application.', 'medium',
         ARRAY['real-time','websocket','messaging','presence'],
         '1:1 vs group chat differences. Online presence and typing indicators. Message delivery guarantees and ordering. Offline message handling.', 'seed'),
        ('Rate Limiter', 'Design a rate limiting service.', 'medium',
         ARRAY['distributed','algorithms','middleware','reliability'],
         'Token bucket vs sliding window vs fixed window. Distributed rate limiting across multiple servers. Different rate limit tiers. Client identification.', 'seed'),
        ('Web Crawler', 'Design a web crawler.', 'hard',
         ARRAY['distributed','storage','graph','deduplication'],
         'URL frontier and prioritization. Politeness and robots.txt. Deduplication of content. Distributed crawling coordination.', 'seed'),
        ('Notification System', 'Design a notification delivery system.', 'medium',
         ARRAY['distributed','messaging','push','email'],
         'Multiple channels (push, email, SMS, in-app). Delivery guarantees and retry. User preferences and throttling. Template management.', 'seed'),
        ('Video Streaming', 'Design a video streaming platform.', 'hard',
         ARRAY['streaming','cdn','encoding','storage'],
         'Video encoding and adaptive bitrate. CDN and edge caching. Upload pipeline and processing. Live vs on-demand streaming.', 'seed'),
        ('Search Autocomplete', 'Design a search autocomplete system.', 'medium',
         ARRAY['search','trie','caching','ranking'],
         'Trie vs other data structures. Ranking suggestions by popularity. Personalization. Handling misspellings.', 'seed'),
        ('Distributed Cache', 'Design a distributed caching system.', 'hard',
         ARRAY['distributed','caching','consistency','partitioning'],
         'Consistent hashing. Cache eviction policies. Cache invalidation strategies. Replication and failover.', 'seed'),
        ('File Storage', 'Design a cloud file storage service like Dropbox.', 'hard',
         ARRAY['storage','sync','deduplication','distributed'],
         'File chunking and deduplication. Sync conflict resolution. Metadata vs content storage separation. Sharing and permissions.', 'seed'),
        ('Ride Sharing', 'Design a ride-sharing service like Uber.', 'hard',
         ARRAY['real-time','geospatial','matching','pricing'],
         'Driver-rider matching algorithm. Real-time location tracking. Surge pricing. ETA calculation.', 'seed'),
        ('Task Queue', 'Design a distributed task queue.', 'medium',
         ARRAY['distributed','queue','reliability','scheduling'],
         'At-least-once vs exactly-once delivery. Priority queues. Dead letter queues. Delayed/scheduled tasks.', 'seed'),
        ('E-Commerce', 'Design an e-commerce platform.', 'hard',
         ARRAY['transactions','inventory','search','payments'],
         'Inventory management and race conditions. Product search and filtering. Shopping cart. Order processing pipeline.', 'seed'),
        ('Metrics System', 'Design a metrics collection and alerting system.', 'hard',
         ARRAY['time-series','aggregation','alerting','streaming'],
         'Time-series data storage. Aggregation at different granularities. Alert evaluation engine. High cardinality labels.', 'seed'),
        ('Key-Value Store', 'Design a distributed key-value store.', 'medium',
         ARRAY['distributed','storage','consistency','replication'],
         'Partitioning strategy. Replication and consistency model. Read/write paths. Failure detection and recovery.', 'seed'),
        ('Social Graph', 'Design a social graph service.', 'medium',
         ARRAY['graph','social','caching','relationships'],
         'Friend recommendations. Graph traversal for mutual friends. Fan-out for activity feeds. Privacy controls.', 'seed'),
        ('Payment System', 'Design a payment processing system.', 'hard',
         ARRAY['transactions','reliability','security','ledger'],
         'Idempotency in payment processing. Double-entry bookkeeping. Payment gateway integration. Fraud detection.', 'seed'),
        ('Content Moderation', 'Design a content moderation system.', 'medium',
         ARRAY['ml','queue','review','policy'],
         'Automated vs human review pipeline. Priority and escalation. Appeals process. Policy versioning.', 'seed');
    END IF;
END $$;
