// Code generated by aippatchgen. DO NOT EDIT.
package patches

import (
	drillv1 "github.com/btc/drill/internal/pb/drill/v1"
	"github.com/btc/drill/thirdparty/aippatch"
)

// Codecs is the shared registry of enum codecs declared in aippatch.yaml.
// Validate(Codecs) selects the codecs reachable from each Mapping's Bindings.
var Codecs = map[string]aippatch.EnumCodec{
	"enum_plan": {
		ProtoEnum: "drill.v1.UserPlan",
		ToText: map[int32]string{
			int32(drillv1.UserPlan_USER_PLAN_FREE): "free",
			int32(drillv1.UserPlan_USER_PLAN_PRO):  "pro",
		},
	},
	"enum_role": {
		ProtoEnum: "drill.v1.UserRole",
		ToText: map[int32]string{
			int32(drillv1.UserRole_USER_ROLE_CANDIDATE): "candidate",
			int32(drillv1.UserRole_USER_ROLE_ADMIN):     "admin",
		},
	},
}

// InitPatches validates every generated mapping. Call once at server startup.
// Returns the first validation error encountered; never panics.
func InitPatches() error {
	for _, fn := range []func(map[string]aippatch.EnumCodec) error{
		UserPatch.Validate,
	} {
		if err := fn(Codecs); err != nil {
			return err
		}
	}
	return nil
}
