// Code generated by aippatchgen. DO NOT EDIT.
package patches

import (
	drillv1 "github.com/btc/drill/internal/pb/drill/v1"
	"github.com/btc/drill/thirdparty/aippatch"
)

// UserPatch is the PATCH mapping for drill.v1.User -> users.
// Validate(Codecs) is called from InitPatches() at startup, never at package init.
var UserPatch = &aippatch.Mapping[*drillv1.User]{
	Table:      "users",
	PK:         "id",
	SoftDelete: "deleted_at",
	EmptyMask:  aippatch.ErrorOnEmpty,
	Bindings: []aippatch.Binding{
		{Proto: "create_time", Column: "created_at", SQLType: "timestamptz", Writable: false, Codec: "timestamp"},
		{Proto: "display_name", Column: "display_name", SQLType: "text", Writable: true, Codec: ""},
		{Proto: "email", Column: "email", SQLType: "text", Writable: false, Codec: ""},
		{Proto: "email_verified", Column: "email_verified", SQLType: "boolean", Writable: false, Codec: ""},
		{Proto: "id", Column: "id", SQLType: "uuid", Writable: false, Codec: ""},
		{Proto: "plan", Column: "plan", SQLType: "text", Writable: false, Codec: "enum:enum_plan"},
		{Proto: "role", Column: "role", SQLType: "text", Writable: false, Codec: "enum:enum_role"},
	},
	AutoSet: []aippatch.AutoSetClause{
		{Column: "updated_at", SQLLiteral: "NOW()"},
	},
}
