import { LegalPage } from "@/components/legal-page";

export default function Terms() {
  return (
    <LegalPage title="Terms of Service">
      <p><em>Last updated: 2026-05-04</em></p>

      <p>
        These terms govern your use of Sabermatic, a service operated by Spanda,
        LLC ("we"). By using the service you agree to these terms.
      </p>

      <h2>The service</h2>
      <p>
        Sabermatic is a practice tool for system design interviews. It uses AI to
        conduct simulated interviews and provide feedback on your responses.
      </p>

      <h2>Your account</h2>
      <p>
        You need an account to use the service. You are responsible for keeping
        your account credentials secure. You must provide accurate information
        and notify us promptly of any unauthorized use.
      </p>

      <h2>Acceptable use</h2>
      <p>
        You agree to use the service in good faith for system design learning and
        practice. Casual or exploratory use of the chat outside the strict
        interview format is fine; the AI is tuned for system design and may not
        be helpful for unrelated topics.
      </p>
      <p>You agree not to:</p>
      <ul>
        <li>
          Use the service to cheat in a real interview, including by transmitting
          live interviewer questions or content to or from an interview in
          progress.
        </li>
        <li>
          Attempt to disrupt the service, scrape data, or reverse-engineer the AI
          prompts or models.
        </li>
        <li>
          Submit content that is illegal, infringing, or harmful, or use the
          service to harass others.
        </li>
      </ul>
      <p>
        We reserve the right to suspend or terminate accounts that violate these
        terms.
      </p>

      <h2>Pricing and subscriptions</h2>
      <p>
        Sabermatic offers paid plans (subscription and one-time minute packs).
        Current pricing is shown in the app.
      </p>
      <ul>
        <li>
          <strong>Subscriptions</strong> can be cancelled at any time.
          Cancellation stops future billing; access continues through the end of
          the billing period for which you have paid. We do not refund time
          already paid.
        </li>
        <li>
          <strong>Minute packs</strong> are non-refundable once purchased. Minutes
          do not expire while your account is active.
        </li>
      </ul>
      <p>Payments are processed by Stripe.</p>

      <h2>Your content</h2>
      <p>
        You retain ownership of the content you provide (your responses,
        recordings). By using the service, you grant us a non-exclusive license
        to process that content as needed to operate the service for you and to
        improve the product, as described in our Privacy Policy.
      </p>
      <p>
        The AI evaluations and coaching analyses generated by the service are
        made available to you for your use. The underlying prompts, models, and
        product are owned by us.
      </p>

      <h2>Disclaimers</h2>
      <p>
        The service is provided "as is." We do not guarantee that the AI's
        evaluations, coaching, or any output of the service is accurate,
        complete, or suitable for any particular purpose.{" "}
        <strong>
          Sabermatic does not provide career, hiring, or professional advice.
          Using Sabermatic does not guarantee any interview, job offer, or
          employment outcome.
        </strong>
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, Spanda, LLC is not liable for any
        indirect, incidental, consequential, or punitive damages arising from
        your use of the service. Our total liability for any claim is limited to
        the greater of (a) one hundred US dollars or (b) the amount you have paid
        us in the 12 months before the claim.
      </p>

      <h2>Termination</h2>
      <p>
        We reserve the right to suspend or terminate your account for violation
        of these terms. You may terminate your account at any time via Settings →
        Delete Account.
      </p>

      <h2>Changes to these terms</h2>
      <p>
        We may update these terms from time to time. If we make material changes,
        we will notify you by email. Continued use of the service after changes
        take effect means you accept the updated terms.
      </p>

      <h2>Governing law</h2>
      <p>
        These terms are governed by the laws of the State of Delaware, USA,
        without regard to conflict-of-law rules. Any dispute will be resolved in
        the state or federal courts located in Delaware.
      </p>

      <h2>Contact</h2>
      <p>
        Spanda, LLC
        <br />
        <a href="mailto:brian@spanda.llc">brian@spanda.llc</a>
      </p>
    </LegalPage>
  );
}
