// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: drill/v1/billing.proto

package drillv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/btc/drill/internal/pb/drill/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BillingServiceName is the fully-qualified name of the BillingService service.
	BillingServiceName = "drill.v1.BillingService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BillingServiceCheckoutProcedure is the fully-qualified name of the BillingService's Checkout RPC.
	BillingServiceCheckoutProcedure = "/drill.v1.BillingService/Checkout"
	// BillingServicePortalProcedure is the fully-qualified name of the BillingService's Portal RPC.
	BillingServicePortalProcedure = "/drill.v1.BillingService/Portal"
)

// BillingServiceClient is a client for the drill.v1.BillingService service.
type BillingServiceClient interface {
	Checkout(context.Context, *connect.Request[v1.CheckoutRequest]) (*connect.Response[v1.CheckoutResponse], error)
	Portal(context.Context, *connect.Request[v1.PortalRequest]) (*connect.Response[v1.PortalResponse], error)
}

// NewBillingServiceClient constructs a client for the drill.v1.BillingService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBillingServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BillingServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	billingServiceMethods := v1.File_drill_v1_billing_proto.Services().ByName("BillingService").Methods()
	return &billingServiceClient{
		checkout: connect.NewClient[v1.CheckoutRequest, v1.CheckoutResponse](
			httpClient,
			baseURL+BillingServiceCheckoutProcedure,
			connect.WithSchema(billingServiceMethods.ByName("Checkout")),
			connect.WithClientOptions(opts...),
		),
		portal: connect.NewClient[v1.PortalRequest, v1.PortalResponse](
			httpClient,
			baseURL+BillingServicePortalProcedure,
			connect.WithSchema(billingServiceMethods.ByName("Portal")),
			connect.WithClientOptions(opts...),
		),
	}
}

// billingServiceClient implements BillingServiceClient.
type billingServiceClient struct {
	checkout *connect.Client[v1.CheckoutRequest, v1.CheckoutResponse]
	portal   *connect.Client[v1.PortalRequest, v1.PortalResponse]
}

// Checkout calls drill.v1.BillingService.Checkout.
func (c *billingServiceClient) Checkout(ctx context.Context, req *connect.Request[v1.CheckoutRequest]) (*connect.Response[v1.CheckoutResponse], error) {
	return c.checkout.CallUnary(ctx, req)
}

// Portal calls drill.v1.BillingService.Portal.
func (c *billingServiceClient) Portal(ctx context.Context, req *connect.Request[v1.PortalRequest]) (*connect.Response[v1.PortalResponse], error) {
	return c.portal.CallUnary(ctx, req)
}

// BillingServiceHandler is an implementation of the drill.v1.BillingService service.
type BillingServiceHandler interface {
	Checkout(context.Context, *connect.Request[v1.CheckoutRequest]) (*connect.Response[v1.CheckoutResponse], error)
	Portal(context.Context, *connect.Request[v1.PortalRequest]) (*connect.Response[v1.PortalResponse], error)
}

// NewBillingServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBillingServiceHandler(svc BillingServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	billingServiceMethods := v1.File_drill_v1_billing_proto.Services().ByName("BillingService").Methods()
	billingServiceCheckoutHandler := connect.NewUnaryHandler(
		BillingServiceCheckoutProcedure,
		svc.Checkout,
		connect.WithSchema(billingServiceMethods.ByName("Checkout")),
		connect.WithHandlerOptions(opts...),
	)
	billingServicePortalHandler := connect.NewUnaryHandler(
		BillingServicePortalProcedure,
		svc.Portal,
		connect.WithSchema(billingServiceMethods.ByName("Portal")),
		connect.WithHandlerOptions(opts...),
	)
	return "/drill.v1.BillingService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BillingServiceCheckoutProcedure:
			billingServiceCheckoutHandler.ServeHTTP(w, r)
		case BillingServicePortalProcedure:
			billingServicePortalHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBillingServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBillingServiceHandler struct{}

func (UnimplementedBillingServiceHandler) Checkout(context.Context, *connect.Request[v1.CheckoutRequest]) (*connect.Response[v1.CheckoutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drill.v1.BillingService.Checkout is not implemented"))
}

func (UnimplementedBillingServiceHandler) Portal(context.Context, *connect.Request[v1.PortalRequest]) (*connect.Response[v1.PortalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drill.v1.BillingService.Portal is not implemented"))
}
