// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: drill/v1/coach.proto

package drillv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/btc/drill/internal/pb/drill/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CoachServiceName is the fully-qualified name of the CoachService service.
	CoachServiceName = "drill.v1.CoachService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CoachServiceGetCoachAnalysisProcedure is the fully-qualified name of the CoachService's
	// GetCoachAnalysis RPC.
	CoachServiceGetCoachAnalysisProcedure = "/drill.v1.CoachService/GetCoachAnalysis"
	// CoachServiceRequestCoachAnalysisProcedure is the fully-qualified name of the CoachService's
	// RequestCoachAnalysis RPC.
	CoachServiceRequestCoachAnalysisProcedure = "/drill.v1.CoachService/RequestCoachAnalysis"
)

// CoachServiceClient is a client for the drill.v1.CoachService service.
type CoachServiceClient interface {
	GetCoachAnalysis(context.Context, *connect.Request[v1.GetCoachAnalysisRequest]) (*connect.Response[v1.GetCoachAnalysisResponse], error)
	RequestCoachAnalysis(context.Context, *connect.Request[v1.RequestCoachAnalysisRequest]) (*connect.Response[v1.RequestCoachAnalysisResponse], error)
}

// NewCoachServiceClient constructs a client for the drill.v1.CoachService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCoachServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CoachServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	coachServiceMethods := v1.File_drill_v1_coach_proto.Services().ByName("CoachService").Methods()
	return &coachServiceClient{
		getCoachAnalysis: connect.NewClient[v1.GetCoachAnalysisRequest, v1.GetCoachAnalysisResponse](
			httpClient,
			baseURL+CoachServiceGetCoachAnalysisProcedure,
			connect.WithSchema(coachServiceMethods.ByName("GetCoachAnalysis")),
			connect.WithClientOptions(opts...),
		),
		requestCoachAnalysis: connect.NewClient[v1.RequestCoachAnalysisRequest, v1.RequestCoachAnalysisResponse](
			httpClient,
			baseURL+CoachServiceRequestCoachAnalysisProcedure,
			connect.WithSchema(coachServiceMethods.ByName("RequestCoachAnalysis")),
			connect.WithClientOptions(opts...),
		),
	}
}

// coachServiceClient implements CoachServiceClient.
type coachServiceClient struct {
	getCoachAnalysis     *connect.Client[v1.GetCoachAnalysisRequest, v1.GetCoachAnalysisResponse]
	requestCoachAnalysis *connect.Client[v1.RequestCoachAnalysisRequest, v1.RequestCoachAnalysisResponse]
}

// GetCoachAnalysis calls drill.v1.CoachService.GetCoachAnalysis.
func (c *coachServiceClient) GetCoachAnalysis(ctx context.Context, req *connect.Request[v1.GetCoachAnalysisRequest]) (*connect.Response[v1.GetCoachAnalysisResponse], error) {
	return c.getCoachAnalysis.CallUnary(ctx, req)
}

// RequestCoachAnalysis calls drill.v1.CoachService.RequestCoachAnalysis.
func (c *coachServiceClient) RequestCoachAnalysis(ctx context.Context, req *connect.Request[v1.RequestCoachAnalysisRequest]) (*connect.Response[v1.RequestCoachAnalysisResponse], error) {
	return c.requestCoachAnalysis.CallUnary(ctx, req)
}

// CoachServiceHandler is an implementation of the drill.v1.CoachService service.
type CoachServiceHandler interface {
	GetCoachAnalysis(context.Context, *connect.Request[v1.GetCoachAnalysisRequest]) (*connect.Response[v1.GetCoachAnalysisResponse], error)
	RequestCoachAnalysis(context.Context, *connect.Request[v1.RequestCoachAnalysisRequest]) (*connect.Response[v1.RequestCoachAnalysisResponse], error)
}

// NewCoachServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCoachServiceHandler(svc CoachServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	coachServiceMethods := v1.File_drill_v1_coach_proto.Services().ByName("CoachService").Methods()
	coachServiceGetCoachAnalysisHandler := connect.NewUnaryHandler(
		CoachServiceGetCoachAnalysisProcedure,
		svc.GetCoachAnalysis,
		connect.WithSchema(coachServiceMethods.ByName("GetCoachAnalysis")),
		connect.WithHandlerOptions(opts...),
	)
	coachServiceRequestCoachAnalysisHandler := connect.NewUnaryHandler(
		CoachServiceRequestCoachAnalysisProcedure,
		svc.RequestCoachAnalysis,
		connect.WithSchema(coachServiceMethods.ByName("RequestCoachAnalysis")),
		connect.WithHandlerOptions(opts...),
	)
	return "/drill.v1.CoachService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CoachServiceGetCoachAnalysisProcedure:
			coachServiceGetCoachAnalysisHandler.ServeHTTP(w, r)
		case CoachServiceRequestCoachAnalysisProcedure:
			coachServiceRequestCoachAnalysisHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCoachServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCoachServiceHandler struct{}

func (UnimplementedCoachServiceHandler) GetCoachAnalysis(context.Context, *connect.Request[v1.GetCoachAnalysisRequest]) (*connect.Response[v1.GetCoachAnalysisResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drill.v1.CoachService.GetCoachAnalysis is not implemented"))
}

func (UnimplementedCoachServiceHandler) RequestCoachAnalysis(context.Context, *connect.Request[v1.RequestCoachAnalysisRequest]) (*connect.Response[v1.RequestCoachAnalysisResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drill.v1.CoachService.RequestCoachAnalysis is not implemented"))
}
