// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: drill/v1/educator.proto

package drillv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/btc/drill/internal/pb/drill/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EducatorServiceName is the fully-qualified name of the EducatorService service.
	EducatorServiceName = "drill.v1.EducatorService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EducatorServiceGetEducatorAnalysisProcedure is the fully-qualified name of the EducatorService's
	// GetEducatorAnalysis RPC.
	EducatorServiceGetEducatorAnalysisProcedure = "/drill.v1.EducatorService/GetEducatorAnalysis"
	// EducatorServiceRequestEducatorAnalysisProcedure is the fully-qualified name of the
	// EducatorService's RequestEducatorAnalysis RPC.
	EducatorServiceRequestEducatorAnalysisProcedure = "/drill.v1.EducatorService/RequestEducatorAnalysis"
)

// EducatorServiceClient is a client for the drill.v1.EducatorService service.
type EducatorServiceClient interface {
	GetEducatorAnalysis(context.Context, *connect.Request[v1.GetEducatorAnalysisRequest]) (*connect.Response[v1.GetEducatorAnalysisResponse], error)
	RequestEducatorAnalysis(context.Context, *connect.Request[v1.RequestEducatorAnalysisRequest]) (*connect.Response[v1.RequestEducatorAnalysisResponse], error)
}

// NewEducatorServiceClient constructs a client for the drill.v1.EducatorService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEducatorServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EducatorServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	educatorServiceMethods := v1.File_drill_v1_educator_proto.Services().ByName("EducatorService").Methods()
	return &educatorServiceClient{
		getEducatorAnalysis: connect.NewClient[v1.GetEducatorAnalysisRequest, v1.GetEducatorAnalysisResponse](
			httpClient,
			baseURL+EducatorServiceGetEducatorAnalysisProcedure,
			connect.WithSchema(educatorServiceMethods.ByName("GetEducatorAnalysis")),
			connect.WithClientOptions(opts...),
		),
		requestEducatorAnalysis: connect.NewClient[v1.RequestEducatorAnalysisRequest, v1.RequestEducatorAnalysisResponse](
			httpClient,
			baseURL+EducatorServiceRequestEducatorAnalysisProcedure,
			connect.WithSchema(educatorServiceMethods.ByName("RequestEducatorAnalysis")),
			connect.WithClientOptions(opts...),
		),
	}
}

// educatorServiceClient implements EducatorServiceClient.
type educatorServiceClient struct {
	getEducatorAnalysis     *connect.Client[v1.GetEducatorAnalysisRequest, v1.GetEducatorAnalysisResponse]
	requestEducatorAnalysis *connect.Client[v1.RequestEducatorAnalysisRequest, v1.RequestEducatorAnalysisResponse]
}

// GetEducatorAnalysis calls drill.v1.EducatorService.GetEducatorAnalysis.
func (c *educatorServiceClient) GetEducatorAnalysis(ctx context.Context, req *connect.Request[v1.GetEducatorAnalysisRequest]) (*connect.Response[v1.GetEducatorAnalysisResponse], error) {
	return c.getEducatorAnalysis.CallUnary(ctx, req)
}

// RequestEducatorAnalysis calls drill.v1.EducatorService.RequestEducatorAnalysis.
func (c *educatorServiceClient) RequestEducatorAnalysis(ctx context.Context, req *connect.Request[v1.RequestEducatorAnalysisRequest]) (*connect.Response[v1.RequestEducatorAnalysisResponse], error) {
	return c.requestEducatorAnalysis.CallUnary(ctx, req)
}

// EducatorServiceHandler is an implementation of the drill.v1.EducatorService service.
type EducatorServiceHandler interface {
	GetEducatorAnalysis(context.Context, *connect.Request[v1.GetEducatorAnalysisRequest]) (*connect.Response[v1.GetEducatorAnalysisResponse], error)
	RequestEducatorAnalysis(context.Context, *connect.Request[v1.RequestEducatorAnalysisRequest]) (*connect.Response[v1.RequestEducatorAnalysisResponse], error)
}

// NewEducatorServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEducatorServiceHandler(svc EducatorServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	educatorServiceMethods := v1.File_drill_v1_educator_proto.Services().ByName("EducatorService").Methods()
	educatorServiceGetEducatorAnalysisHandler := connect.NewUnaryHandler(
		EducatorServiceGetEducatorAnalysisProcedure,
		svc.GetEducatorAnalysis,
		connect.WithSchema(educatorServiceMethods.ByName("GetEducatorAnalysis")),
		connect.WithHandlerOptions(opts...),
	)
	educatorServiceRequestEducatorAnalysisHandler := connect.NewUnaryHandler(
		EducatorServiceRequestEducatorAnalysisProcedure,
		svc.RequestEducatorAnalysis,
		connect.WithSchema(educatorServiceMethods.ByName("RequestEducatorAnalysis")),
		connect.WithHandlerOptions(opts...),
	)
	return "/drill.v1.EducatorService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EducatorServiceGetEducatorAnalysisProcedure:
			educatorServiceGetEducatorAnalysisHandler.ServeHTTP(w, r)
		case EducatorServiceRequestEducatorAnalysisProcedure:
			educatorServiceRequestEducatorAnalysisHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEducatorServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEducatorServiceHandler struct{}

func (UnimplementedEducatorServiceHandler) GetEducatorAnalysis(context.Context, *connect.Request[v1.GetEducatorAnalysisRequest]) (*connect.Response[v1.GetEducatorAnalysisResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drill.v1.EducatorService.GetEducatorAnalysis is not implemented"))
}

func (UnimplementedEducatorServiceHandler) RequestEducatorAnalysis(context.Context, *connect.Request[v1.RequestEducatorAnalysisRequest]) (*connect.Response[v1.RequestEducatorAnalysisResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drill.v1.EducatorService.RequestEducatorAnalysis is not implemented"))
}
