// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: drill/v1/question.proto

package drillv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/btc/drill/internal/pb/drill/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// QuestionServiceName is the fully-qualified name of the QuestionService service.
	QuestionServiceName = "drill.v1.QuestionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// QuestionServiceListQuestionsProcedure is the fully-qualified name of the QuestionService's
	// ListQuestions RPC.
	QuestionServiceListQuestionsProcedure = "/drill.v1.QuestionService/ListQuestions"
	// QuestionServiceCreateQuestionProcedure is the fully-qualified name of the QuestionService's
	// CreateQuestion RPC.
	QuestionServiceCreateQuestionProcedure = "/drill.v1.QuestionService/CreateQuestion"
)

// QuestionServiceClient is a client for the drill.v1.QuestionService service.
type QuestionServiceClient interface {
	ListQuestions(context.Context, *connect.Request[v1.ListQuestionsRequest]) (*connect.Response[v1.ListQuestionsResponse], error)
	CreateQuestion(context.Context, *connect.Request[v1.CreateQuestionRequest]) (*connect.Response[v1.Question], error)
}

// NewQuestionServiceClient constructs a client for the drill.v1.QuestionService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewQuestionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) QuestionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	questionServiceMethods := v1.File_drill_v1_question_proto.Services().ByName("QuestionService").Methods()
	return &questionServiceClient{
		listQuestions: connect.NewClient[v1.ListQuestionsRequest, v1.ListQuestionsResponse](
			httpClient,
			baseURL+QuestionServiceListQuestionsProcedure,
			connect.WithSchema(questionServiceMethods.ByName("ListQuestions")),
			connect.WithClientOptions(opts...),
		),
		createQuestion: connect.NewClient[v1.CreateQuestionRequest, v1.Question](
			httpClient,
			baseURL+QuestionServiceCreateQuestionProcedure,
			connect.WithSchema(questionServiceMethods.ByName("CreateQuestion")),
			connect.WithClientOptions(opts...),
		),
	}
}

// questionServiceClient implements QuestionServiceClient.
type questionServiceClient struct {
	listQuestions  *connect.Client[v1.ListQuestionsRequest, v1.ListQuestionsResponse]
	createQuestion *connect.Client[v1.CreateQuestionRequest, v1.Question]
}

// ListQuestions calls drill.v1.QuestionService.ListQuestions.
func (c *questionServiceClient) ListQuestions(ctx context.Context, req *connect.Request[v1.ListQuestionsRequest]) (*connect.Response[v1.ListQuestionsResponse], error) {
	return c.listQuestions.CallUnary(ctx, req)
}

// CreateQuestion calls drill.v1.QuestionService.CreateQuestion.
func (c *questionServiceClient) CreateQuestion(ctx context.Context, req *connect.Request[v1.CreateQuestionRequest]) (*connect.Response[v1.Question], error) {
	return c.createQuestion.CallUnary(ctx, req)
}

// QuestionServiceHandler is an implementation of the drill.v1.QuestionService service.
type QuestionServiceHandler interface {
	ListQuestions(context.Context, *connect.Request[v1.ListQuestionsRequest]) (*connect.Response[v1.ListQuestionsResponse], error)
	CreateQuestion(context.Context, *connect.Request[v1.CreateQuestionRequest]) (*connect.Response[v1.Question], error)
}

// NewQuestionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewQuestionServiceHandler(svc QuestionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	questionServiceMethods := v1.File_drill_v1_question_proto.Services().ByName("QuestionService").Methods()
	questionServiceListQuestionsHandler := connect.NewUnaryHandler(
		QuestionServiceListQuestionsProcedure,
		svc.ListQuestions,
		connect.WithSchema(questionServiceMethods.ByName("ListQuestions")),
		connect.WithHandlerOptions(opts...),
	)
	questionServiceCreateQuestionHandler := connect.NewUnaryHandler(
		QuestionServiceCreateQuestionProcedure,
		svc.CreateQuestion,
		connect.WithSchema(questionServiceMethods.ByName("CreateQuestion")),
		connect.WithHandlerOptions(opts...),
	)
	return "/drill.v1.QuestionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case QuestionServiceListQuestionsProcedure:
			questionServiceListQuestionsHandler.ServeHTTP(w, r)
		case QuestionServiceCreateQuestionProcedure:
			questionServiceCreateQuestionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedQuestionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedQuestionServiceHandler struct{}

func (UnimplementedQuestionServiceHandler) ListQuestions(context.Context, *connect.Request[v1.ListQuestionsRequest]) (*connect.Response[v1.ListQuestionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drill.v1.QuestionService.ListQuestions is not implemented"))
}

func (UnimplementedQuestionServiceHandler) CreateQuestion(context.Context, *connect.Request[v1.CreateQuestionRequest]) (*connect.Response[v1.Question], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drill.v1.QuestionService.CreateQuestion is not implemented"))
}
