// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: drill/v1/session.proto

package drillv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/btc/drill/internal/pb/drill/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SessionServiceName is the fully-qualified name of the SessionService service.
	SessionServiceName = "drill.v1.SessionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SessionServiceGetSessionProcedure is the fully-qualified name of the SessionService's GetSession
	// RPC.
	SessionServiceGetSessionProcedure = "/drill.v1.SessionService/GetSession"
	// SessionServiceListSessionsProcedure is the fully-qualified name of the SessionService's
	// ListSessions RPC.
	SessionServiceListSessionsProcedure = "/drill.v1.SessionService/ListSessions"
	// SessionServiceCreateSessionProcedure is the fully-qualified name of the SessionService's
	// CreateSession RPC.
	SessionServiceCreateSessionProcedure = "/drill.v1.SessionService/CreateSession"
	// SessionServiceArchiveSessionsProcedure is the fully-qualified name of the SessionService's
	// ArchiveSessions RPC.
	SessionServiceArchiveSessionsProcedure = "/drill.v1.SessionService/ArchiveSessions"
	// SessionServiceGetTranscriptProcedure is the fully-qualified name of the SessionService's
	// GetTranscript RPC.
	SessionServiceGetTranscriptProcedure = "/drill.v1.SessionService/GetTranscript"
)

// SessionServiceClient is a client for the drill.v1.SessionService service.
type SessionServiceClient interface {
	// AIP-131: Get a single session by ID.
	GetSession(context.Context, *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error)
	// AIP-132: List sessions for the authenticated user.
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error)
	// AIP-133: Create a new interview session.
	CreateSession(context.Context, *connect.Request[v1.CreateSessionRequest]) (*connect.Response[v1.CreateSessionResponse], error)
	// AIP-136: Custom method — bulk archive/unarchive sessions.
	ArchiveSessions(context.Context, *connect.Request[v1.ArchiveSessionsRequest]) (*connect.Response[v1.ArchiveSessionsResponse], error)
	// AIP-131: Get the transcript (messages) for a session.
	GetTranscript(context.Context, *connect.Request[v1.GetTranscriptRequest]) (*connect.Response[v1.GetTranscriptResponse], error)
}

// NewSessionServiceClient constructs a client for the drill.v1.SessionService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSessionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SessionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sessionServiceMethods := v1.File_drill_v1_session_proto.Services().ByName("SessionService").Methods()
	return &sessionServiceClient{
		getSession: connect.NewClient[v1.GetSessionRequest, v1.GetSessionResponse](
			httpClient,
			baseURL+SessionServiceGetSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("GetSession")),
			connect.WithClientOptions(opts...),
		),
		listSessions: connect.NewClient[v1.ListSessionsRequest, v1.ListSessionsResponse](
			httpClient,
			baseURL+SessionServiceListSessionsProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("ListSessions")),
			connect.WithClientOptions(opts...),
		),
		createSession: connect.NewClient[v1.CreateSessionRequest, v1.CreateSessionResponse](
			httpClient,
			baseURL+SessionServiceCreateSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("CreateSession")),
			connect.WithClientOptions(opts...),
		),
		archiveSessions: connect.NewClient[v1.ArchiveSessionsRequest, v1.ArchiveSessionsResponse](
			httpClient,
			baseURL+SessionServiceArchiveSessionsProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("ArchiveSessions")),
			connect.WithClientOptions(opts...),
		),
		getTranscript: connect.NewClient[v1.GetTranscriptRequest, v1.GetTranscriptResponse](
			httpClient,
			baseURL+SessionServiceGetTranscriptProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("GetTranscript")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sessionServiceClient implements SessionServiceClient.
type sessionServiceClient struct {
	getSession      *connect.Client[v1.GetSessionRequest, v1.GetSessionResponse]
	listSessions    *connect.Client[v1.ListSessionsRequest, v1.ListSessionsResponse]
	createSession   *connect.Client[v1.CreateSessionRequest, v1.CreateSessionResponse]
	archiveSessions *connect.Client[v1.ArchiveSessionsRequest, v1.ArchiveSessionsResponse]
	getTranscript   *connect.Client[v1.GetTranscriptRequest, v1.GetTranscriptResponse]
}

// GetSession calls drill.v1.SessionService.GetSession.
func (c *sessionServiceClient) GetSession(ctx context.Context, req *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error) {
	return c.getSession.CallUnary(ctx, req)
}

// ListSessions calls drill.v1.SessionService.ListSessions.
func (c *sessionServiceClient) ListSessions(ctx context.Context, req *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error) {
	return c.listSessions.CallUnary(ctx, req)
}

// CreateSession calls drill.v1.SessionService.CreateSession.
func (c *sessionServiceClient) CreateSession(ctx context.Context, req *connect.Request[v1.CreateSessionRequest]) (*connect.Response[v1.CreateSessionResponse], error) {
	return c.createSession.CallUnary(ctx, req)
}

// ArchiveSessions calls drill.v1.SessionService.ArchiveSessions.
func (c *sessionServiceClient) ArchiveSessions(ctx context.Context, req *connect.Request[v1.ArchiveSessionsRequest]) (*connect.Response[v1.ArchiveSessionsResponse], error) {
	return c.archiveSessions.CallUnary(ctx, req)
}

// GetTranscript calls drill.v1.SessionService.GetTranscript.
func (c *sessionServiceClient) GetTranscript(ctx context.Context, req *connect.Request[v1.GetTranscriptRequest]) (*connect.Response[v1.GetTranscriptResponse], error) {
	return c.getTranscript.CallUnary(ctx, req)
}

// SessionServiceHandler is an implementation of the drill.v1.SessionService service.
type SessionServiceHandler interface {
	// AIP-131: Get a single session by ID.
	GetSession(context.Context, *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error)
	// AIP-132: List sessions for the authenticated user.
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error)
	// AIP-133: Create a new interview session.
	CreateSession(context.Context, *connect.Request[v1.CreateSessionRequest]) (*connect.Response[v1.CreateSessionResponse], error)
	// AIP-136: Custom method — bulk archive/unarchive sessions.
	ArchiveSessions(context.Context, *connect.Request[v1.ArchiveSessionsRequest]) (*connect.Response[v1.ArchiveSessionsResponse], error)
	// AIP-131: Get the transcript (messages) for a session.
	GetTranscript(context.Context, *connect.Request[v1.GetTranscriptRequest]) (*connect.Response[v1.GetTranscriptResponse], error)
}

// NewSessionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSessionServiceHandler(svc SessionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sessionServiceMethods := v1.File_drill_v1_session_proto.Services().ByName("SessionService").Methods()
	sessionServiceGetSessionHandler := connect.NewUnaryHandler(
		SessionServiceGetSessionProcedure,
		svc.GetSession,
		connect.WithSchema(sessionServiceMethods.ByName("GetSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceListSessionsHandler := connect.NewUnaryHandler(
		SessionServiceListSessionsProcedure,
		svc.ListSessions,
		connect.WithSchema(sessionServiceMethods.ByName("ListSessions")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceCreateSessionHandler := connect.NewUnaryHandler(
		SessionServiceCreateSessionProcedure,
		svc.CreateSession,
		connect.WithSchema(sessionServiceMethods.ByName("CreateSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceArchiveSessionsHandler := connect.NewUnaryHandler(
		SessionServiceArchiveSessionsProcedure,
		svc.ArchiveSessions,
		connect.WithSchema(sessionServiceMethods.ByName("ArchiveSessions")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceGetTranscriptHandler := connect.NewUnaryHandler(
		SessionServiceGetTranscriptProcedure,
		svc.GetTranscript,
		connect.WithSchema(sessionServiceMethods.ByName("GetTranscript")),
		connect.WithHandlerOptions(opts...),
	)
	return "/drill.v1.SessionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SessionServiceGetSessionProcedure:
			sessionServiceGetSessionHandler.ServeHTTP(w, r)
		case SessionServiceListSessionsProcedure:
			sessionServiceListSessionsHandler.ServeHTTP(w, r)
		case SessionServiceCreateSessionProcedure:
			sessionServiceCreateSessionHandler.ServeHTTP(w, r)
		case SessionServiceArchiveSessionsProcedure:
			sessionServiceArchiveSessionsHandler.ServeHTTP(w, r)
		case SessionServiceGetTranscriptProcedure:
			sessionServiceGetTranscriptHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSessionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSessionServiceHandler struct{}

func (UnimplementedSessionServiceHandler) GetSession(context.Context, *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drill.v1.SessionService.GetSession is not implemented"))
}

func (UnimplementedSessionServiceHandler) ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drill.v1.SessionService.ListSessions is not implemented"))
}

func (UnimplementedSessionServiceHandler) CreateSession(context.Context, *connect.Request[v1.CreateSessionRequest]) (*connect.Response[v1.CreateSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drill.v1.SessionService.CreateSession is not implemented"))
}

func (UnimplementedSessionServiceHandler) ArchiveSessions(context.Context, *connect.Request[v1.ArchiveSessionsRequest]) (*connect.Response[v1.ArchiveSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drill.v1.SessionService.ArchiveSessions is not implemented"))
}

func (UnimplementedSessionServiceHandler) GetTranscript(context.Context, *connect.Request[v1.GetTranscriptRequest]) (*connect.Response[v1.GetTranscriptResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drill.v1.SessionService.GetTranscript is not implemented"))
}
