package coach

import (
	"encoding/json"
	"fmt"

	"github.com/anthropics/anthropic-sdk-go"
)

// CoachResult holds the parsed coaching analysis ready for persistence.
type CoachResult struct {
	Narrative           string
	WeakestDimension    string
	ImprovingDimensions []string
	TopicGaps           []string
	GeneratedQuestion   *GeneratedQuestion
}

// GeneratedQuestion holds an optional custom question generated by the coach.
type GeneratedQuestion struct {
	Title      string
	Prompt     string
	Difficulty string
	Tags       []string
}

// ToolSchema returns the anthropic.ToolParam for the submit_analysis tool.
func ToolSchema() anthropic.ToolParam {
	return anthropic.ToolParam{
		Name:        "submit_analysis",
		Description: anthropic.String("Submit the strategic coaching analysis based on the candidate's interview history."),
		InputSchema: anthropic.ToolInputSchemaParam{
			Properties: map[string]any{
				"narrative": map[string]any{
					"type":        "string",
					"description": "Strategic coaching narrative including thinking patterns and metacognitive coaching.",
				},
				"weakest_dimension": map[string]any{
					"type":        "string",
					"description": "The evaluation dimension where the candidate scores lowest.",
				},
				"improving_dimensions": map[string]any{
					"type":        "array",
					"items":       map[string]any{"type": "string"},
					"description": "Dimensions showing improvement over time.",
				},
				"topic_gaps": map[string]any{
					"type":        "array",
					"items":       map[string]any{"type": "string"},
					"description": "System design topics the candidate hasn't practiced yet.",
				},
				"generated_question": map[string]any{
					"type":        []any{"object", "null"},
					"description": "An optional custom question targeting the candidate's weaknesses.",
					"properties": map[string]any{
						"title":      map[string]any{"type": "string", "description": "Short title for the generated question."},
						"prompt":     map[string]any{"type": "string", "description": "Full interview-style prompt for the question."},
						"difficulty": map[string]any{"type": "string", "enum": []string{"medium", "hard"}, "description": "Difficulty level."},
						"tags":       map[string]any{"type": "array", "items": map[string]any{"type": "string"}, "description": "Topic tags."},
					},
				},
			},
			Required: []string{"narrative"},
		},
	}
}

// rawToolInput is an intermediate struct for JSON unmarshaling.
type rawToolInput struct {
	Narrative           string          `json:"narrative"`
	WeakestDimension    string          `json:"weakest_dimension"`
	ImprovingDimensions []string        `json:"improving_dimensions"`
	TopicGaps           []string        `json:"topic_gaps"`
	GeneratedQuestion   *rawGenQuestion `json:"generated_question"`
}

type rawGenQuestion struct {
	Title      string   `json:"title"`
	Prompt     string   `json:"prompt"`
	Difficulty string   `json:"difficulty"`
	Tags       []string `json:"tags"`
}

// Parse unmarshals tool input JSON into a CoachResult.
// Returns an error if narrative is empty or generated_question has an invalid difficulty.
func Parse(raw json.RawMessage) (*CoachResult, error) {
	var input rawToolInput
	if err := json.Unmarshal(raw, &input); err != nil {
		return nil, fmt.Errorf("coach: unmarshal tool input: %w", err)
	}
	if input.Narrative == "" {
		return nil, fmt.Errorf("coach: narrative is empty")
	}
	if input.ImprovingDimensions == nil {
		input.ImprovingDimensions = []string{}
	}
	if input.TopicGaps == nil {
		input.TopicGaps = []string{}
	}
	result := &CoachResult{
		Narrative:           input.Narrative,
		WeakestDimension:    input.WeakestDimension,
		ImprovingDimensions: input.ImprovingDimensions,
		TopicGaps:           input.TopicGaps,
	}
	if input.GeneratedQuestion != nil && input.GeneratedQuestion.Title != "" {
		gq := input.GeneratedQuestion
		if gq.Prompt == "" {
			return nil, fmt.Errorf("coach: generated question prompt is empty")
		}
		if gq.Difficulty != "medium" && gq.Difficulty != "hard" {
			return nil, fmt.Errorf("coach: generated question difficulty must be medium or hard, got %q", gq.Difficulty)
		}
		if gq.Tags == nil {
			gq.Tags = []string{}
		}
		result.GeneratedQuestion = &GeneratedQuestion{
			Title:      gq.Title,
			Prompt:     gq.Prompt,
			Difficulty: gq.Difficulty,
			Tags:       gq.Tags,
		}
	}
	return result, nil
}
