// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: advisory_locks.sql

package db

import (
	"context"
)

const pGAdvisoryUnlock = `-- name: PGAdvisoryUnlock :one
SELECT pg_advisory_unlock($1)
`

func (q *Queries) PGAdvisoryUnlock(ctx context.Context, key int64) (bool, error) {
	row := q.db.QueryRow(ctx, pGAdvisoryUnlock, key)
	var pg_advisory_unlock bool
	err := row.Scan(&pg_advisory_unlock)
	return pg_advisory_unlock, err
}

const pGTryAdvisoryLock = `-- name: PGTryAdvisoryLock :one
SELECT pg_try_advisory_lock($1)
`

func (q *Queries) PGTryAdvisoryLock(ctx context.Context, key int64) (bool, error) {
	row := q.db.QueryRow(ctx, pGTryAdvisoryLock, key)
	var pg_try_advisory_lock bool
	err := row.Scan(&pg_try_advisory_lock)
	return pg_try_advisory_lock, err
}
