// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: auth_sessions.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO auth_sessions (user_id, token_hash, expires_at, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, expires_at, last_active, ip_address, user_agent, created_at
`

type CreateAuthSessionParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	TokenHash string      `json:"token_hash"`
	ExpiresAt time.Time   `json:"expires_at"`
	IpAddress *netip.Addr `json:"ip_address"`
	UserAgent pgtype.Text `json:"user_agent"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastActive,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAuthSession = `-- name: DeleteAuthSession :exec
DELETE FROM auth_sessions WHERE id = $1
`

func (q *Queries) DeleteAuthSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAuthSession, id)
	return err
}

const deleteUserAuthSessions = `-- name: DeleteUserAuthSessions :exec
DELETE FROM auth_sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserAuthSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserAuthSessions, userID)
	return err
}

const getAuthSessionByToken = `-- name: GetAuthSessionByToken :one
SELECT s.id, s.user_id, s.token_hash, s.expires_at, s.last_active, s.ip_address, s.user_agent, s.created_at, u.email, u.display_name, u.role, u.plan, u.email_verified
FROM auth_sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.expires_at > NOW()
  AND u.deleted_at IS NULL
`

type GetAuthSessionByTokenRow struct {
	ID            uuid.UUID   `json:"id"`
	UserID        uuid.UUID   `json:"user_id"`
	TokenHash     string      `json:"token_hash"`
	ExpiresAt     time.Time   `json:"expires_at"`
	LastActive    time.Time   `json:"last_active"`
	IpAddress     *netip.Addr `json:"ip_address"`
	UserAgent     pgtype.Text `json:"user_agent"`
	CreatedAt     time.Time   `json:"created_at"`
	Email         string      `json:"email"`
	DisplayName   string      `json:"display_name"`
	Role          string      `json:"role"`
	Plan          string      `json:"plan"`
	EmailVerified bool        `json:"email_verified"`
}

func (q *Queries) GetAuthSessionByToken(ctx context.Context, tokenHash string) (GetAuthSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getAuthSessionByToken, tokenHash)
	var i GetAuthSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastActive,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Plan,
		&i.EmailVerified,
	)
	return i, err
}

const touchAuthSession = `-- name: TouchAuthSession :exec
UPDATE auth_sessions SET last_active = NOW()
WHERE id = $1
`

func (q *Queries) TouchAuthSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAuthSession, id)
	return err
}
