// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: coach_analyses.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestCoachAnalysis = `-- name: GetLatestCoachAnalysis :one
SELECT id, user_id, narrative, weakest_dimension,
       improving_dimensions, topic_gaps,
       suggested_question_id, sessions_analyzed, created_at, summary
FROM coach_analyses
WHERE user_id = $1
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestCoachAnalysis(ctx context.Context, userID uuid.UUID) (CoachAnalysis, error) {
	row := q.db.QueryRow(ctx, getLatestCoachAnalysis, userID)
	var i CoachAnalysis
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Narrative,
		&i.WeakestDimension,
		&i.ImprovingDimensions,
		&i.TopicGaps,
		&i.SuggestedQuestionID,
		&i.SessionsAnalyzed,
		&i.CreatedAt,
		&i.Summary,
	)
	return i, err
}

const insertCoachAnalysis = `-- name: InsertCoachAnalysis :one
INSERT INTO coach_analyses (
    user_id, narrative, summary, weakest_dimension,
    improving_dimensions, topic_gaps,
    suggested_question_id, sessions_analyzed
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertCoachAnalysisParams struct {
	UserID              uuid.UUID   `json:"user_id"`
	Narrative           string      `json:"narrative"`
	Summary             pgtype.Text `json:"summary"`
	WeakestDimension    pgtype.Text `json:"weakest_dimension"`
	ImprovingDimensions []string    `json:"improving_dimensions"`
	TopicGaps           []string    `json:"topic_gaps"`
	SuggestedQuestionID pgtype.UUID `json:"suggested_question_id"`
	SessionsAnalyzed    []uuid.UUID `json:"sessions_analyzed"`
}

func (q *Queries) InsertCoachAnalysis(ctx context.Context, arg InsertCoachAnalysisParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertCoachAnalysis,
		arg.UserID,
		arg.Narrative,
		arg.Summary,
		arg.WeakestDimension,
		arg.ImprovingDimensions,
		arg.TopicGaps,
		arg.SuggestedQuestionID,
		arg.SessionsAnalyzed,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
