// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: educator_analyses.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getEducatorAnalysisBySession = `-- name: GetEducatorAnalysisBySession :one
SELECT id, session_id, status, model_answer, gap_deep_dives, created_at
FROM educator_analyses WHERE session_id = $1
`

func (q *Queries) GetEducatorAnalysisBySession(ctx context.Context, sessionID uuid.UUID) (EducatorAnalysis, error) {
	row := q.db.QueryRow(ctx, getEducatorAnalysisBySession, sessionID)
	var i EducatorAnalysis
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Status,
		&i.ModelAnswer,
		&i.GapDeepDives,
		&i.CreatedAt,
	)
	return i, err
}

const insertEducatorAnalysis = `-- name: InsertEducatorAnalysis :one
INSERT INTO educator_analyses (session_id)
VALUES ($1)
RETURNING id
`

func (q *Queries) InsertEducatorAnalysis(ctx context.Context, sessionID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertEducatorAnalysis, sessionID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateEducatorAnalysisContent = `-- name: UpdateEducatorAnalysisContent :exec
UPDATE educator_analyses
SET model_answer = $2, gap_deep_dives = $3, status = 'completed'
WHERE id = $1
`

type UpdateEducatorAnalysisContentParams struct {
	ID           uuid.UUID   `json:"id"`
	ModelAnswer  pgtype.Text `json:"model_answer"`
	GapDeepDives pgtype.Text `json:"gap_deep_dives"`
}

func (q *Queries) UpdateEducatorAnalysisContent(ctx context.Context, arg UpdateEducatorAnalysisContentParams) error {
	_, err := q.db.Exec(ctx, updateEducatorAnalysisContent, arg.ID, arg.ModelAnswer, arg.GapDeepDives)
	return err
}

const updateEducatorAnalysisStatus = `-- name: UpdateEducatorAnalysisStatus :exec
UPDATE educator_analyses SET status = $2 WHERE id = $1
`

type UpdateEducatorAnalysisStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateEducatorAnalysisStatus(ctx context.Context, arg UpdateEducatorAnalysisStatusParams) error {
	_, err := q.db.Exec(ctx, updateEducatorAnalysisStatus, arg.ID, arg.Status)
	return err
}
