// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: evaluations.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getAnnotationsByEvaluation = `-- name: GetAnnotationsByEvaluation :many
SELECT a.id, a.evaluation_id, a.message_id, a.annotation_type, a.content,
       m.seq AS message_seq
FROM annotations a
JOIN messages m ON m.id = a.message_id
WHERE a.evaluation_id = $1
ORDER BY m.seq, a.annotation_type
`

type GetAnnotationsByEvaluationRow struct {
	ID             uuid.UUID `json:"id"`
	EvaluationID   uuid.UUID `json:"evaluation_id"`
	MessageID      uuid.UUID `json:"message_id"`
	AnnotationType string    `json:"annotation_type"`
	Content        string    `json:"content"`
	MessageSeq     int32     `json:"message_seq"`
}

func (q *Queries) GetAnnotationsByEvaluation(ctx context.Context, evaluationID uuid.UUID) ([]GetAnnotationsByEvaluationRow, error) {
	rows, err := q.db.Query(ctx, getAnnotationsByEvaluation, evaluationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAnnotationsByEvaluationRow
	for rows.Next() {
		var i GetAnnotationsByEvaluationRow
		if err := rows.Scan(
			&i.ID,
			&i.EvaluationID,
			&i.MessageID,
			&i.AnnotationType,
			&i.Content,
			&i.MessageSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvaluationBySession = `-- name: GetEvaluationBySession :one
SELECT id, session_id, score_requirements, score_architecture,
       score_deep_dive, score_scalability, score_communication,
       score_overall, strengths, gaps, advice, created_at
FROM evaluations WHERE session_id = $1
`

func (q *Queries) GetEvaluationBySession(ctx context.Context, sessionID uuid.UUID) (Evaluation, error) {
	row := q.db.QueryRow(ctx, getEvaluationBySession, sessionID)
	var i Evaluation
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ScoreRequirements,
		&i.ScoreArchitecture,
		&i.ScoreDeepDive,
		&i.ScoreScalability,
		&i.ScoreCommunication,
		&i.ScoreOverall,
		&i.Strengths,
		&i.Gaps,
		&i.Advice,
		&i.CreatedAt,
	)
	return i, err
}

const getEvaluationsBySessionIDs = `-- name: GetEvaluationsBySessionIDs :many
SELECT id, session_id, score_requirements, score_architecture,
       score_deep_dive, score_scalability, score_communication,
       score_overall, strengths, gaps, advice, created_at
FROM evaluations WHERE session_id = ANY($1::uuid[])
`

func (q *Queries) GetEvaluationsBySessionIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Evaluation, error) {
	rows, err := q.db.Query(ctx, getEvaluationsBySessionIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Evaluation
	for rows.Next() {
		var i Evaluation
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ScoreRequirements,
			&i.ScoreArchitecture,
			&i.ScoreDeepDive,
			&i.ScoreScalability,
			&i.ScoreCommunication,
			&i.ScoreOverall,
			&i.Strengths,
			&i.Gaps,
			&i.Advice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAnnotation = `-- name: InsertAnnotation :exec
INSERT INTO annotations (evaluation_id, message_id, annotation_type, content)
VALUES ($1, $2, $3, $4)
`

type InsertAnnotationParams struct {
	EvaluationID   uuid.UUID `json:"evaluation_id"`
	MessageID      uuid.UUID `json:"message_id"`
	AnnotationType string    `json:"annotation_type"`
	Content        string    `json:"content"`
}

func (q *Queries) InsertAnnotation(ctx context.Context, arg InsertAnnotationParams) error {
	_, err := q.db.Exec(ctx, insertAnnotation,
		arg.EvaluationID,
		arg.MessageID,
		arg.AnnotationType,
		arg.Content,
	)
	return err
}

const insertEvaluation = `-- name: InsertEvaluation :one
INSERT INTO evaluations (
    session_id, score_requirements, score_architecture,
    score_deep_dive, score_scalability, score_communication,
    score_overall, strengths, gaps, advice
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id
`

type InsertEvaluationParams struct {
	SessionID          uuid.UUID `json:"session_id"`
	ScoreRequirements  int32     `json:"score_requirements"`
	ScoreArchitecture  int32     `json:"score_architecture"`
	ScoreDeepDive      int32     `json:"score_deep_dive"`
	ScoreScalability   int32     `json:"score_scalability"`
	ScoreCommunication int32     `json:"score_communication"`
	ScoreOverall       int32     `json:"score_overall"`
	Strengths          []byte    `json:"strengths"`
	Gaps               []byte    `json:"gaps"`
	Advice             string    `json:"advice"`
}

func (q *Queries) InsertEvaluation(ctx context.Context, arg InsertEvaluationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertEvaluation,
		arg.SessionID,
		arg.ScoreRequirements,
		arg.ScoreArchitecture,
		arg.ScoreDeepDive,
		arg.ScoreScalability,
		arg.ScoreCommunication,
		arg.ScoreOverall,
		arg.Strengths,
		arg.Gaps,
		arg.Advice,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
