// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: grants.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGrantFromStripe = `-- name: CreateGrantFromStripe :one
INSERT INTO grants (user_id, source, stripe_event_id, initial_minutes, remaining_minutes, expires_at)
VALUES ($1, $2, $3, $4, $4, $5)
ON CONFLICT (stripe_event_id) DO NOTHING
RETURNING id, user_id, source, stripe_event_id, initial_minutes, remaining_minutes, expires_at, created_at
`

type CreateGrantFromStripeParams struct {
	UserID         uuid.UUID          `json:"user_id"`
	Source         string             `json:"source"`
	StripeEventID  pgtype.Text        `json:"stripe_event_id"`
	InitialMinutes int32              `json:"initial_minutes"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateGrantFromStripe(ctx context.Context, arg CreateGrantFromStripeParams) (Grant, error) {
	row := q.db.QueryRow(ctx, createGrantFromStripe,
		arg.UserID,
		arg.Source,
		arg.StripeEventID,
		arg.InitialMinutes,
		arg.ExpiresAt,
	)
	var i Grant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.StripeEventID,
		&i.InitialMinutes,
		&i.RemainingMinutes,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const ensureFreeGrant = `-- name: EnsureFreeGrant :exec
WITH new_grant AS (
  INSERT INTO grants (user_id, source, initial_minutes, remaining_minutes, expires_at)
  VALUES ($1, 'free_grant', $2, $2, $3)
  ON CONFLICT (user_id, date_trunc('month', timezone('UTC', created_at))) WHERE source = 'free_grant'
  DO NOTHING
  RETURNING id, user_id, initial_minutes
)
INSERT INTO ledger_entries (user_id, grant_id, amount, reason)
SELECT user_id, id, initial_minutes, 'free_monthly'
FROM new_grant
`

type EnsureFreeGrantParams struct {
	UserID         uuid.UUID          `json:"user_id"`
	InitialMinutes int32              `json:"initial_minutes"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

// Creates the monthly free grant + ledger entry atomically. If the grant
// already exists (ON CONFLICT), both the INSERT and the ledger SELECT
// produce zero rows — a no-op.
func (q *Queries) EnsureFreeGrant(ctx context.Context, arg EnsureFreeGrantParams) error {
	_, err := q.db.Exec(ctx, ensureFreeGrant, arg.UserID, arg.InitialMinutes, arg.ExpiresAt)
	return err
}

const fullRefundSessionMinutes = `-- name: FullRefundSessionMinutes :many
WITH RECURSIVE
  refund_amount AS (
    SELECT $4::int AS total
  ),
  reserves AS (
    SELECT grant_id, -amount AS debit,
           ROW_NUMBER() OVER (ORDER BY created_at DESC) AS rn
    FROM ledger_entries
    WHERE session_id = $3 AND reason = 'session_reserve'
  ),
  distributed AS (
    SELECT r.grant_id, r.debit,
           LEAST(r.debit, ra.total) AS credit,
           ra.total - LEAST(r.debit, ra.total) AS remaining,
           r.rn
    FROM reserves r, refund_amount ra
    WHERE r.rn = 1

    UNION ALL

    SELECT r.grant_id, r.debit,
           LEAST(r.debit, d.remaining) AS credit,
           d.remaining - LEAST(r.debit, d.remaining) AS remaining,
           r.rn
    FROM reserves r
    JOIN distributed d ON r.rn = d.rn + 1
    WHERE d.remaining > 0
  ),
  apply_credits AS (
    UPDATE grants g
    SET remaining_minutes = remaining_minutes + d.credit
    FROM distributed d
    WHERE g.id = d.grant_id AND d.credit > 0
      AND g.remaining_minutes + d.credit <= g.initial_minutes
    RETURNING g.id AS grant_id, d.credit
  )
INSERT INTO ledger_entries (user_id, grant_id, amount, reason, session_id)
SELECT $1, ac.grant_id, ac.credit, $2, $3
FROM apply_credits ac
RETURNING grant_id, amount
`

type FullRefundSessionMinutesParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	Reason    string      `json:"reason"`
	SessionID pgtype.UUID `json:"session_id"`
	Minutes   int32       `json:"minutes"`
}

type FullRefundSessionMinutesRow struct {
	GrantID uuid.UUID `json:"grant_id"`
	Amount  int32     `json:"amount"`
}

// Refunds exactly @minutes back to the grants that were originally debited
// for this session. Used by FailSession (platform error → full refund).
func (q *Queries) FullRefundSessionMinutes(ctx context.Context, arg FullRefundSessionMinutesParams) ([]FullRefundSessionMinutesRow, error) {
	rows, err := q.db.Query(ctx, fullRefundSessionMinutes,
		arg.UserID,
		arg.Reason,
		arg.SessionID,
		arg.Minutes,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FullRefundSessionMinutesRow
	for rows.Next() {
		var i FullRefundSessionMinutesRow
		if err := rows.Scan(&i.GrantID, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBillingSnapshot = `-- name: GetBillingSnapshot :one
SELECT u.plan, u.free_full_educators_used,
  COALESCE(SUM(g.remaining_minutes) FILTER (
    WHERE g.remaining_minutes > 0 AND (g.expires_at IS NULL OR g.expires_at > NOW())
  ), 0)::int AS total_balance,
  COALESCE(SUM(g.remaining_minutes) FILTER (
    WHERE g.remaining_minutes > 0 AND g.source != 'free_grant'
    AND (g.expires_at IS NULL OR g.expires_at > NOW())
  ), 0)::int AS paid_balance
FROM users u
LEFT JOIN grants g ON g.user_id = u.id
WHERE u.id = $1
GROUP BY u.id, u.plan, u.free_full_educators_used
`

type GetBillingSnapshotRow struct {
	Plan                  string `json:"plan"`
	FreeFullEducatorsUsed int32  `json:"free_full_educators_used"`
	TotalBalance          int32  `json:"total_balance"`
	PaidBalance           int32  `json:"paid_balance"`
}

// Single query to fetch all billing state needed for entitlement checks.
// Fetch inside the caller's transaction to avoid TOCTOU.
func (q *Queries) GetBillingSnapshot(ctx context.Context, id uuid.UUID) (GetBillingSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getBillingSnapshot, id)
	var i GetBillingSnapshotRow
	err := row.Scan(
		&i.Plan,
		&i.FreeFullEducatorsUsed,
		&i.TotalBalance,
		&i.PaidBalance,
	)
	return i, err
}

const getFreeGrantForMonth = `-- name: GetFreeGrantForMonth :one
SELECT id FROM grants
WHERE user_id = $1
  AND source = 'free_grant'
  AND expires_at = $2
LIMIT 1
`

type GetFreeGrantForMonthParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetFreeGrantForMonth(ctx context.Context, arg GetFreeGrantForMonthParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getFreeGrantForMonth, arg.UserID, arg.ExpiresAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getRecentLedgerEntries = `-- name: GetRecentLedgerEntries :many
SELECT amount, reason, session_id, created_at
FROM ledger_entries
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetRecentLedgerEntriesParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

type GetRecentLedgerEntriesRow struct {
	Amount    int32       `json:"amount"`
	Reason    string      `json:"reason"`
	SessionID pgtype.UUID `json:"session_id"`
	CreatedAt time.Time   `json:"created_at"`
}

func (q *Queries) GetRecentLedgerEntries(ctx context.Context, arg GetRecentLedgerEntriesParams) ([]GetRecentLedgerEntriesRow, error) {
	rows, err := q.db.Query(ctx, getRecentLedgerEntries, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentLedgerEntriesRow
	for rows.Next() {
		var i GetRecentLedgerEntriesRow
		if err := rows.Scan(
			&i.Amount,
			&i.Reason,
			&i.SessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserUsageSummary = `-- name: GetUserUsageSummary :one
SELECT
  COALESCE(SUM(remaining_minutes) FILTER (WHERE expires_at IS NULL OR expires_at > NOW()), 0)::int AS total_balance,
  COALESCE(SUM(remaining_minutes) FILTER (WHERE source = 'free_grant' AND (expires_at IS NULL OR expires_at > NOW())), 0)::int AS free_balance,
  COALESCE(SUM(remaining_minutes) FILTER (WHERE source != 'free_grant' AND (expires_at IS NULL OR expires_at > NOW())), 0)::int AS paid_balance
FROM grants
WHERE user_id = $1
  AND remaining_minutes > 0
`

type GetUserUsageSummaryRow struct {
	TotalBalance int32 `json:"total_balance"`
	FreeBalance  int32 `json:"free_balance"`
	PaidBalance  int32 `json:"paid_balance"`
}

func (q *Queries) GetUserUsageSummary(ctx context.Context, userID uuid.UUID) (GetUserUsageSummaryRow, error) {
	row := q.db.QueryRow(ctx, getUserUsageSummary, userID)
	var i GetUserUsageSummaryRow
	err := row.Scan(&i.TotalBalance, &i.FreeBalance, &i.PaidBalance)
	return i, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :one
INSERT INTO ledger_entries (user_id, grant_id, amount, reason, session_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, grant_id, amount, reason, session_id, created_at
`

type InsertLedgerEntryParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	GrantID   uuid.UUID   `json:"grant_id"`
	Amount    int32       `json:"amount"`
	Reason    string      `json:"reason"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, insertLedgerEntry,
		arg.UserID,
		arg.GrantID,
		arg.Amount,
		arg.Reason,
		arg.SessionID,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GrantID,
		&i.Amount,
		&i.Reason,
		&i.SessionID,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveGrants = `-- name: ListActiveGrants :many
SELECT id, source, initial_minutes, remaining_minutes, expires_at, created_at
FROM grants
WHERE user_id = $1
  AND remaining_minutes > 0
  AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY expires_at ASC NULLS LAST
`

type ListActiveGrantsRow struct {
	ID               uuid.UUID          `json:"id"`
	Source           string             `json:"source"`
	InitialMinutes   int32              `json:"initial_minutes"`
	RemainingMinutes int32              `json:"remaining_minutes"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	CreatedAt        time.Time          `json:"created_at"`
}

func (q *Queries) ListActiveGrants(ctx context.Context, userID uuid.UUID) ([]ListActiveGrantsRow, error) {
	rows, err := q.db.Query(ctx, listActiveGrants, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveGrantsRow
	for rows.Next() {
		var i ListActiveGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.InitialMinutes,
			&i.RemainingMinutes,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refundSessionMinutes = `-- name: RefundSessionMinutes :many
WITH RECURSIVE
  refund_calc AS (
    SELECT GREATEST(0,
      reserved_minutes - GREATEST(1, CEIL(EXTRACT(EPOCH FROM (ended_at - started_at)) / 60))::int
    ) AS total
    FROM interview_sessions
    WHERE id = $3 AND reserved_minutes IS NOT NULL
  ),
  reserves AS (
    SELECT grant_id, -amount AS debit,
           ROW_NUMBER() OVER (ORDER BY created_at DESC) AS rn
    FROM ledger_entries
    WHERE session_id = $3 AND reason = 'session_reserve'
  ),
  distributed AS (
    SELECT r.grant_id, r.debit,
           LEAST(r.debit, rc.total) AS credit,
           rc.total - LEAST(r.debit, rc.total) AS remaining,
           r.rn
    FROM reserves r, refund_calc rc
    WHERE r.rn = 1

    UNION ALL

    SELECT r.grant_id, r.debit,
           LEAST(r.debit, d.remaining) AS credit,
           d.remaining - LEAST(r.debit, d.remaining) AS remaining,
           r.rn
    FROM reserves r
    JOIN distributed d ON r.rn = d.rn + 1
    WHERE d.remaining > 0
  ),
  apply_credits AS (
    UPDATE grants g
    SET remaining_minutes = remaining_minutes + d.credit
    FROM distributed d
    WHERE g.id = d.grant_id
      AND d.credit > 0
      AND g.remaining_minutes + d.credit <= g.initial_minutes
    RETURNING g.id AS grant_id, d.credit
  )
INSERT INTO ledger_entries (user_id, grant_id, amount, reason, session_id)
SELECT $1, ac.grant_id, ac.credit, $2, $3
FROM apply_credits ac
RETURNING grant_id, amount
`

type RefundSessionMinutesParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	Reason    string      `json:"reason"`
	SessionID pgtype.UUID `json:"session_id"`
}

type RefundSessionMinutesRow struct {
	GrantID uuid.UUID `json:"grant_id"`
	Amount  int32     `json:"amount"`
}

func (q *Queries) RefundSessionMinutes(ctx context.Context, arg RefundSessionMinutesParams) ([]RefundSessionMinutesRow, error) {
	rows, err := q.db.Query(ctx, refundSessionMinutes, arg.UserID, arg.Reason, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefundSessionMinutesRow
	for rows.Next() {
		var i RefundSessionMinutesRow
		if err := rows.Scan(&i.GrantID, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reserveMinutes = `-- name: ReserveMinutes :many
WITH RECURSIVE
  locked AS (
    SELECT id, remaining_minutes, expires_at
    FROM grants
    WHERE user_id = $1
      AND remaining_minutes > 0
      AND (expires_at IS NULL OR expires_at > NOW())
    FOR UPDATE
  ),
  eligible AS (
    SELECT id, remaining_minutes,
           ROW_NUMBER() OVER (ORDER BY expires_at ASC NULLS LAST) AS rn
    FROM locked
  ),
  balance_check AS (
    SELECT COALESCE(SUM(remaining_minutes), 0) AS total
    FROM eligible
  ),
  request AS (
    SELECT $3::int AS requested
    FROM balance_check
    WHERE total >= $3
  ),
  distributed AS (
    SELECT e.id AS grant_id, e.remaining_minutes,
           LEAST(e.remaining_minutes, r.requested) AS debit,
           r.requested - LEAST(e.remaining_minutes, r.requested) AS remaining,
           e.rn
    FROM eligible e, request r
    WHERE e.rn = 1

    UNION ALL

    SELECT e.id, e.remaining_minutes,
           LEAST(e.remaining_minutes, d.remaining) AS debit,
           d.remaining - LEAST(e.remaining_minutes, d.remaining) AS remaining,
           e.rn
    FROM eligible e
    JOIN distributed d ON e.rn = d.rn + 1
    WHERE d.remaining > 0
  ),
  apply_debits AS (
    UPDATE grants g
    SET remaining_minutes = g.remaining_minutes - d.debit
    FROM distributed d
    WHERE g.id = d.grant_id AND d.debit > 0
    RETURNING g.id AS grant_id, d.debit
  )
INSERT INTO ledger_entries (user_id, grant_id, amount, reason, session_id)
SELECT $1, ad.grant_id, -ad.debit, 'session_reserve', $2
FROM apply_debits ad
RETURNING grant_id, amount
`

type ReserveMinutesParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	SessionID pgtype.UUID `json:"session_id"`
	Minutes   int32       `json:"minutes"`
}

type ReserveMinutesRow struct {
	GrantID uuid.UUID `json:"grant_id"`
	Amount  int32     `json:"amount"`
}

// Atomically reserves @minutes from the user's grants in FIFO-by-expiry order.
// Returns one row per grant debited. Returns zero rows if balance is insufficient
// (all-or-nothing: no mutations occur when balance < requested).
func (q *Queries) ReserveMinutes(ctx context.Context, arg ReserveMinutesParams) ([]ReserveMinutesRow, error) {
	rows, err := q.db.Query(ctx, reserveMinutes, arg.UserID, arg.SessionID, arg.Minutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReserveMinutesRow
	for rows.Next() {
		var i ReserveMinutesRow
		if err := rows.Scan(&i.GrantID, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
