// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: interview.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acquireGeneratingStatus = `-- name: AcquireGeneratingStatus :one
UPDATE interview_sessions
SET status = 'generating', generating_since = NOW(), updated_at = NOW()
WHERE id = $1 AND status = 'active'
RETURNING id
`

// Atomically set status to 'generating'. Returns the session ID if successful.
// No row returned means the session is not active or already generating.
func (q *Queries) AcquireGeneratingStatus(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, acquireGeneratingStatus, id)
	err := row.Scan(&id)
	return id, err
}

const cleanupStaleGenerating = `-- name: CleanupStaleGenerating :exec
UPDATE interview_sessions
SET status = 'active', generating_since = NULL, updated_at = NOW()
WHERE status = 'generating'
  AND generating_since < NOW() - INTERVAL '5 minutes'
`

// Reset sessions stuck in 'generating' for too long (crash recovery).
func (q *Queries) CleanupStaleGenerating(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupStaleGenerating)
	return err
}

const countInterviewerMessages = `-- name: CountInterviewerMessages :one
SELECT COUNT(*)::int AS count
FROM messages
WHERE session_id = $1 AND role = 'interviewer'
`

// Count completed interviewer turns for turn_count derivation.
func (q *Queries) CountInterviewerMessages(ctx context.Context, sessionID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countInterviewerMessages, sessionID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const getMessagesBySessionOffset = `-- name: GetMessagesBySessionOffset :many
SELECT id, session_id, seq, role, content, input_method, audio_url, created_at
FROM messages
WHERE session_id = $1
ORDER BY seq
OFFSET $2
`

type GetMessagesBySessionOffsetParams struct {
	SessionID uuid.UUID `json:"session_id"`
	Offset    int32     `json:"offset"`
}

// Return messages after the given offset (for known_message_count cursor).
func (q *Queries) GetMessagesBySessionOffset(ctx context.Context, arg GetMessagesBySessionOffsetParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesBySessionOffset, arg.SessionID, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Seq,
			&i.Role,
			&i.Content,
			&i.InputMethod,
			&i.AudioUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionForTurn = `-- name: GetSessionForTurn :one
SELECT s.id, s.user_id, s.question_id, s.status,
       s.config_duration_minutes, s.config_tts_enabled,
       s.config_coach_briefing, s.started_at,
       q.title AS question_title, q.prompt AS question_prompt,
       q.difficulty AS question_difficulty, q.hints AS question_hints
FROM interview_sessions s
JOIN questions q ON q.id = s.question_id
WHERE s.id = $1
`

type GetSessionForTurnRow struct {
	ID                    uuid.UUID   `json:"id"`
	UserID                uuid.UUID   `json:"user_id"`
	QuestionID            uuid.UUID   `json:"question_id"`
	Status                string      `json:"status"`
	ConfigDurationMinutes int32       `json:"config_duration_minutes"`
	ConfigTtsEnabled      bool        `json:"config_tts_enabled"`
	ConfigCoachBriefing   bool        `json:"config_coach_briefing"`
	StartedAt             time.Time   `json:"started_at"`
	QuestionTitle         string      `json:"question_title"`
	QuestionPrompt        string      `json:"question_prompt"`
	QuestionDifficulty    string      `json:"question_difficulty"`
	QuestionHints         pgtype.Text `json:"question_hints"`
}

// Load session + question in a single query for turn execution.
func (q *Queries) GetSessionForTurn(ctx context.Context, id uuid.UUID) (GetSessionForTurnRow, error) {
	row := q.db.QueryRow(ctx, getSessionForTurn, id)
	var i GetSessionForTurnRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuestionID,
		&i.Status,
		&i.ConfigDurationMinutes,
		&i.ConfigTtsEnabled,
		&i.ConfigCoachBriefing,
		&i.StartedAt,
		&i.QuestionTitle,
		&i.QuestionPrompt,
		&i.QuestionDifficulty,
		&i.QuestionHints,
	)
	return i, err
}

const getSessionStatus = `-- name: GetSessionStatus :one
SELECT status, generating_since
FROM interview_sessions
WHERE id = $1
`

type GetSessionStatusRow struct {
	Status          string             `json:"status"`
	GeneratingSince pgtype.Timestamptz `json:"generating_since"`
}

// Lightweight status check for EndSession/CancelSession polling.
func (q *Queries) GetSessionStatus(ctx context.Context, id uuid.UUID) (GetSessionStatusRow, error) {
	row := q.db.QueryRow(ctx, getSessionStatus, id)
	var i GetSessionStatusRow
	err := row.Scan(&i.Status, &i.GeneratingSince)
	return i, err
}

const inlineRecoverStaleGenerating = `-- name: InlineRecoverStaleGenerating :exec
UPDATE interview_sessions
SET status = 'active', generating_since = NULL, updated_at = NOW()
WHERE id = $1
  AND status = 'generating'
  AND generating_since < NOW() - INTERVAL '5 minutes'
`

// Inline crash recovery for EndSession/CancelSession.
// Conditional WHERE makes this idempotent and race-free.
func (q *Queries) InlineRecoverStaleGenerating(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, inlineRecoverStaleGenerating, id)
	return err
}

const releaseGeneratingStatus = `-- name: ReleaseGeneratingStatus :exec
UPDATE interview_sessions
SET status = 'active', generating_since = NULL, updated_at = NOW()
WHERE id = $1 AND status = 'generating'
`

// Revert status to 'active' after a turn completes or fails.
func (q *Queries) ReleaseGeneratingStatus(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, releaseGeneratingStatus, id)
	return err
}
