// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: keep_link_token_uses.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const tryClaimKeepToken = `-- name: TryClaimKeepToken :one
INSERT INTO keep_link_token_uses (token_hash, user_id)
VALUES ($1, $2)
ON CONFLICT (token_hash) DO NOTHING
RETURNING token_hash
`

type TryClaimKeepTokenParams struct {
	TokenHash []byte    `json:"token_hash"`
	UserID    uuid.UUID `json:"user_id"`
}

// Single-use enforcement. Returns the hash on first claim, no row otherwise.
func (q *Queries) TryClaimKeepToken(ctx context.Context, arg TryClaimKeepTokenParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, tryClaimKeepToken, arg.TokenHash, arg.UserID)
	var token_hash []byte
	err := row.Scan(&token_hash)
	return token_hash, err
}
