// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: llm_calls.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertLLMCall = `-- name: InsertLLMCall :one
INSERT INTO llm_calls (session_id, user_id, role, model, input_tokens, output_tokens, estimated_cost, latency_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertLLMCallParams struct {
	SessionID     pgtype.UUID    `json:"session_id"`
	UserID        uuid.UUID      `json:"user_id"`
	Role          string         `json:"role"`
	Model         string         `json:"model"`
	InputTokens   int32          `json:"input_tokens"`
	OutputTokens  int32          `json:"output_tokens"`
	EstimatedCost pgtype.Numeric `json:"estimated_cost"`
	LatencyMs     int32          `json:"latency_ms"`
}

func (q *Queries) InsertLLMCall(ctx context.Context, arg InsertLLMCallParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertLLMCall,
		arg.SessionID,
		arg.UserID,
		arg.Role,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.EstimatedCost,
		arg.LatencyMs,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertLLMCallContent = `-- name: InsertLLMCallContent :exec
INSERT INTO llm_call_content (llm_call_id, prompt, response)
VALUES ($1, $2, $3)
`

type InsertLLMCallContentParams struct {
	LlmCallID uuid.UUID `json:"llm_call_id"`
	Prompt    []byte    `json:"prompt"`
	Response  []byte    `json:"response"`
}

func (q *Queries) InsertLLMCallContent(ctx context.Context, arg InsertLLMCallContentParams) error {
	_, err := q.db.Exec(ctx, insertLLMCallContent, arg.LlmCallID, arg.Prompt, arg.Response)
	return err
}
