// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Annotation struct {
	ID             uuid.UUID `json:"id"`
	EvaluationID   uuid.UUID `json:"evaluation_id"`
	MessageID      uuid.UUID `json:"message_id"`
	AnnotationType string    `json:"annotation_type"`
	Content        string    `json:"content"`
	CreatedAt      time.Time `json:"created_at"`
}

type AuthSession struct {
	ID         uuid.UUID   `json:"id"`
	UserID     uuid.UUID   `json:"user_id"`
	TokenHash  string      `json:"token_hash"`
	ExpiresAt  time.Time   `json:"expires_at"`
	LastActive time.Time   `json:"last_active"`
	IpAddress  *netip.Addr `json:"ip_address"`
	UserAgent  pgtype.Text `json:"user_agent"`
	CreatedAt  time.Time   `json:"created_at"`
}

type CoachAnalysis struct {
	ID                  uuid.UUID   `json:"id"`
	UserID              uuid.UUID   `json:"user_id"`
	Narrative           string      `json:"narrative"`
	WeakestDimension    pgtype.Text `json:"weakest_dimension"`
	ImprovingDimensions []string    `json:"improving_dimensions"`
	TopicGaps           []string    `json:"topic_gaps"`
	SuggestedQuestionID pgtype.UUID `json:"suggested_question_id"`
	SessionsAnalyzed    []uuid.UUID `json:"sessions_analyzed"`
	CreatedAt           time.Time   `json:"created_at"`
	Summary             pgtype.Text `json:"summary"`
}

type EducatorAnalysis struct {
	ID           uuid.UUID   `json:"id"`
	SessionID    uuid.UUID   `json:"session_id"`
	Status       string      `json:"status"`
	ModelAnswer  pgtype.Text `json:"model_answer"`
	GapDeepDives pgtype.Text `json:"gap_deep_dives"`
	CreatedAt    time.Time   `json:"created_at"`
}

type Evaluation struct {
	ID                 uuid.UUID `json:"id"`
	SessionID          uuid.UUID `json:"session_id"`
	ScoreRequirements  int32     `json:"score_requirements"`
	ScoreArchitecture  int32     `json:"score_architecture"`
	ScoreDeepDive      int32     `json:"score_deep_dive"`
	ScoreScalability   int32     `json:"score_scalability"`
	ScoreCommunication int32     `json:"score_communication"`
	ScoreOverall       int32     `json:"score_overall"`
	Strengths          []byte    `json:"strengths"`
	Gaps               []byte    `json:"gaps"`
	Advice             string    `json:"advice"`
	CreatedAt          time.Time `json:"created_at"`
}

type Grant struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	Source           string             `json:"source"`
	StripeEventID    pgtype.Text        `json:"stripe_event_id"`
	InitialMinutes   int32              `json:"initial_minutes"`
	RemainingMinutes int32              `json:"remaining_minutes"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	CreatedAt        time.Time          `json:"created_at"`
}

type InterviewSession struct {
	ID                    uuid.UUID          `json:"id"`
	UserID                uuid.UUID          `json:"user_id"`
	QuestionID            uuid.UUID          `json:"question_id"`
	Status                string             `json:"status"`
	ConfigDurationMinutes int32              `json:"config_duration_minutes"`
	ConfigTtsEnabled      bool               `json:"config_tts_enabled"`
	ConfigCoachBriefing   bool               `json:"config_coach_briefing"`
	StartedAt             time.Time          `json:"started_at"`
	EndedAt               pgtype.Timestamptz `json:"ended_at"`
	TurnCount             int32              `json:"turn_count"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
	ReservedMinutes       pgtype.Int4        `json:"reserved_minutes"`
	ArchivedAt            pgtype.Timestamptz `json:"archived_at"`
	GeneratingSince       pgtype.Timestamptz `json:"generating_since"`
}

type LedgerEntry struct {
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
	GrantID   uuid.UUID   `json:"grant_id"`
	Amount    int32       `json:"amount"`
	Reason    string      `json:"reason"`
	SessionID pgtype.UUID `json:"session_id"`
	CreatedAt time.Time   `json:"created_at"`
}

type LlmCall struct {
	ID            uuid.UUID      `json:"id"`
	SessionID     pgtype.UUID    `json:"session_id"`
	UserID        pgtype.UUID    `json:"user_id"`
	Role          string         `json:"role"`
	Model         string         `json:"model"`
	InputTokens   int32          `json:"input_tokens"`
	OutputTokens  int32          `json:"output_tokens"`
	EstimatedCost pgtype.Numeric `json:"estimated_cost"`
	LatencyMs     int32          `json:"latency_ms"`
	CreatedAt     time.Time      `json:"created_at"`
}

type LlmCallContent struct {
	LlmCallID uuid.UUID `json:"llm_call_id"`
	Prompt    []byte    `json:"prompt"`
	Response  []byte    `json:"response"`
}

type Message struct {
	ID          uuid.UUID   `json:"id"`
	SessionID   uuid.UUID   `json:"session_id"`
	Seq         int32       `json:"seq"`
	Role        string      `json:"role"`
	Content     string      `json:"content"`
	InputMethod pgtype.Text `json:"input_method"`
	AudioUrl    pgtype.Text `json:"audio_url"`
	CreatedAt   time.Time   `json:"created_at"`
}

type OauthAccount struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	Provider   string    `json:"provider"`
	ProviderID string    `json:"provider_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type Question struct {
	ID             uuid.UUID   `json:"id"`
	UserID         pgtype.UUID `json:"user_id"`
	Title          string      `json:"title"`
	Prompt         string      `json:"prompt"`
	Difficulty     string      `json:"difficulty"`
	Tags           []string    `json:"tags"`
	Hints          pgtype.Text `json:"hints"`
	Source         string      `json:"source"`
	CoachRationale pgtype.Text `json:"coach_rationale"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	ImageUrl       pgtype.Text `json:"image_url"`
}

type User struct {
	ID                    uuid.UUID          `json:"id"`
	Email                 string             `json:"email"`
	EmailVerified         bool               `json:"email_verified"`
	PasswordHash          pgtype.Text        `json:"password_hash"`
	DisplayName           string             `json:"display_name"`
	Role                  string             `json:"role"`
	StripeCustomerID      pgtype.Text        `json:"stripe_customer_id"`
	Plan                  string             `json:"plan"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	FreeFullEducatorsUsed int32              `json:"free_full_educators_used"`
}

type UserEvent struct {
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
	SessionID pgtype.UUID `json:"session_id"`
	EventType string      `json:"event_type"`
	Metadata  []byte      `json:"metadata"`
	CreatedAt time.Time   `json:"created_at"`
}
