// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountSeedQuestions(ctx context.Context) (int64, error)
	GetQuestion(ctx context.Context, id uuid.UUID) (Question, error)
	HealthCheck(ctx context.Context) (int32, error)
	ListSeedQuestions(ctx context.Context) ([]ListSeedQuestionsRow, error)
}

var _ Querier = (*Queries)(nil)
