// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountSeedQuestions(ctx context.Context) (int64, error)
	CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error)
	CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error)
	CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (User, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (InterviewSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAuthSession(ctx context.Context, id uuid.UUID) error
	DeleteUserAuthSessions(ctx context.Context, userID uuid.UUID) error
	FindAbandonedSessions(ctx context.Context) ([]uuid.UUID, error)
	GetAnnotationsByEvaluation(ctx context.Context, evaluationID uuid.UUID) ([]GetAnnotationsByEvaluationRow, error)
	GetAuthSessionByToken(ctx context.Context, tokenHash string) (GetAuthSessionByTokenRow, error)
	GetEvaluationBySession(ctx context.Context, sessionID uuid.UUID) (Evaluation, error)
	GetMaxSeqForSession(ctx context.Context, sessionID uuid.UUID) (int32, error)
	GetMessagesBySession(ctx context.Context, sessionID uuid.UUID) ([]Message, error)
	GetMessagesBySessionAfterSeq(ctx context.Context, arg GetMessagesBySessionAfterSeqParams) ([]Message, error)
	GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error)
	GetOAuthAccountsByUser(ctx context.Context, userID uuid.UUID) ([]OauthAccount, error)
	GetQuestion(ctx context.Context, id uuid.UUID) (Question, error)
	GetSession(ctx context.Context, id uuid.UUID) (InterviewSession, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByEmailIncludingDeleted(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByIDIncludingDeleted(ctx context.Context, id uuid.UUID) (User, error)
	InsertAnnotation(ctx context.Context, arg InsertAnnotationParams) error
	InsertEvaluation(ctx context.Context, arg InsertEvaluationParams) (uuid.UUID, error)
	InsertLLMCall(ctx context.Context, arg InsertLLMCallParams) (uuid.UUID, error)
	InsertLLMCallContent(ctx context.Context, arg InsertLLMCallContentParams) error
	InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error)
	ListQuestionsForUser(ctx context.Context, userID pgtype.UUID) ([]ListQuestionsForUserRow, error)
	ListSeedQuestions(ctx context.Context) ([]ListSeedQuestionsRow, error)
	ListSessionsByUser(ctx context.Context, userID uuid.UUID) ([]ListSessionsByUserRow, error)
	MarkSessionCompleted(ctx context.Context, id uuid.UUID) error
	ReactivateUser(ctx context.Context, id uuid.UUID) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	TouchAuthSession(ctx context.Context, id uuid.UUID) error
	UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error
	// NB: Unlike UpdateSessionStatus, this does NOT touch ended_at or turn_count.
	// Used for status transitions after session completion (evaluating → reviewed,
	// → evaluation_failed) where end time and turn count should not change.
	UpdateSessionStatusOnly(ctx context.Context, arg UpdateSessionStatusOnlyParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	VerifyUserEmail(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
