// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: questions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSeedQuestions = `-- name: CountSeedQuestions :one
SELECT COUNT(*) FROM questions WHERE source = 'seed' AND user_id IS NULL
`

func (q *Queries) CountSeedQuestions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSeedQuestions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getQuestion = `-- name: GetQuestion :one
SELECT id, user_id, title, prompt, difficulty, tags, hints, source, coach_rationale, created_at, updated_at
FROM questions
WHERE id = $1
`

func (q *Queries) GetQuestion(ctx context.Context, id uuid.UUID) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestion, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Prompt,
		&i.Difficulty,
		&i.Tags,
		&i.Hints,
		&i.Source,
		&i.CoachRationale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSeedQuestions = `-- name: ListSeedQuestions :many
SELECT id, title, prompt, difficulty, tags, hints, source, created_at
FROM questions
WHERE source = 'seed' AND user_id IS NULL
ORDER BY created_at
`

type ListSeedQuestionsRow struct {
	ID         uuid.UUID   `json:"id"`
	Title      string      `json:"title"`
	Prompt     string      `json:"prompt"`
	Difficulty string      `json:"difficulty"`
	Tags       []string    `json:"tags"`
	Hints      pgtype.Text `json:"hints"`
	Source     string      `json:"source"`
	CreatedAt  time.Time   `json:"created_at"`
}

func (q *Queries) ListSeedQuestions(ctx context.Context) ([]ListSeedQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listSeedQuestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeedQuestionsRow
	for rows.Next() {
		var i ListSeedQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Prompt,
			&i.Difficulty,
			&i.Tags,
			&i.Hints,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
