// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO interview_sessions (user_id, question_id, config_duration_minutes, config_tts_enabled)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, question_id, status, config_duration_minutes, config_tts_enabled,
          config_coach_briefing, started_at, ended_at, turn_count, archived, created_at, updated_at
`

type CreateSessionParams struct {
	UserID                uuid.UUID `json:"user_id"`
	QuestionID            uuid.UUID `json:"question_id"`
	ConfigDurationMinutes int32     `json:"config_duration_minutes"`
	ConfigTtsEnabled      bool      `json:"config_tts_enabled"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (InterviewSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.QuestionID,
		arg.ConfigDurationMinutes,
		arg.ConfigTtsEnabled,
	)
	var i InterviewSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuestionID,
		&i.Status,
		&i.ConfigDurationMinutes,
		&i.ConfigTtsEnabled,
		&i.ConfigCoachBriefing,
		&i.StartedAt,
		&i.EndedAt,
		&i.TurnCount,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findAbandonedSessions = `-- name: FindAbandonedSessions :many
SELECT id FROM interview_sessions
WHERE status = 'active'
  AND started_at + (config_duration_minutes + 5) * INTERVAL '1 minute' < NOW()
`

func (q *Queries) FindAbandonedSessions(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, findAbandonedSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, question_id, status, config_duration_minutes, config_tts_enabled,
       config_coach_briefing, started_at, ended_at, turn_count, archived, created_at, updated_at
FROM interview_sessions
WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (InterviewSession, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i InterviewSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuestionID,
		&i.Status,
		&i.ConfigDurationMinutes,
		&i.ConfigTtsEnabled,
		&i.ConfigCoachBriefing,
		&i.StartedAt,
		&i.EndedAt,
		&i.TurnCount,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT s.id, s.user_id, s.question_id, s.status, s.config_duration_minutes,
       s.config_tts_enabled, s.started_at, s.ended_at, s.turn_count, s.archived,
       s.created_at, q.title AS question_title
FROM interview_sessions s
JOIN questions q ON q.id = s.question_id
WHERE s.user_id = $1
ORDER BY s.created_at DESC
`

type ListSessionsByUserRow struct {
	ID                    uuid.UUID          `json:"id"`
	UserID                uuid.UUID          `json:"user_id"`
	QuestionID            uuid.UUID          `json:"question_id"`
	Status                string             `json:"status"`
	ConfigDurationMinutes int32              `json:"config_duration_minutes"`
	ConfigTtsEnabled      bool               `json:"config_tts_enabled"`
	StartedAt             time.Time          `json:"started_at"`
	EndedAt               pgtype.Timestamptz `json:"ended_at"`
	TurnCount             int32              `json:"turn_count"`
	Archived              bool               `json:"archived"`
	CreatedAt             time.Time          `json:"created_at"`
	QuestionTitle         string             `json:"question_title"`
}

func (q *Queries) ListSessionsByUser(ctx context.Context, userID uuid.UUID) ([]ListSessionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsByUserRow
	for rows.Next() {
		var i ListSessionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.QuestionID,
			&i.Status,
			&i.ConfigDurationMinutes,
			&i.ConfigTtsEnabled,
			&i.StartedAt,
			&i.EndedAt,
			&i.TurnCount,
			&i.Archived,
			&i.CreatedAt,
			&i.QuestionTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionCompleted = `-- name: MarkSessionCompleted :exec
UPDATE interview_sessions
SET status = 'completed', ended_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkSessionCompleted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markSessionCompleted, id)
	return err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE interview_sessions
SET status = $2, ended_at = NOW(), turn_count = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateSessionStatusParams struct {
	ID        uuid.UUID `json:"id"`
	Status    string    `json:"status"`
	TurnCount int32     `json:"turn_count"`
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSessionStatus, arg.ID, arg.Status, arg.TurnCount)
	return err
}

const updateSessionStatusOnly = `-- name: UpdateSessionStatusOnly :exec
UPDATE interview_sessions
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateSessionStatusOnlyParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

// NB: Unlike UpdateSessionStatus, this does NOT touch ended_at or turn_count.
// Used for status transitions after session completion (evaluating → reviewed,
// → evaluation_failed) where end time and turn count should not change.
func (q *Queries) UpdateSessionStatusOnly(ctx context.Context, arg UpdateSessionStatusOnlyParams) error {
	_, err := q.db.Exec(ctx, updateSessionStatusOnly, arg.ID, arg.Status)
	return err
}
