// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveSessionsByIDs = `-- name: ArchiveSessionsByIDs :execrows
UPDATE interview_sessions
SET archived_at = CASE WHEN $1::bool THEN NOW() ELSE NULL END,
    updated_at = NOW()
WHERE id = ANY($2::uuid[])
  AND user_id = $3
  AND CASE WHEN $1::bool THEN archived_at IS NULL ELSE archived_at IS NOT NULL END
`

type ArchiveSessionsByIDsParams struct {
	Archive bool        `json:"archive"`
	Ids     []uuid.UUID `json:"ids"`
	UserID  uuid.UUID   `json:"user_id"`
}

func (q *Queries) ArchiveSessionsByIDs(ctx context.Context, arg ArchiveSessionsByIDsParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveSessionsByIDs, arg.Archive, arg.Ids, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelAbandonedEmptySessions = `-- name: CancelAbandonedEmptySessions :many
UPDATE interview_sessions
SET status = 'cancelled', ended_at = NOW(), archived_at = NOW(), updated_at = NOW()
WHERE status = 'active'
  AND started_at + (config_duration_minutes + 5) * INTERVAL '1 minute' < NOW()
  AND NOT EXISTS (
    SELECT 1 FROM messages m
    WHERE m.session_id = interview_sessions.id AND m.role = 'candidate'
  )
RETURNING id
`

// Batch-cancels abandoned sessions that have zero candidate messages.
// These are empty sessions where no interview happened.
func (q *Queries) CancelAbandonedEmptySessions(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, cancelAbandonedEmptySessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelSession = `-- name: CancelSession :exec
UPDATE interview_sessions
SET status = 'cancelled', ended_at = NOW(), turn_count = $2, archived_at = NOW(), updated_at = NOW()
WHERE id = $1
`

type CancelSessionParams struct {
	ID        uuid.UUID `json:"id"`
	TurnCount int32     `json:"turn_count"`
}

func (q *Queries) CancelSession(ctx context.Context, arg CancelSessionParams) error {
	_, err := q.db.Exec(ctx, cancelSession, arg.ID, arg.TurnCount)
	return err
}

const completeAbandonedActiveSessions = `-- name: CompleteAbandonedActiveSessions :many
UPDATE interview_sessions
SET status = 'completed', ended_at = NOW(), updated_at = NOW()
WHERE status = 'active'
  AND started_at + (config_duration_minutes + 5) * INTERVAL '1 minute' < NOW()
  AND EXISTS (
    SELECT 1 FROM messages m
    WHERE m.session_id = interview_sessions.id AND m.role = 'candidate'
  )
RETURNING id
`

// Batch-completes abandoned sessions that have at least one candidate message.
// These are real interviews that the user forgot to end.
func (q *Queries) CompleteAbandonedActiveSessions(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, completeAbandonedActiveSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActiveSessionsByUser = `-- name: CountActiveSessionsByUser :one
SELECT COUNT(*)::int AS count
FROM interview_sessions
WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) CountActiveSessionsByUser(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveSessionsByUser, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO interview_sessions (user_id, question_id, config_duration_minutes, config_tts_enabled, reserved_minutes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, question_id, status, config_duration_minutes, config_tts_enabled, config_coach_briefing, started_at, ended_at, turn_count, created_at, updated_at, reserved_minutes, archived_at
`

type CreateSessionParams struct {
	UserID                uuid.UUID   `json:"user_id"`
	QuestionID            uuid.UUID   `json:"question_id"`
	ConfigDurationMinutes int32       `json:"config_duration_minutes"`
	ConfigTtsEnabled      bool        `json:"config_tts_enabled"`
	ReservedMinutes       pgtype.Int4 `json:"reserved_minutes"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (InterviewSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.QuestionID,
		arg.ConfigDurationMinutes,
		arg.ConfigTtsEnabled,
		arg.ReservedMinutes,
	)
	var i InterviewSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuestionID,
		&i.Status,
		&i.ConfigDurationMinutes,
		&i.ConfigTtsEnabled,
		&i.ConfigCoachBriefing,
		&i.StartedAt,
		&i.EndedAt,
		&i.TurnCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReservedMinutes,
		&i.ArchivedAt,
	)
	return i, err
}

const findAbandonedSessions = `-- name: FindAbandonedSessions :many
SELECT id FROM interview_sessions
WHERE status = 'active'
  AND started_at + (config_duration_minutes + 5) * INTERVAL '1 minute' < NOW()
`

func (q *Queries) FindAbandonedSessions(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, findAbandonedSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewedSessionIDsForUser = `-- name: GetReviewedSessionIDsForUser :many
SELECT id FROM interview_sessions
WHERE user_id = $1 AND status = 'reviewed' AND archived_at IS NULL
ORDER BY created_at
`

func (q *Queries) GetReviewedSessionIDsForUser(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getReviewedSessionIDsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewedSessionsForUser = `-- name: GetReviewedSessionsForUser :many
SELECT id, user_id, question_id, status, config_duration_minutes, config_tts_enabled, config_coach_briefing, started_at, ended_at, turn_count, created_at, updated_at, reserved_minutes, archived_at FROM interview_sessions
WHERE user_id = $1 AND status = 'reviewed' AND archived_at IS NULL
ORDER BY created_at
`

func (q *Queries) GetReviewedSessionsForUser(ctx context.Context, userID uuid.UUID) ([]InterviewSession, error) {
	rows, err := q.db.Query(ctx, getReviewedSessionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InterviewSession
	for rows.Next() {
		var i InterviewSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.QuestionID,
			&i.Status,
			&i.ConfigDurationMinutes,
			&i.ConfigTtsEnabled,
			&i.ConfigCoachBriefing,
			&i.StartedAt,
			&i.EndedAt,
			&i.TurnCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReservedMinutes,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSession = `-- name: GetSession :one
SELECT s.id, s.user_id, s.question_id, s.status,
       s.config_duration_minutes, s.config_tts_enabled,
       s.config_coach_briefing, s.started_at, s.ended_at,
       s.turn_count, s.archived_at, s.created_at, s.updated_at,
       q.title AS question_title, q.prompt AS question_prompt,
       q.difficulty AS question_difficulty, q.hints AS question_hints
FROM interview_sessions s
JOIN questions q ON q.id = s.question_id
WHERE s.id = $1
`

type GetSessionRow struct {
	ID                    uuid.UUID          `json:"id"`
	UserID                uuid.UUID          `json:"user_id"`
	QuestionID            uuid.UUID          `json:"question_id"`
	Status                string             `json:"status"`
	ConfigDurationMinutes int32              `json:"config_duration_minutes"`
	ConfigTtsEnabled      bool               `json:"config_tts_enabled"`
	ConfigCoachBriefing   bool               `json:"config_coach_briefing"`
	StartedAt             time.Time          `json:"started_at"`
	EndedAt               pgtype.Timestamptz `json:"ended_at"`
	TurnCount             int32              `json:"turn_count"`
	ArchivedAt            pgtype.Timestamptz `json:"archived_at"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
	QuestionTitle         string             `json:"question_title"`
	QuestionPrompt        string             `json:"question_prompt"`
	QuestionDifficulty    string             `json:"question_difficulty"`
	QuestionHints         pgtype.Text        `json:"question_hints"`
}

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuestionID,
		&i.Status,
		&i.ConfigDurationMinutes,
		&i.ConfigTtsEnabled,
		&i.ConfigCoachBriefing,
		&i.StartedAt,
		&i.EndedAt,
		&i.TurnCount,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuestionTitle,
		&i.QuestionPrompt,
		&i.QuestionDifficulty,
		&i.QuestionHints,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, question_id, status, config_duration_minutes, config_tts_enabled, config_coach_briefing, started_at, ended_at, turn_count, created_at, updated_at, reserved_minutes, archived_at FROM interview_sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (InterviewSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i InterviewSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuestionID,
		&i.Status,
		&i.ConfigDurationMinutes,
		&i.ConfigTtsEnabled,
		&i.ConfigCoachBriefing,
		&i.StartedAt,
		&i.EndedAt,
		&i.TurnCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReservedMinutes,
		&i.ArchivedAt,
	)
	return i, err
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT s.id, s.user_id, s.question_id, s.status, s.config_duration_minutes,
       s.config_tts_enabled, s.started_at, s.ended_at, s.turn_count, s.archived_at,
       s.created_at, q.title AS question_title
FROM interview_sessions s
JOIN questions q ON q.id = s.question_id
WHERE s.user_id = $1
ORDER BY s.created_at DESC
`

type ListSessionsByUserRow struct {
	ID                    uuid.UUID          `json:"id"`
	UserID                uuid.UUID          `json:"user_id"`
	QuestionID            uuid.UUID          `json:"question_id"`
	Status                string             `json:"status"`
	ConfigDurationMinutes int32              `json:"config_duration_minutes"`
	ConfigTtsEnabled      bool               `json:"config_tts_enabled"`
	StartedAt             time.Time          `json:"started_at"`
	EndedAt               pgtype.Timestamptz `json:"ended_at"`
	TurnCount             int32              `json:"turn_count"`
	ArchivedAt            pgtype.Timestamptz `json:"archived_at"`
	CreatedAt             time.Time          `json:"created_at"`
	QuestionTitle         string             `json:"question_title"`
}

func (q *Queries) ListSessionsByUser(ctx context.Context, userID uuid.UUID) ([]ListSessionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsByUserRow
	for rows.Next() {
		var i ListSessionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.QuestionID,
			&i.Status,
			&i.ConfigDurationMinutes,
			&i.ConfigTtsEnabled,
			&i.StartedAt,
			&i.EndedAt,
			&i.TurnCount,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.QuestionTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionCompleted = `-- name: MarkSessionCompleted :exec
UPDATE interview_sessions
SET status = 'completed', ended_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkSessionCompleted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markSessionCompleted, id)
	return err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE interview_sessions
SET status = $2, ended_at = NOW(), turn_count = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateSessionStatusParams struct {
	ID        uuid.UUID `json:"id"`
	Status    string    `json:"status"`
	TurnCount int32     `json:"turn_count"`
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSessionStatus, arg.ID, arg.Status, arg.TurnCount)
	return err
}

const updateSessionStatusOnly = `-- name: UpdateSessionStatusOnly :exec
UPDATE interview_sessions
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateSessionStatusOnlyParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

// NB: Unlike UpdateSessionStatus, this does NOT touch ended_at or turn_count.
// Used for status transitions after session completion (evaluating → reviewed,
// → evaluation_failed) where end time and turn count should not change.
func (q *Queries) UpdateSessionStatusOnly(ctx context.Context, arg UpdateSessionStatusOnlyParams) error {
	_, err := q.db.Exec(ctx, updateSessionStatusOnly, arg.ID, arg.Status)
	return err
}
