// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: stripe_webhook_dedup.sql

package db

import (
	"context"
)

const tryClaimWebhookEvent = `-- name: TryClaimWebhookEvent :one
INSERT INTO stripe_webhook_dedup (event_id, event_type)
VALUES ($1, $2)
ON CONFLICT (event_id) DO NOTHING
RETURNING event_id
`

type TryClaimWebhookEventParams struct {
	EventID   string `json:"event_id"`
	EventType string `json:"event_type"`
}

// Returns the event_id on first claim; returns no row on subsequent claims.
// Use the no-row return as the signal "this event was already handled".
func (q *Queries) TryClaimWebhookEvent(ctx context.Context, arg TryClaimWebhookEventParams) (string, error) {
	row := q.db.QueryRow(ctx, tryClaimWebhookEvent, arg.EventID, arg.EventType)
	var event_id string
	err := row.Scan(&event_id)
	return event_id, err
}
