// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: user_events.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getMostRecentKeptOrCanceledForPeriod = `-- name: GetMostRecentKeptOrCanceledForPeriod :one
SELECT event_type
FROM user_events
WHERE user_id = $1
  AND event_type IN ('subscription_auto_canceled', 'subscription_kept')
  AND (metadata->>'subscription_id') = $2::text
  AND (metadata->>'current_period_start')::timestamptz = $3::timestamptz
ORDER BY created_at DESC
LIMIT 1
`

type GetMostRecentKeptOrCanceledForPeriodParams struct {
	UserID             uuid.UUID `json:"user_id"`
	SubscriptionID     string    `json:"subscription_id"`
	CurrentPeriodStart time.Time `json:"current_period_start"`
}

// For multi-firing dedup: did a 'subscription_kept' event arrive after the
// most recent 'subscription_auto_canceled' for this period? If yes, the user
// already kept their sub for this period; don't re-cancel.
func (q *Queries) GetMostRecentKeptOrCanceledForPeriod(ctx context.Context, arg GetMostRecentKeptOrCanceledForPeriodParams) (string, error) {
	row := q.db.QueryRow(ctx, getMostRecentKeptOrCanceledForPeriod, arg.UserID, arg.SubscriptionID, arg.CurrentPeriodStart)
	var event_type string
	err := row.Scan(&event_type)
	return event_type, err
}

const hasAutoCanceledThisPeriod = `-- name: HasAutoCanceledThisPeriod :one
SELECT EXISTS (
  SELECT 1 FROM user_events
  WHERE user_id = $1
    AND event_type = 'subscription_auto_canceled'
    AND (metadata->>'subscription_id') = $2::text
    AND (metadata->>'current_period_start')::timestamptz = $3::timestamptz
)
`

type HasAutoCanceledThisPeriodParams struct {
	UserID             uuid.UUID `json:"user_id"`
	SubscriptionID     string    `json:"subscription_id"`
	CurrentPeriodStart time.Time `json:"current_period_start"`
}

// Returns true if a subscription_auto_canceled event already exists for
// this (user, subscription, period). Backs the multi-firing dedup in §4.1.
// metadata->>'current_period_start' is RFC3339 text written by cancelMetadata.
func (q *Queries) HasAutoCanceledThisPeriod(ctx context.Context, arg HasAutoCanceledThisPeriodParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasAutoCanceledThisPeriod, arg.UserID, arg.SubscriptionID, arg.CurrentPeriodStart)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertSubscriptionAutoCanceledEvent = `-- name: InsertSubscriptionAutoCanceledEvent :exec
INSERT INTO user_events (user_id, event_type, metadata)
VALUES ($1, 'subscription_auto_canceled', $2)
`

type InsertSubscriptionAutoCanceledEventParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Metadata []byte    `json:"metadata"`
}

// Composed insert for the cancel decision. metadata is already-marshaled JSON.
func (q *Queries) InsertSubscriptionAutoCanceledEvent(ctx context.Context, arg InsertSubscriptionAutoCanceledEventParams) error {
	_, err := q.db.Exec(ctx, insertSubscriptionAutoCanceledEvent, arg.UserID, arg.Metadata)
	return err
}

const insertSubscriptionKeptEvent = `-- name: InsertSubscriptionKeptEvent :exec
INSERT INTO user_events (user_id, event_type, metadata)
VALUES ($1, 'subscription_kept', $2)
`

type InsertSubscriptionKeptEventParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Metadata []byte    `json:"metadata"`
}

func (q *Queries) InsertSubscriptionKeptEvent(ctx context.Context, arg InsertSubscriptionKeptEventParams) error {
	_, err := q.db.Exec(ctx, insertSubscriptionKeptEvent, arg.UserID, arg.Metadata)
	return err
}
